### ISSUE TITLE
A1 - Translated 1 article into Thai and published in my medium

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#101]
I wrapped 2 articles into one article which are from Cointelegraph's and Astar's and I post it on my Medium and Blockdit.

https://panupongpnp.medium.com/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%80%E0%B8%8A%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%A1%E0%B8%95%E0%B9%88%E0%B8%AD%E0%B8%A3%E0%B8%B0%E0%B8%AB%E0%B8%A7%E0%B9%88%E0%B8%B2%E0%B8%87-2-%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%82%E0%B9%88%E0%B8%B2%E0%B8%A2-polkadot-%E0%B9%81%E0%B8%A5%E0%B8%B0-cosmos-93f67b81a1f2?source=user_profile---------0----------------------------

https://www.blockdit.com/posts/61359f94dbbc820c5a27b2df

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10

**Comment by SotaWatanabe** [comment]
@pnpdude Thanks for working on this. Please teach me how well the article and movie were spread. We don't fund SDN for activities themselves but fund the viewers.

**Comment by pnpdude** [comment]
> @pnpdude Thanks for working on this. Please teach me how well the article and movie were spread. We don't fund SDN for activities themselves but fund the viewers. 

Thank you for your reply, Sota. 

About the one follower on Medium, Medium is not the place where most of Thai people read the article, so I have decided to publish on another platform which is Blockdit. It is the platform which most Thai readers use.

As you can check below, each of my Astar's posts will contain engagement include viewers, and share. And, they are organic.

https://www.blockdit.com/pages/60ba3f6524ebe60d23d81ce0

**Comment by fiexer** [comment]
Thanks! Please share the stats again 2 weeks after publication.
Thanks :-)

**Comment by fiexer** [comment]
Thanks for booking a slot for a call 
Let's discuss all your work

**Comment by pnpdude** [comment]
> Thanks for booking a slot for a call 
> Let's discuss all your work

Sure, Marteen. Looking forward to discussing with you.

**Comment by pnpdude** [comment]
> Thanks! Please share the stats again 2 weeks after publication.
> Thanks :-)

Here

![cosmos_shidenmedium jpg](https://user-images.githubusercontent.com/90048622/134166570-07bc8065-26a2-46d8-ab01-82da6c3647f7.jpeg)

**Comment by fiexer** [comment]
Total points: 3
