### ISSUE TITLE
A1 - Translated article into japanese and posted on my media (note).

### ISSUE THREAD

**Issue by yudai-ogata** [PlasmNetwork/growth-program#102]
【翻訳】Announcing the $30M Astar/Shiden Ecosystem Growth Fund【Astar Network】
https://note.com/you425/n/ncb32b0566ed2
https://twitter.com/you425you/status/1434891259500392450?s=20

Twitter：@you425you
Telegram：@you425
Discord：you425#7409
Shiden wallet address：YjuqPYaRnBop94qv925q4H5gCD2rWvb6VJiHYmHQnN8Y1xP

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10

**Comment by SotaWatanabe** [comment]
こちらありがとうございます！Community Programの基準として最近設けたのですが、翻訳という「行為」自体にではなく、記事が「どれだけ読まれたか」におうじてポイントを計算するので、viewer数の記載もいただけますと幸いです

**Comment by yudai-ogata** [comment]
EVMの実装おめでとうございます！
WASMとdApp Stakingも楽しみです。

現状 viewer57 スキ3 なのでまだまだですね…。
翻訳記事は基本公式アンバサダーのみということなので、違う内容考えます。

引き続き応援していきますのでよろしくお願いいたします！

**Comment by SotaWatanabe** [comment]
いえ、応援していただいている気持ちはありがたいです！ありがとうございます。最近、海外でgoogle翻訳しただけで公開とかしているやつらがいまして、アクティビティのみにファンディングはしないことにしました。引き続きよろしくおねがいします。

@fiexer the number of viewers is 57 and 3 likes.

**Comment by fiexer** [comment]
Thanks! Please share the stats again 2 weeks after publication.
Thanks :-)

**Comment by fiexer** [comment]
Please do share your stats for this article or it will not be counted for the September rewards.

**Comment by yudai-ogata** [comment]
Hi.
Share the results of this article.

view:164
like:7

**Comment by fiexer** [comment]
Total points: 3
