### ISSUE TITLE
A1-Posting to Twitter

### ISSUE THREAD

**Issue by kubvil** [PlasmNetwork/growth-program#106]
https://twitter.com/kubvil551/status/1434972904844890120
https://twitter.com/kubvil551/status/1434975972940566535

telegram handle: @kubvil88
my Shiden wallet address: WBR6xowc6fNGhKkJgaF5ELx4UfLVjr14iFdpXqJ5w9jZMC5
Discord kubvil#4326

**Comment by fiexer** [comment]
Please share those tweets with the translation you made.
Twitter followers/likes/retweets counts in the outreach of your translated article.
