### ISSUE TITLE
A6: Step Guide to Getting Started with Smart Contract Development

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#12]
I wrote an article about how to get started developing Smart Contracts.
The article links are below.
https://realtakahashi-work.medium.com/how-to-start-about-smart-contract-development-of-astar-network-fbeb0b1f3eac

Shiden Address:b49pUAMgek5HePmC8dMWCgrhVUFkzKXy6P4UinF9Wnwnwxt
Discord:s.takahashi
Telegram:s takahashi

**Comment by fiexer** [comment]
Great! Thanks a lot for sharing this.
Can you also just add your wallet, this is only needed for the first submission.

Thanks

**Comment by realtakahashi** [comment]
I apologize for the omission. I have listed Shiden's Address, Discord, and Telegram's handle.

**Comment by fiexer** [comment]
Can you share the current stats for the story so we can calculate the points?

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by realtakahashi** [comment]
![image](https://user-images.githubusercontent.com/38233656/132143141-dde6b877-a6f1-44a0-bcc2-889ee975a25a.png)

**Comment by fiexer** [comment]
Total reward point: 9
