### ISSUE TITLE
C2 - Community Management

### ISSUE THREAD

**Issue by vladylime** [PlasmNetwork/growth-program#13]
Hi, I'm Vlady. I am a representative of the Russian community Astar / Shiden
https://t.me/astar_rus

For over 1 year I have been making contributions for the project.
In my reports, I will point out some of them.

Telegram: @vladylimes
Wallet: av6AYeM556wzE6ct1RKyCfTnZNXCfhWuxc93PVo7BWmXsMW

**Comment by fiexer** [comment]
Can you please add me an admin in the community so I can see the stats for the channel?
Thanks

**Comment by vladylime** [comment]
> Can you please add me an admin in the community so I can see the stats for the channel?
> Thanks

done

**Comment by fiexer** [comment]
Rewards for Community management can be shared to PromoTeam?

**Comment by vladylime** [comment]
> Rewards for Community management can be shared to PromoTeam?

yes, please
