### ISSUE TITLE
A3 - Created a video about Shiden Network's Update. [video] 

### ISSUE THREAD

**Issue by KryptosChain** [PlasmNetwork/growth-program#135]
Shiden Progress Update: https://youtu.be/97Be_yQGGMs?t=651
Twitter: @KryptosChain
Telegram: @KryptosChain
Shiden Address:  YAozdoSG5a2uNTze1ZocQtdM1ZxixLJ7Fcwj8cmAEKeyJCD

#crowdloan #shiden #shidennetwork

**Comment by fiexer** [comment]
Thanks a lot!
Total points: 11

Feedback is always welcome in this post.
