### ISSUE TITLE
A1 - Translation of Astar / Shiden articles

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#136]
We prepared translations for Astar / Shiden medium articles and we will keep doing that, to bring Astar / Shiden to as wide a polish audience as possible and to take down the language barrier. Here are some articles we translated and published onto Elevate Medium and Polish telegram. We also promote them on Elevate Twitter account. 

https://elevate-cv.medium.com/astar-network-%C5%82%C4%85czy-si%C4%99-z-crypto-climate-accord-85872359f28e
https://elevate-cv.medium.com/wsp%C3%B3%C5%82praca-z-microsoft-uczyni-astar-bardziej-stabiln%C4%85-sieci%C4%85-bad66ea043a6
https://elevate-cv.medium.com/shiden-astar-network-faq-a675e1c8f7fb
https://elevate-cv.medium.com/onfinality-partner-infrastruktury-astar-556dcf6ae3fc
https://elevate-cv.medium.com/plasm-zmienia-nazw%C4%99-na-astar-network-5224e3481f59
https://elevate-cv.medium.com/astar-community-program-a4d9af084e78

We are going to translate all the most important articles coming from Astar and will also start live YT sessions covering Shiden and Astar. 

We are getting started and hungry for more:)

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by jimmy-tudeski** [comment]
Here are the stats for articles translated:

https://elevate-cv.medium.com/astar-community-program-a4d9af084e78
![11](https://user-images.githubusercontent.com/68714636/134379817-464f378a-5edb-4706-b4a5-dad2c529a23c.png)

https://elevate-cv.medium.com/plasm-zmienia-nazw%C4%99-na-astar-network-5224e3481f59
![12](https://user-images.githubusercontent.com/68714636/134379956-5cab0d91-c4b3-423e-b1fb-4021ed14e94b.png)

https://elevate-cv.medium.com/onfinality-partner-infrastruktury-astar-556dcf6ae3fc
![13](https://user-images.githubusercontent.com/68714636/134381008-af5e7d21-cbc7-4096-93c9-6b33470458bc.png)

https://elevate-cv.medium.com/shiden-astar-network-faq-a675e1c8f7fb
![14](https://user-images.githubusercontent.com/68714636/134381193-113e7bba-b4f2-4d46-840b-8c0d05548b44.png)

https://elevate-cv.medium.com/wsp%C3%B3%C5%82praca-z-microsoft-uczyni-astar-bardziej-stabiln%C4%85-sieci%C4%85-bad66ea043a6
![15](https://user-images.githubusercontent.com/68714636/134381827-c434ea18-da08-4d43-beca-812c96cb6e29.png)

https://elevate-cv.medium.com/astar-network-%C5%82%C4%85czy-si%C4%99-z-crypto-climate-accord-85872359f28e
![16](https://user-images.githubusercontent.com/68714636/134382129-9038be70-93b2-4766-b8f1-31ab03582b64.png)

https://elevate-cv.medium.com/microsoft-japan-zapowiada-wsparcie-w-budowie-ekosystemu-astar-shiden-44502395ef7f
![17](https://user-images.githubusercontent.com/68714636/134382248-17e6e8fb-577a-4402-bda3-a3f6658e6ecf.png)

https://elevate-cv.medium.com/zapowied%C5%BA-astar-v2-0-multi-chain-dapp-hub-3f9d3657f209
![18](https://user-images.githubusercontent.com/68714636/134382412-cd2690e9-3784-49ef-9403-7c7b67f2ccc7.png)

**Comment by fiexer** [comment]
Total points: 17
