### ISSUE TITLE
A1 - Translated 2 articles into Thai and published in my medium and social media

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#137]
The first one for today is funding news, which I post on my Medium and also my Blockdit

https://panupongpnp.medium.com/astar-%E0%B9%81%E0%B8%A5%E0%B8%B0-shiden-%E0%B9%84%E0%B8%94%E0%B9%89%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B9%80%E0%B8%87%E0%B8%B4%E0%B8%99%E0%B8%AA%E0%B8%99%E0%B8%B1%E0%B8%9A%E0%B8%AA%E0%B8%99%E0%B8%B8%E0%B8%99%E0%B8%81%E0%B8%A7%E0%B9%88%E0%B8%B2-30-%E0%B8%A5%E0%B9%89%E0%B8%B2%E0%B8%99%E0%B8%94%E0%B8%AD%E0%B8%A5%E0%B8%A5%E0%B9%88%E0%B8%B2%E0%B8%AB%E0%B9%8C-bc33a9734c3b

https://www.blockdit.com/posts/6136fd7bdf855a0766e63570

The second one is Marteen's interview with PromoTeam, which I also post on my Medium and Blockdit. However, I decided to cut the article into 3 parts, it is easy to digest for reader and persuade them to follow the article's series.

https://panupongpnp.medium.com/%E0%B8%9A%E0%B8%97%E0%B8%AA%E0%B8%B1%E0%B8%A1%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%93%E0%B9%8C-promoteam-%E0%B8%81%E0%B8%B1%E0%B8%9A-maarten-%E0%B8%88%E0%B8%B2%E0%B8%81-astar-shiden-1-3-9c3d9be26ea5

https://www.blockdit.com/posts/6137655b790d95074c4e0bbc

As you can see on Blockdit, the engagement after I post Astar & Shiden is increasingly surprising and I also gain some more followers!

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10

**Comment by SotaWatanabe** [comment]
Thanks for your work @pnpdude. We evaluate the number of viewers, not the translation itself. It seems that you only have 1 follower on Medium. Please tell me how well your article was spread in Thai.

Hope we can get the reply this week.

**Comment by pnpdude** [comment]
> Thanks for your work @pnpdude. We evaluate the number of viewers, not the translation itself. It seems that you only have 1 follower on Medium. Please tell me how well your article was spread in Thai.
> 
> Hope we can get the reply this week. 

Thank you for your reply, Sota.

About the one follower on Medium, Medium is not the place where most of Thai people read the article, so I have decided to publish on another platform which is Blockdit. It is the platform which most Thai readers use.

As you can check below, each of my Astar's posts will contain engagement include viewers, and share. And, they are organic.

https://www.blockdit.com/pages/60ba3f6524ebe60d23d81ce0

**Comment by SotaWatanabe** [comment]
okay thanks for letting me know! @fiexer FYI

**Comment by fiexer** [comment]
Thanks for your contributions
You are approved as a translator! Thanks for your work

Total points for these contributions: 6

**Comment by pnpdude** [comment]
> Thanks for your contributions
> You are approved as a translator! Thanks for your work
> 
> Total points for these contributions: 6

Thank you, Maarten!

**Comment by pnpdude** [comment]
> Thanks for your contributions
> You are approved as a translator! Thanks for your work
> 
> Total points for these contributions: 6

![funding](https://user-images.githubusercontent.com/90048622/134166985-16c65d20-598b-403d-a901-90a591e14493.jpg)

**Comment by pnpdude** [comment]
> Thanks for your contributions
> You are approved as a translator! Thanks for your work
> 
> Total points for these contributions: 6

![funding2](https://user-images.githubusercontent.com/90048622/134167022-f3eccc48-e3dd-4de7-abee-9237b0f912d4.jpg)

**Comment by pnpdude** [comment]
> Thanks for your contributions
> You are approved as a translator! Thanks for your work
> 
> Total points for these contributions: 6
These will be stats of interview article

![image](https://user-images.githubusercontent.com/90048622/134167262-4779da05-20cd-472c-8a4e-5ee233313708.png)

**Comment by pnpdude** [comment]
![interviw](https://user-images.githubusercontent.com/90048622/134167431-f3cdfcc3-b8d0-4d3f-9d24-a87e80899d17.jpg)
