### ISSUE TITLE
C2 - Community Management - Belarus Community

### ISSUE THREAD

**Issue by donatello345** [PlasmNetwork/growth-program#138]
I have created a community of your Twitter in Belarusian, I will develop it, post current news there.

Twitter - https://twitter.com/AstarNetworkBL

Wallet - at4b8VCsh7bAQCK3KRvM5jTSGSGjVZD5kndWx1myRTbvfHq

!!! If I need to fix something, add something, then write here and I will definitely do it.

**Comment by donatello345** [comment]
Also, I could become a moderator in discord and create my own chat #Belarus for the Belarusian community.

**Comment by donatello345** [comment]
![image](https://user-images.githubusercontent.com/82183467/132981426-21d835fe-f731-43c7-bbb1-1fbee04a1adf.png)

At the moment, the community consists of about 30 people, in the near future I plan to hold several contests and increase the audience to 200-500 participants.

There are also plans to hold an online meeting, a call with my community.

**Comment by donatello345** [comment]
@fiexer Can I become an official ambassador?

**Comment by fiexer** [comment]
> @fiexer Can I become an official ambassador?

Please contact me on Telegram or Discord.
