### ISSUE TITLE
C2 - Community Management Thailand

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#139]
My name is Panupong Chunid
Thai community manager
Telegram :
https://t.me/Astarthai

My Shiden address  :
Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Thanks a lot.

Can you make me admin in your group? I joined today.
Looking forward to our call on Thursday to discuss your Ambassador status.

**Comment by pnpdude** [comment]
> Thanks a lot.
> 
> Can you make me admin in your group? I joined today.
> Looking forward to our call on Thursday to discuss your Ambassador status.

Got it, can't wait to discuss with you too!
