### ISSUE TITLE
C1 - Introducing Astar | Shiden Network (Polkadot) to Octopus Network (Near)

### ISSUE THREAD

**Issue by marvelet** [PlasmNetwork/growth-program#147]
Introducing and setting up meeting between Sota Watanabe and Maarten Henskens from Astar Shiden Network with Louis Liu and Aaron Ting from Octopus Network.

Initial meeting happened in Mid August 2021. With the results that both parties are planning to build a network bridge between both ecosystems.

**Comment by fiexer** [comment]
Can you please add your Shiden address to your contributions?
Thanks a lot 🙏

**Comment by marvelet** [comment]
YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

This is my Shiden Wallet, many thanks!
