### ISSUE TITLE
A5 - Social engagement invitation for Astar/Shiden Twitter status

### ISSUE THREAD

**Issue by anaelleltd** [PlasmNetwork/growth-program#149]
Topic: Metamask x Shiden
Link: [Metamask integrates Shiden network to give you a substrate address for your existing Ethereum account!](https://www.reddit.com/r/Kusama/comments/peb4t3/metamask_integrates_shiden_network_to_give_you_a/)
Shiden wallet: Z1fHUw3G38sDiuJ8mGBGoiCJwyV5Qg2zdrNxzV49Drhf2ft

**Comment by fiexer** [comment]
Have you started/created more discussion topics on the Subreddit of Kusama about Astar and Shiden?
Or is this the only one?

Thanks

**Comment by anaelleltd** [comment]
Hi Maarten,

I have made the following posts about Astar/Shiden on r/Kusama:

[https://www.reddit.com/r/Kusama/comments/ooo5aj/shining_a_light_on_shidenastar_network_the/](https://www.reddit.com/r/Kusama/comments/ooo5aj/shining_a_light_on_shidenastar_network_the/)

[Metamask integrates Shiden network to give you a substrate address for your existing Ethereum account!](https://www.reddit.com/r/Kusama/comments/peb4t3/metamask_integrates_shiden_network_to_give_you_a/)

[Mission EVM: Moonriver and Shiden are rapidly expanding the Kusama ecosystem...for pennies.](https://www.reddit.com/r/Kusama/comments/pn4otq/mission_evm_moonriver_and_shiden_are_rapidly/
)

I probably should have bundled them into one post, apologies. >_<

Thanks.

**Comment by fiexer** [comment]
Total points: 5
