### ISSUE TITLE
A2	Creating interesting memes by viverrinii#0535 

### ISSUE THREAD

**Issue by Strongyloides** [PlasmNetwork/growth-program#150]
https://twitter.com/caocaovalue/status/1435507100302528512?s=20

discord: viverrinii#0535 
twitter: @caocaovalue
telegram: @caocaovalue
shiden adress: YwG4iSBymPKx7FjCqj7jEacfefinw1jYvKNck3zGm9eRKem

**Comment by fiexer** [comment]
Total points: 1
