### ISSUE TITLE
A8 - Astar Animated logo

### ISSUE THREAD

**Issue by boodovskiy** [PlasmNetwork/growth-program#154]
https://youtu.be/2SKPafhaSmE
Twitter post: https://twitter.com/boodovskiy/status/1435727073163816969

Discord: budovskiy#4624
Telegram: budovskiy87
Twitter: @boodovskiy

Shiden address: YFTJBnTYxmVES377a1iwnY8SHmNZHYaBhhRPxwBSQ7tKJHq

**Comment by fiexer** [comment]
That's one cool video!
Thanks a lot for creating this.

**Comment by fiexer** [comment]
Total points: 10

**Comment by boodovskiy** [comment]
@fiexer Thank you!
