### ISSUE TITLE
A1 - Translate ASTR crowdloan event to persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1575]
I translated the ASTR crowdloan event article in medium to Persian language 
https://telegra.ph/رویداد-Astar-Crowdloan-Event-قسمت-اول-10-18

Discord handle: pooya#0847
Telegram handle:
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۸-۰۰۲۲۳۳_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140661566-6e965a7c-efc9-4e86-887a-d8fd849cdbbd.jpg)
