### ISSUE TITLE
A1 – Builder & Grant Program article in French - 2

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#1576]
September 2021 :
- Article about the Builder & Grant Program into French with a presentation list of all the projects granted : https://medium.com/@Gunit3124/astar-shiden-builders-et-grants-program-f1731979ee7b

![image](https://user-images.githubusercontent.com/85451570/138191835-0820f947-e756-4053-8adb-a48df14e7eeb.png)

**Comment by fiexer** [comment]
Only October articles are rewarded in this phase.
