### ISSUE TITLE
A1 - Translate ASTR crowdloan event into Thai

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1577]
https://panupongpnp.medium.com/astar-crowdloan-event-%E0%B8%95%E0%B8%AD%E0%B8%99-1-33a7a525de8f

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pnpdude** [comment]
![image](https://user-images.githubusercontent.com/90048622/140860187-2de9d96e-7be0-4700-ba9a-ee2f5862456c.png)
Sorry for my late response, Maarten

**Comment by fiexer** [comment]
Added!
