### ISSUE TITLE
A6 - how to make polkadot.js wallet guide in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1581]
I Make an article to help for make polkadot.js wallet
https://telegra.ph/طریقه-ساخت-کیف-پول-polkadotjs-10-20

Discord handle: pooya#0847
Telegram handle: 
SDN wallet:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
It shared on telegram group we can't see number of views
