### ISSUE TITLE
A5 - Twitter Engagement - Shiden Dapp Staking Explained / Double Reward Ann

### ISSUE THREAD

**Issue by marvelet** [PlasmNetwork/growth-program#1583]
Twitter Thread link : 
https://twitter.com/rudayruday/status/1450034271968645122?s=20

Stats (on Oct 22, 2021) : 27 RTs, 1 Qt , 96 Likes

Graphics (1920x1080) :
![dapp staking - twit 1](https://user-images.githubusercontent.com/87793956/138383446-3d65da70-bea8-494d-b1ef-d40cf24ced1b.jpg)

Wallet :
YZn94AfMctQHscmKotKX5AdDMtr4mhypKjet99FdYrmmimg

**Comment by fiexer** [comment]
Part of community management.
In case you want to use social engagement make a summary of your monthly activity.
