### ISSUE TITLE
A1 - translate article about sending tokens to metamask in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1585]
I translate a tutorial about sending tokens to metamask 
https://telegra.ph/ارسال-توکن-ها-10-22

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address 
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۸-۰۰۰۰۲۲_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140899835-2b8732f7-0e84-42c7-a637-ffaff2f2dfc5.jpg)

**Comment by fiexer** [comment]
Added!
