### ISSUE TITLE
A1 - Write an article about Shiden tokenomic in Thai

### ISSUE THREAD

**Issue by nuttapat007** [PlasmNetwork/growth-program#1588]
https://scarlet-flannel-c82.notion.site/Shiden-network-EP-1-1c3b87f7ede9409b82ab89b0efb3d769

Shiden address : a7df2mcfXK9ic7hJcTgtxXJ7WSrJSphqsopYVNFRhTcJtst
telegram : jude_olo

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !

**Comment by nuttapat007** [comment]
@Gunit2481 I don't think notion have the way to see those stats.
