### ISSUE TITLE
A4 - Hosted an Astar Meetup 

### ISSUE THREAD

**Issue by Mucunguzi256** [PlasmNetwork/growth-program#1590]
I hosted an Aster meetup of 35 attendants and discussed the major rational of dApp staking. I took the audience through the process of using Polkadot.JS in particular, choosing shiden network from the portal.
https://drive.google.com/drive/folders/1-YMmVf7NknE9pNQ7dcKQBmzcurN9C187

Discord
Mucu256#3205

SDN Address
Wr3L92YY3fcyCWAPFEKxbwLKHwo7mtf5ShNWJfn9xizzQjT

**Comment by fiexer** [comment]
Added!
