### ISSUE TITLE
A3 - How to Withdraw Shiden Network Coin from Astar Dashboard to Kucoin Exchange

### ISSUE THREAD

**Issue by snars2018** [PlasmNetwork/growth-program#1591]
I've created a video tutorial on How to Withdraw Shiden Network Coin ( SDN ) from Astar Dashboard to Kucoin Exchange. Here's the link below:

https://youtu.be/zzNfGXpWjSk

============
https://twitter.com/snars11

SDN address: Xg1oajKXxYDMQh6RPSWTX3ScAmdcAA41gVpHmJw5TuhmhFJ

**Comment by fiexer** [comment]
Points added.
