### ISSUE TITLE
A8 - Art work about Astar by Elena#4267

### ISSUE THREAD

**Issue by mycryptoabs** [PlasmNetwork/growth-program#1592]
My art - https://twitter.com/temewhy/status/1451981140454170631?s=20

alenkaboom - node name
Elena#4267 - discord
@temewhy - twitter
YCSbrYQHvQAtiZNdLtVBP8WAhssRttDLkaV1Gk14Z48iyVe - Shiden wallet
Email address - mycryptoabs@gmail.com

**Comment by fiexer** [comment]
Already rewarded in the graphic challenge.
