### ISSUE TITLE
A1 - Astar Crowdloan Event - Turkish content

### ISSUE THREAD

**Issue by iamcem007** [PlasmNetwork/growth-program#1593]
https://medium.com/@cempehlivan7/astar-crowdloan-etkinli%C4%9Fi-1-b%C3%B6l%C3%BCm-9f45c076dcba 
Telegram : @iamcemo
Twitter:  @iamcemm
Discord: iamcemm#5992
Dot js wallet : 5EUhsf5nwjuP1d7u1rLbBZ2z1ENqpsafVuUBwXaXn84Y1RoG

**Comment by iamcem007** [comment]
> https://medium.com/@cempehlivan7/astar-crowdloan-etkinli%C4%9Fi-1-b%C3%B6l%C3%BCm-9f45c076dcba Telegram : @iamcemo Twitter: @iamcemm Discord: iamcemm#5992 Dot js wallet : 5EUhsf5nwjuP1d7u1rLbBZ2z1ENqpsafVuUBwXaXn84Y1RoG İTS ALLOW ANY CHAİN

ZcYdU1oPAMtb7Rn9MfgqKiFo5nVoQbst9ozw52oruK4VY2x İT MY PLASM NETWOK DO JS WALLET

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
