### ISSUE TITLE
A1 - Article about use cases Shiden and Kintsugi.

### ISSUE THREAD

**Issue by boodovskiy** [PlasmNetwork/growth-program#1596]
Article: Featured Use Case: Kintsugi & Shiden
https://boodovskiy87.medium.com/featured-use-case-kintsugi-shiden-f2dae7bd5f96

Discord: budovskiy#4624
Twitter: twitter.com/boodovskiy
Shiden wallet: YFTJBnTYxmVES377a1iwnY8SHmNZHYaBhhRPxwBSQ7tKJHq
![image](https://user-images.githubusercontent.com/15303736/138589309-c905f4a6-71c0-4f9c-9fc2-05ecb6ed6873.png)

**Comment by fiexer** [comment]
Duplicate from https://github.com/PlasmNetwork/growth-program/issues/279 ?

**Comment by boodovskiy** [comment]
@fiexer Check please the publication date of the original article. Mine was earlier.

**Comment by fiexer** [comment]
Added!
