### ISSUE TITLE
A8 - Astar Network Mystery Logo

### ISSUE THREAD

**Issue by boodovskiy** [PlasmNetwork/growth-program#1597]
https://youtu.be/uKwY1EGnrcI
https://twitter.com/boodovskiy/status/1452225877048238080

https://user-images.githubusercontent.com/15303736/138590684-83a2b36a-b7e8-4311-8c9d-3aafa47dfc31.mp4

Discord: budovskiy#4624
Telegram: budovskiy87
Twitter: @boodovskiy

Shiden address: YFTJBnTYxmVES377a1iwnY8SHmNZHYaBhhRPxwBSQ7tKJHq

**Comment by fiexer** [comment]
Added
