### ISSUE TITLE
A8 - Article about Shiden tokenomics in persian 

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1598]
I wrote an article about Siden tokenomics and SDN token in persian
https://telegra.ph/توضیحاتی-راجب-توکنومیک-SDN-10-17

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۸-۰۰۰۰۳۴_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140899937-d42efb0c-9aff-4cb7-9198-e272e9733c03.jpg)

**Comment by fiexer** [comment]
Added!
