### ISSUE TITLE
A1 - Get a reward for developing

### ISSUE THREAD

**Issue by cryptodmeme** [PlasmNetwork/growth-program#1599]
I wrote a blog on subsocial
https://app.subsocial.network/4932/get-a-reward-for-developing-21041

This in non-technical text. Mainly about dapp staking.
I know we love technology, but I dared to give you a simple explanation.

twitter/telegram : cryptodmeme
discord : CrypTod#5916
wallet address : Ww388xVGbU2HAyRbabXEkERZJBpw8R1XGxXXQSW3pUXoPBg

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by cryptodmeme** [comment]
https://twitter.com/cryptodmeme/status/1451447269312450560

impression : 473
Engagement : 18
Likes : 1
Retweet : 1

@fiexer , Thanks

**Comment by fiexer** [comment]
Added!
