### ISSUE TITLE
A1 - Understanding Dapp Staking

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#1600]
I wrote an article sharing my opinion about dapp staking.

https://mamora-toga.medium.com/understanding-dapp-staking-23ad9e0d8b29

Statistics:
![image](https://user-images.githubusercontent.com/37278708/138628871-2dd16c4f-5ad2-45c0-b6cd-ebdc61311125.png)

![image](https://user-images.githubusercontent.com/37278708/138628899-409c8f56-de73-421b-bc6f-ef6a8db6eb5b.png)

![image](https://user-images.githubusercontent.com/37278708/138628929-65d75366-3e91-4e82-8e65-ae99c95d6ea6.png)

**Comment by fiexer** [comment]
Added
