### ISSUE TITLE
A6 - Dapp Staking Guide

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#1601]
I wrote a tutorial on dapp staking.

https://mamora-toga.medium.com/shiden-network-dapp-staking-guide-8497825f80f6

Statistics:
![image](https://user-images.githubusercontent.com/37278708/138629586-cbffeb64-312f-4d51-84ca-1b5d05266537.png)

![image](https://user-images.githubusercontent.com/37278708/138629610-cc09ffcc-9678-453a-8e40-7377acbb8f19.png)

![image](https://user-images.githubusercontent.com/37278708/138629634-8723b76c-3577-4713-90b8-ac1e2db8ce49.png)

**Comment by fiexer** [comment]
Added!
