### ISSUE TITLE
A5 - social engagement in twitter 

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1602]
I talked to someone who loves dot and has a lot of followers and he also encouraged his followers to follow our project and community.
https://twitter.com/arashdre21/status/1452542260340568064?t=QvoauP7anfBKBBqvxLwdCw&s=19

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Not qualify for community reward program.
