### ISSUE TITLE
A5 - Promoting Crowdloan ;)

### ISSUE THREAD

**Issue by abk400** [PlasmNetwork/growth-program#1604]
Promotion of crowdloan in twitter
https://twitter.com/Hot_invest/status/1452948814478942210?s=20

Discord: KArt#3451
Shiden wallet address: 5DXENXeqdtxvNUcLJkqqtaZ2jb1zwYbdQUXHKxS44J3Duo1m
Telegram: @GoodService4u

**Comment by fiexer** [comment]
Read guidelines on social engagement.
