### ISSUE TITLE
A8 - Shibuya collator fund application NataDark

### ISSUE THREAD

**Issue by Prufful** [PlasmNetwork/growth-program#1606]
Discord - prufful#6879
Node name - NataDark
https://shibuya.subscan.io/account/abdpHcxM4xkJa5WUjrEfXYWS3rTUUEPYYrRPEYswKdVgKo9
email - prufful@gmail.com
Shiden adress - abdpHcxM4xkJa5WUjrEfXYWS3rTUUEPYYrRPEYswKdVgKo9

**Comment by Prufful** [comment]
14 days have passed, the node is in work, thanks

**Comment by fiexer** [comment]
Fund sent and added you on the list.
Please onboard your collator.

Thanks
