### ISSUE TITLE
A1 - dApp Staking article

### ISSUE THREAD

**Issue by Kahonnohak** [PlasmNetwork/growth-program#1607]
Wrote about dApp Staking and how to stake with common troubleshooting.
https://note.com/kahon_design/n/n56dda46b3c66

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Kahonnohak** [comment]
Hi sorry for being slow:
total views at 27 Nov is 528.
Thanks

**Comment by Gunit2481** [comment]
Added !
