### ISSUE TITLE
A1 - dApp Staking article from Polkadotters

### ISSUE THREAD

**Issue by pmensik** [PlasmNetwork/growth-program#1608]
We have created an article about dApp staking along with a Twitter post that had some nice reactions from the community

https://polkadotters.medium.com/astar-network-and-dapp-staking-unique-solution-for-developers-68fd4930919d

https://twitter.com/Polkadotters1/status/1451604098764181517

Overall it has more than 600 views with almost 200 of reads and counting :-)

Discord - pmensik#3434
Telegram - @pmensik
Shiden address - XoPmK9TagQEAFusNy1DYAEgLuft4Ly5wGwM66bvAYLhC3km

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pmensik** [comment]
Hey @fiexer, sure thing, here you go

![image](https://user-images.githubusercontent.com/3175660/140938433-3592fdfe-9dee-4963-a467-71b8c562af47.png)

**Comment by fiexer** [comment]
Added!
