### ISSUE TITLE
A7 - dApp staking stress test

### ISSUE THREAD

**Issue by Vert2785** [PlasmNetwork/growth-program#1610]
Actively participated in dApp staking stress test on Shibuya network from first minutes when it launched.
Created several bugs and enhancements to UI and process, some of them already fixed by the team. Here are list of created issues:

https://github.com/PlasmNetwork/astar-apps/issues/28
https://github.com/PlasmNetwork/astar-apps/issues/29
https://github.com/PlasmNetwork/astar-apps/issues/30
https://github.com/PlasmNetwork/astar-apps/issues/31
https://github.com/PlasmNetwork/astar-apps/issues/33
https://github.com/PlasmNetwork/astar-apps/issues/39
https://github.com/PlasmNetwork/astar-apps/issues/64
https://github.com/PlasmNetwork/astar-apps/issues/65

SDN address: bHV7Rd9htiUbxG2jH9skezP5ncQK4wn3QxmKMbCfd5zcrh9
Email: vertusprem@gmail.com

**Comment by fiexer** [comment]
This is not part of the community rewards program.
Bugs for MVP do not qualify.

**Comment by Vert2785** [comment]
I have created this issue based on Overview what we have for community reward program:
"A7 | Coding, **bug hunting**, development work for the Astar ecosystem."

@fiexer if bugs for MVP not qualified, it might be worth to add some examples what bugs are qualified for "bug hunting" category. Thanks anyway for opportunity to be a part of the project.
