### ISSUE TITLE
A1 - translate an article about the problems Astar solves

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1611]
I translate an article about the problems Astar solves from website
https://telegra.ph/پروژه-یASTAR-Network-چه-مشکلاتی-را-حل-می-کند-10-25

Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۸-۰۰۲۱۵۶_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140903085-5522249a-1800-4ec2-9d6a-52aa50f6136c.jpg)

**Comment by fiexer** [comment]
Added!
