### ISSUE TITLE
A8 - Earn $SDN by participating in this quest! #Build2Earn Quest

### ISSUE THREAD

**Issue by fiexer** [PlasmNetwork/growth-program#1612]
![astar-cover](https://user-images.githubusercontent.com/40356749/135799652-175e0d24-1255-4c26-87e8-447b192fd4b2.gif)

Hi Astarians!

Besides having regular challenges we are now taking you on a quest.
During this quest, we take you on a journey through our Build2Earn protocol.

This quest is designed to test our infrastructure when we would upgrade our stakers limit from 512 to 2048. After a successful stress test on Shibuya, we will deploy this on Shiden.

**Stake on a project in our Shibuya dApp store and earn $SDN for each vote!**

**Question**: ask them in this thread on GitHub!

## Quest
- Create an account on Polkadot JS Extension
- Connect to Shibuya in our portal
- Use our faucet bot to transfer $SBY (test tokens) to your wallet
- Stake those tokens on a dApp listed in our dApp store

## Rewards
- Total quest reward pool: 2500 SDN
- Pool will be divided into all wallets that staked on listed projects
- Rewards will be distributed to the same wallet as used on Shibuya (address is the same as on Shiden)
- Rewards will be distributed on November 6th, 2021.

## Rules
- Quest ends **Wednesday, November 3rd, 8 PM UTC**
- Minimum amount to stake on a dApp is 5 SBY
- Limited stakers for each project is 2048 stakers
- You can stake on different projects to earn more rewards

## Resources
- Documentation: https://docs.astar.network
- Polkadot JS Extension: https://polkadot.js.org/extension/
- Astar portal: https://portal.astar.network/
- How to use Shibuya faucet: https://docs.astar.network/build/testnet-faucet
- How to use dApp staking: https://www.youtube.com/watch?v=b9r4VlXJkh0

**Comment by fiexer** [comment]
Quest extended by 2 days!

**Comment by murchelon** [comment]
I got to the point where i recieve SBY in my Shibuya accont. But.. i cant find out how to connect this account in the Astra Portal.. to stake the coins !
Please, do anyone have any advice? thanks

**Comment by murchelon** [comment]
> u

I understood ! I was able to finish the quest ! Thanks a lot!

**Comment by fiexer** [comment]
All pools are full! Quest is finished!

**Comment by fiexer** [comment]
A total of 25119 valid wallets joined this quest!
The total rewards pool will be divided between every valid wallet:
2500/25119=0,0995262550260759

We will round this number to 0.1 SDN! So we increased the reward pool to 2512
Distribution will happen today after a successful test on Shibuya.
