### ISSUE TITLE
A1 - Use Case Article About Shiden and Kinstsugi #279 

### ISSUE THREAD

**Issue by pro100programmer** [PlasmNetwork/growth-program#1613]
Wrote an article to educate people on the value of Shiden network
https://medium.com/@gavrysh.vova/featured-use-case-kintsugi-and-shiden-8b3616a42f60

Shiden wallet: YAXMMDKYhJoKKMWhr1qHTcaEroJhvqsVSMmABdEkxUimwyz
Telegram handle: @vova_op
Discord handle: PRO100SKILL#3728

**Comment by fiexer** [comment]
Already added!
