### ISSUE TITLE
A7 - Added new features  [Astar portal, No.2]

### ISSUE THREAD

**Issue by impelcrypto** [PlasmNetwork/growth-program#1615]
* EVM support with Ethereum wallet (H160 address scheme)
https://github.com/PlasmNetwork/astar-apps/pull/90

* Added 'max button' and 'staked balance' in Unstake UI 
https://github.com/PlasmNetwork/astar-apps/pull/121

SDN address: avf5nPmTfztUfq3gi1Bm3vBcEUHghUyrqRppXmsmDZ5hfrD
email: impelcrypto@gmail.com

**Comment by fiexer** [comment]
The scores put the importance of the work and the time into consideration.
Added!
