### ISSUE TITLE
A8 - Infographic about Astar

### ISSUE THREAD

**Issue by cryptosats** [PlasmNetwork/growth-program#1616]
I designed an infographic to educate the people about Astar Netwrok

https://www.linkedin.com/posts/cmalize_blockchain-astarnetwork-polkadot-activity-6849303551164866560-oOZW

SHIDEN WALLET ADDRESS- Y5iCr5tyia5UwQnjVjSE9nDWJoFtowywG3BSfmsqLzNgy6W
TELEGRAM ID- @christopedia

**Comment by fiexer** [comment]
Added.
