### ISSUE TITLE
A8 - Infographics about Astar & Shiden Network

### ISSUE THREAD

**Issue by cryptosats** [PlasmNetwork/growth-program#1617]
I designed some infographics to educate the masses about Astar & Shiden Network

https://www.linkedin.com/posts/cmalize_blockchain-astarnetwork-scalable-activity-6849514930765348864-8EC4
https://www.linkedin.com/posts/cmalize_blockchain-asta-usecase-activity-6849652539697201153-twHi
https://www.linkedin.com/posts/cmalize_blockchain-shiden-astar-activity-6850019430634672128-Jgzu
https://www.linkedin.com/posts/cmalize_blockchain-shiden-smartcontracts-activity-6850710214610583552-SYRu
https://www.linkedin.com/posts/cmalize_shiden-smartcontracts-dapps-activity-6851024663083028480--Uv_
https://www.linkedin.com/posts/cmalize_astarnetwork-smartcontracts-relaychain-activity-6851616857024143360-7BI2
https://www.linkedin.com/posts/cmalize_astarnetwork-weeklyupdate-multichain-activity-6851966622257684480-bjsY
https://twitter.com/ChrisMalize3/status/1446430461614563331?s=20
https://twitter.com/ChrisMalize3/status/1446437284136603697?s=20
https://www.linkedin.com/posts/cmalize_astarnetwork-dapps-incentive-activity-6852696937540419584-KX9I
https://www.linkedin.com/posts/cmalize_astarnetwork-projects-network-activity-6853240059299274753-2WxZ
https://twitter.com/ChrisMalize3/status/1447691221049253897?s=20
https://twitter.com/ChrisMalize3/status/1447824186836127745?s=20
https://www.linkedin.com/posts/cmalize_polkadot-parachain-auction-activity-6856963236403798017-t4Pk
https://www.linkedin.com/posts/cmalize_astar-shiden-buildersprogram-activity-6858439051393957888-aWoa
https://www.linkedin.com/posts/cmalize_shiden-partners-anyswap-activity-6858709622019125248-Dkw9
https://twitter.com/ChrisMalize3/status/1452751860876681223?s=20
https://www.linkedin.com/posts/cmalize_dappstaking-shiden-dapps-activity-6859063455048073216-OTX1
https://www.linkedin.com/posts/cmalize_dapp-staking-astar-activity-6859411856390414336-ik7N
https://twitter.com/ChrisMalize3/status/1453353250799955968?s=20
https://twitter.com/ChrisMalize3/status/1453649788847673345?s=20
https://www.linkedin.com/posts/cmalize_astar-crowdloan-strategy-activity-6859807104992088064-96Gn

**Comment by fiexer** [comment]
Added!
