### ISSUE TITLE
A1 - Article about Astar Ecosystem & Build2Earn

### ISSUE THREAD

**Issue by cryptosats** [PlasmNetwork/growth-program#1618]
I wrote some articles to educate people about Astar Network (Ecosystem overview & Build2Earn)

https://www.linkedin.com/pulse/astar-introduces-build2earn-chris-malize-nim
https://www.linkedin.com/pulse/top-6-blockchain-projects-watch-2022-chris-malize-nim
https://www.linkedin.com/pulse/astar-network-brings-smart-contracts-polkadot-chris-malize-nim

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by cryptosats** [comment]
The First article had 32 views and 1 like.
The second article had 9 likes,11 comments and 134 views
The third article had 15 views

**Comment by fiexer** [comment]
Added!
