### ISSUE TITLE
A4 - I organized a meetup about Astar & Shiden Network

### ISSUE THREAD

**Issue by cryptosats** [PlasmNetwork/growth-program#1620]
I organized a meetup about Astar & Shiden Network to educate the masses about the ecosystem and use case. This was done in collaboration with Brian.

Here is the link to the presentation:
https://docs.google.com/presentation/d/1R5FDpeGOT0A670bsZ3s3irxgz7XRKrJqMcB4EyKCmfE/edit?usp=sharing

**Comment by fiexer** [comment]
Added
