### ISSUE TITLE
A5 - Social engagement.

### ISSUE THREAD

**Issue by igorporoshin** [PlasmNetwork/growth-program#1621]
Weekly ecosystem updates have been published:

**Week 1:**

EN topics:
https://www.altcoinstalks.com/index.php?topic=235266.msg1234632#msg1234632
https://bitcointalk.org/index.php?topic=5355407.msg58138561#msg58138561

RU topics:
https://bitcointalk.org/index.php?topic=5362748.msg58138642#msg58138642
https://cp0x.com/topic/419-plasm-realizaciya-plasma-na-osnove-substrate/?do=findComment&comment=11453

**Week 2:**

EN topics:
https://www.altcoinstalks.com/index.php?topic=235266.msg1239197#msg1239197
https://bitcointalk.org/index.php?topic=5355407.msg58193849#msg58193849

RU topics:
https://bitcointalk.org/index.php?topic=5362748.msg58193885#msg58193885
https://cp0x.com/topic/419-plasm-realizaciya-plasma-na-osnove-substrate/?do=findComment&comment=11493

**Week 3:**

EN topics:
https://www.altcoinstalks.com/index.php?topic=235266.msg1243798#msg1243798
https://bitcointalk.org/index.php?topic=5355407.msg58249683#msg58249683

RU topics:
https://bitcointalk.org/index.php?topic=5362748.msg58249562#msg58249562
https://cp0x.com/topic/419-plasm-realizaciya-plasma-na-osnove-substrate/?do=findComment&comment=11531

**Week 4:**

EN topics:
https://www.altcoinstalks.com/index.php?topic=235266.msg1248605#msg1248605
https://bitcointalk.org/index.php?topic=5355407.msg58304698#msg58304698

RU topics:
https://bitcointalk.org/index.php?topic=5362748.msg58304627#msg58304627
https://cp0x.com/topic/419-plasm-realizaciya-plasma-na-osnove-substrate/?do=findComment&comment=11602

Telegram: @igporoshin
Shiden address: aXueqwkrgUTVufyocGeBPm6NeSYp5k1ooPPJAGq3Ts7FtgF

**Comment by fiexer** [comment]
Added!
