### ISSUE TITLE
A8 - Shiden and Astar Infographics and social network promotion   (PromoTeam / October 2021 )

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#1622]
A8 - Shiden and Astar Infographics and  social network promotion  of this infographics  (PromoTeam / October 2021 )

https://t.me/ParachainNews/849		Infographics																							
https://t.me/ParachainNews/893		Infographics																							

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by fiexer** [comment]
First infographic is not made by PromoTeam.
Second added!
