### ISSUE TITLE
C2 - Russian Community Support and Development 

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#1624]
C2 - Russian Community Support and Development 

Russian community Astar / Shiden
https://t.me/astar_rus 1375+ 

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by fiexer** [comment]
Added!
