### ISSUE TITLE
A3 Create a video about Astar/Shiden Network

### ISSUE THREAD

**Issue by charan0318** [PlasmNetwork/growth-program#1627]
#233  My Small Artwork for Astar ~ will definitely do more for upcoming month. I am new , thanks for opportunity

https://user-images.githubusercontent.com/88229908/139542301-9a680ba1-a6d7-4a73-9115-77845d965236.mp4

Tweet link : https://twitter.com/charan_0426/status/1454645266879975432?t=10rUAQYPFihplvqJ3yLM-Q&s=19

Address : YPFMsm16RqfwfefRqQCQKXxoM55bfPgp1CwJHur5rPgisiq

**Comment by fiexer** [comment]
Added!
