### ISSUE TITLE
A1 - Analyse of each dapp in SHIDEN dappstore (october 2021) (French)

### ISSUE THREAD

**Issue by GreatTeacherKez** [PlasmNetwork/growth-program#1629]
In this article, I try to make a review of each dapp in SHIDEN Network dappstore, presenting the project or contract.

 link: https://medium.com/@kekezousmk/dappstore-review-analyse-de-chaque-dapps-et-contrats-disponibles-actuellement-sur-astar-octobre-4e86497657d3
Twitter: @greatteacherkez
Shiden adress: WAyw2mtxkRk9vjmwBdGivFduhVmGEeCH8JAXVmREzku92a8

**Comment by fiexer** [comment]
Cool! Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by GreatTeacherKez** [comment]
Hi maarten,
Sure, i'll send you my stats in next days for the first article.
Thanks!

**Comment by GreatTeacherKez** [comment]
Hi marteen i send you a screen of my stats for the first article, and
resend the same for the second responding to the other mail. Thanks!
Dappstore review article: views 81  read 43 read ratio 53% fan 5

**Comment by Gunit2481** [comment]
Added !
