### ISSUE TITLE
C1 - Introduced Astar Network to Polygon 

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#163]
I bumped into Sreenjoy Mallick, the Growth specialist of Polygon at Zenlink chat. We had a private chat and decided to find a synergy between Astar and Polygon. We created a Telegram group, had an introductory meeting along with Sota and Maarten. We are looking at building a bridge between Astar and Polygon.

Website: https://polygon.technology/

**Comment by fiexer** [comment]
See spreadsheet with follow-up stats
