### ISSUE TITLE
A4 - French AMA on Twitch with Bld & Maarten for Polkadot Francophonie

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#1630]
October 2021 :

- Astar AMA on Twitch for Polkadot Francophonie with @bLd75 & @fiexer - 2021 Oct 27 for 1:15h.
Twitter : https://twitter.com/Polkadot_FR/status/1453626203034771465?s=20
Twitch : https://www.twitch.tv/polka_franco
Replay YT : https://www.youtube.com/watch?v=reTqG-72H1c&t=2s

Overview of Astar, features (dApps Staking, Layer 2), Ambassador Program, Builder program, Community Program, Ecosystem, News, Q&A

**Comment by fiexer** [comment]
Added!
