### ISSUE TITLE
C2 – Community Management – October 2021 

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#1633]
Hi, this is my community management participation for October 2021 and all the stats of the groups to follow the evolution of our ecosystem’s involvement and my participation in those groups.

Discord : Polkadot francophonie (411 members), CryptoMatrix (15k members). Astar & Shiden Network (16k members), Polkadot (Official) (14k members), Journal Du Coin (8k members), ChaosDAO (270 members)
Twitter : 873 followers & 9 tweets about Astar & Shiden
With bld, we manage the twitter of @AstarNetworkFR (317 followers & 50 tweets) and the telegram group of Astar Network France (344 members).

Telegram : @Gunit31
Discord : @g'ₑₓₚₑcₜ cₕₐₒₛ#3121
Twitter : @gunit3124 https://twitter.com/gunit3124
Wallet : Z5VAv3wwBuH15d1gAgjztz8CQPG6rwekFYxavgjhggJicsk

**Comment by fiexer** [comment]
Added!
