### ISSUE TITLE
A1 - Translate ASTR crowdloan event part 2 into Turkısh

### ISSUE THREAD

**Issue by iamcem007** [PlasmNetwork/growth-program#1634]
https://medium.com/@cempehlivan7/astar-crowdloan-etkinli%C4%9Fi-2-b%C3%B6l%C3%BCm-4447fc09123e
telegram:@iamcemo
twiter:@iamcemm
gmail:cempehlivan7@gmail.com

**Comment by fiexer** [comment]
This will be added to November rewards!

Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
