### ISSUE TITLE
A1 - Translate Astar Crowdloan event Article to persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1635]
I translated Astar Crowdloan event to persian
https://telegra.ph/ترجمه-قسمت-دوم-astar-crowdloan-event-11-01

Discord handle: pooya#0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
This will be added to November.
Do not forget to share stats.

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
