### ISSUE TITLE
C2 - Community management for Astar India and Astar Official group - Oct 2021

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#1636]
For the Astar Indian group, currently, the members stand at 118 in number. There is an approx. growth of 20% from the last month.  https://t.me/AstarandShidenNetworkIndia. Also, alongside other ambassadors, I have been fulfilling my role of managing the official TG group for 3 hours daily during weekdays.

**Comment by fiexer** [comment]
Added!
