### ISSUE TITLE
C2- Twitter Management for Astar India - Oct 2021

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#1638]
So, the Twitter management for Astar India has received some good engagement responses in the month of Oct 2021. Total impressions for every post reached approximately 16,000 new users. and engagement rate stands at 0.05 (which is 20x of what it was last month) along with 90% followers increase in Oct versus last month. (attaching the stats excel sheet). https://twitter.com/astarnetworkIN
[daily_tweet_activity_metrics_astarnetworkIN_20211001_20211101_en.csv](https://github.com/PlasmNetwork/growth-program/files/7453613/daily_tweet_activity_metrics_astarnetworkIN_20211001_20211101_en.csv)

**Comment by fiexer** [comment]
This will be added as part of your community management.
