### ISSUE TITLE
C1 - Introduced Astar Network to Emiswap

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#164]
I reached out to Stacy, the CMO of Emiswap. Stacy forwarded my message to her team mates and Ismail Bagshier, the BD, responded to me positively. We had an introductory meeting, created a Telegram group, and the most recent news is that Emiswap have applied for the Builders Program.

Website: https://about.emiswap.com/
Telegram: https://t.me/EmiSwap_Official

**Comment by fiexer** [comment]
See spreadsheet with follow-up stats
