### ISSUE TITLE
A1 - Informing about the Astar and Shiden projects / Translation of articles into Russian / October / 2021

### ISSUE THREAD

**Issue by Celsiu** [PlasmNetwork/growth-program#1644]
Astar Crowdloan Event — Part I / Translation of the article into Russian - https://medium.com/@sir_Celsiu_s/%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3%D1%83-%D0%B0%D1%81%D1%82%D0%B0%D1%80-%D1%87%D0%B0%D1%81%D1%82%D1%8C-i-60043be7ef58

Astar Welcomes Commonwealth Labs & Webb Technologies as Core Companies Behind the Protocol / Translation of the article into Russian - https://medium.com/@sir_Celsiu_s/astar-%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D1%83%D0%B5%D1%82-commonwealth-labs-%D0%B8-webb-technologies-%D0%B2-%D0%BA%D0%B0%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%B5-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D1%85-%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B9-%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D1%85-%D0%B7%D0%B0-5e9d0cd91ff3

Astar Crowdloan Event — Part II / Translation of the article into Russian - https://medium.com/@sir_Celsiu_s/%D0%BC%D0%B5%D1%80%D0%BE%D0%BF%D1%80%D0%B8%D1%8F%D1%82%D0%B8%D0%B5-%D0%BF%D0%BE-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3%D1%83-astar-%D1%87%D0%B0%D1%81%D1%82%D1%8C-ii-1f772a4e8a2d

**Comment by fiexer** [comment]
This will be added to November!

Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:

[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by vladylime** [comment]
some articles are already in the translation archive, Google translated. BUT! he fixed the mistakes that google makes
I would say that the transfer is 3+ points, out of 5 possible

**Comment by Celsiu** [comment]
> some articles are already in the translation archive, Google translated. BUT! he fixed the mistakes that google makes I would say that the transfer is 3+ points, out of 5 possible

Hi !
Sounds like you are a professional translator ... give me a link to these articles, where it is done on 5 points

**Comment by togamamora** [comment]
Please add the statistics screenshots here.

**Comment by Celsiu** [comment]
> Пожалуйста, добавьте сюда скриншоты статистики.

Hello !
![stats](https://user-images.githubusercontent.com/93481015/144100943-8c3dcd2a-5946-4433-8564-96b1b8da247b.png)

**Comment by Celsiu** [comment]
> Please add the statistics screenshots here.
Hello !
![stats](https://user-images.githubusercontent.com/93481015/144101959-bfa4371f-df22-4ee3-898a-bad29afb5698.png)

**Comment by Gunit2481** [comment]
Added !
