### ISSUE TITLE
A6 -Tutorial / Step-by-step /Japanese manual for SBY testnet participation

### ISSUE THREAD

**Issue by kuma56** [PlasmNetwork/growth-program#1645]
I have posted an introductory statement about the SBY Testnet rewards program that is currently in place.
This program is a very interesting project that expands the possibilities of dApps Staking and has rewards for users.
On the other hand, for those who are not familiar with Astar/Shiden, the operation is complicated and hard to understand, so we need a how to manual that anyone can easily participate.
Since there was no manual in Japanese, I wrote one for the Japanese community.

https://twitter.com/kuma56_munage/status/1453976532792139779?s=21

Twitter: @kuma56_munage
Telegram: @Ayanico27
Discord: @AyaNico27
Shiden wallet address: bRBJvMQvXgPBJpNn9pTvkVxYcmLXGaWUNKJ5St3yLs8Mcdt

**Comment by kuma56** [comment]
In addition, I shared the corresponding Twitter URL with the Astar Discord Japanese community.

https://discord.com/channels/644182966574252073/659677166241447956/905243420086390834

**Comment by fiexer** [comment]
Added!
