### ISSUE TITLE
A1 Spanish Translation of articles related to the news, alliances and events announced in the month of October.

### ISSUE THREAD

**Issue by ercab2408** [PlasmNetwork/growth-program#1646]
Hi everyone
These 16 articles have been translated and posted on several social media like medium, telegram and discord in Spanish.
I comply with a strict verification and disclaimer in every translation. Taking care of the image and credibility of the project. For this month of November I will have a general repository in medium for all users in Spanish and that they can locate the articles by TAG.

October List 
https://ercab24.medium.com/astar-network-evento-de-prestamo-colectivo-y-subasta-parte-ii-64ee5e4f1ecd

https://ercab24.medium.com/bware-labs-se-une-al-protocolo-shiden-build2earn-9db4dae61d1e

https://ercab24.medium.com/kaco-finance-reglas-sobre-las-recompensas-de-shiden-dappstaking-6b4b0d6abe94

https://ercab24.medium.com/astar-network-da-la-bienvenida-a-commonwealth-labs-y-webb-technologies-como-empresas-principales-ebc2cc696f84

https://ercab24.medium.com/cryptospells-comienza-en-el-dapps-staking-de-shiden-63b17d47a097

https://ercab24.medium.com/nutbox-walnut-se-une-al-protocolo-build2earn-de-shiden-50c0d1aa451

https://ercab24.medium.com/polkaex-se-une-al-protocolo-shiden-build2earn-2371126e1d91

https://ercab24.medium.com/por-qu%C3%A9-decidimos-respaldar-a-astar-en-las-subastas-de-parachain-polkadot-1403d407aba4

https://ercab24.medium.com/prestamo-colectivo-de-astar-network-parte-i-3e7480b09478

https://ercab24.medium.com/nftylabs-se-une-a-nuestro-programa-de-constructores-61db99bb4a34

https://ercab24.medium.com/evento-de-lanzamiento-de-evm-nft-fa3f7a81493f

https://ercab24.medium.com/dapp-staking-stress-test-en-shibuya-658436cfd827

https://ercab24.medium.com/shiden-se-asocia-con-anyswap-54aceefda817

https://ercab24.medium.com/shiden-mi-colaboraci%C3%B3n-con-crypto-heroes-ef1f3f333974

https://ercab24.medium.com/dapp-staking-a-sido-desplegado-en-shiden-network-build2earn-6fd0c627bb28

https://ercab24.medium.com/anuncio-de-astar-v2-0-dapp-hub-multicadena-56c4d5ed6c42

**Comment by fiexer** [comment]
Can you share all the stats of the articles?
Or average for all articles made?

How to see stats:

[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by ercab2408** [comment]
Sure
![StatsmediumERCAB_4](https://user-images.githubusercontent.com/76635320/141022160-dfb6230e-e5ae-44d7-8601-3155b7592d6c.JPG)
![StatsmediumERCAB_3](https://user-images.githubusercontent.com/76635320/141022163-6690eb9d-b2db-45af-8ea9-b42aa9132da2.JPG)
![StatsmediumERCAB2](https://user-images.githubusercontent.com/76635320/141022171-5ec266b9-80fb-4104-bb48-e87c46bc5589.JPG)
![StatsmediumERCAB_1](https://user-images.githubusercontent.com/76635320/141022173-4b9539bb-afb0-4d0c-8805-cdad0ca54b31.JPG)

**Comment by Gunit2481** [comment]
Added !
