### ISSUE TITLE
A1 - Article to explain "how to manage your auction as well as possible on astar" (French) (November 2021)

### ISSUE THREAD

**Issue by GreatTeacherKez** [PlasmNetwork/growth-program#1648]
I try to explain in an article differences between astar portal, parallel.fi and DEX to have the best opportunities with rewards bonus.
link: https://medium.com/@kekezousmk/g%C3%A9rer-au-mieux-son-ench%C3%A8re-sur-astar-7b5e7662eb0e
By an happy Astaronaut.

Twitter: @greatteacherkez
shiden adress: WAyw2mtxkRk9vjmwBdGivFduhVmGEeCH8JAXVmREzku92a8

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by GreatTeacherKez** [comment]
Hi maarten, same screen for the second article explaining how to manage
astar auction.
stats:views 236 reads 133 read ratio 56% fan 5
thanks!

**Comment by Gunit2481** [comment]
Added !
