### ISSUE TITLE
A3 - Created a tutorial about Shiden Network's dApp Staking. [video] 

### ISSUE THREAD

**Issue by KryptosChain** [PlasmNetwork/growth-program#1649]
Shiden Tutorial (dApp Staking): https://www.youtube.com/watch?v=IXjXcSkRu_k&t
Twitter: @KryptosChain
Telegram: @KryptosChain
Shiden Address: YAozdoSG5a2uNTze1ZocQtdM1ZxixLJ7Fcwj8cmAEKeyJCD

#crowdloan #shiden #shidennetwork

**Comment by fiexer** [comment]
Added!
