### ISSUE TITLE
A1 - Wrote an intro article about Astar/Shiden Network

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#165]
Due to the influx of new members after SDN got listed, I decided to write and intro article about Astar/Shiden Network. I thought this could be useful for the new members.

https://mamora-toga.medium.com/new-to-astar-shiden-network-heres-what-you-have-to-know-77dc7fb74035

Stats:
![image](https://user-images.githubusercontent.com/37278708/132939237-c0be1e1c-a8ca-4c41-b0f5-27ee5990b8b5.png)

![image](https://user-images.githubusercontent.com/37278708/132939254-90e11a02-c070-437c-8909-70a87e957384.png)

![image](https://user-images.githubusercontent.com/37278708/132939266-18ebba86-58b0-4f5f-bec3-c2e25cc592e5.png)

**Comment by fiexer** [comment]
Total points: 22
