### ISSUE TITLE
A3 - Created a tutorial about converting SDN to Metamask and vice versa. [video] 

### ISSUE THREAD

**Issue by KryptosChain** [PlasmNetwork/growth-program#1650]
Shiden Tutorial (SDN conversion to Metamask): https://www.youtube.com/watch?v=uDjfb_EkXiM&t
Twitter: @KryptosChain
Telegram: @KryptosChain
Shiden Address: YAozdoSG5a2uNTze1ZocQtdM1ZxixLJ7Fcwj8cmAEKeyJCD

#crowdloan #shiden #shidennetwork

**Comment by fiexer** [comment]
This one will be added to November.

**Comment by fiexer** [comment]
Added!
