### ISSUE TITLE
A1 - Created an introductory article in my media.

### ISSUE THREAD

**Issue by yudai-ogata** [PlasmNetwork/growth-program#1651]
I have written an article about my own introduction to Astar.

Release Date : October 20
URL : https://note.com/you425/n/n75adf627374e
View : 2412
Like : 76

Tweet
URL : https://twitter.com/you425you/status/1450760912550252550
Impression : 43739
Engagement : 1492
Like : 205
Retweet : 50

**Comment by fiexer** [comment]
Added!
