### ISSUE TITLE
A1 - Translate ASTR crowdloan event part 3 into Thai

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1652]
https://panupongpnp.medium.com/last-call-for-starting-astar-crowdloan-event-%E0%B8%95%E0%B8%AD%E0%B8%99-3-d2bfcfcf5e74

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pnpdude** [comment]
![image](https://user-images.githubusercontent.com/90048622/142160032-3dc9b4f9-ae9e-45f4-a409-7c2695f79950.png)

**Comment by Gunit2481** [comment]
Added !
