### ISSUE TITLE
A1 - Create Thai Article about How to Participating in Astar Crowdloan

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1653]
I share 4 available options of how to participating in Astar Crowdloan-> polkadot.js , Fearless, Exchange, Partner

https://panupongpnp.medium.com/%E0%B8%A3%E0%B8%A7%E0%B8%A1%E0%B8%A7%E0%B8%B4%E0%B8%98%E0%B8%B5%E0%B8%A3%E0%B9%88%E0%B8%A7%E0%B8%A1-astar-crowdloan-94c7f65329e

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pnpdude** [comment]
![image](https://user-images.githubusercontent.com/90048622/142160111-73f9afbb-64dc-4497-b056-b72cbc9183af.png)

**Comment by Gunit2481** [comment]
Added !
