### ISSUE TITLE
A8 - Errors in the Docs and YouTube channel 

### ISSUE THREAD

**Issue by igorporoshin** [PlasmNetwork/growth-program#1654]
During my work on Astarhub.io I have found many errors in the Docs and Astar YouTube channel.

Here is a full list.

[errors.docx](https://github.com/PlasmNetwork/growth-program/files/7475301/errors.docx)

Telegram: @igporoshin
Shiden address: aXueqwkrgUTVufyocGeBPm6NeSYp5k1ooPPJAGq3Ts7FtgF

**Comment by fiexer** [comment]
Added!
