### ISSUE TITLE
C2 - Grow Shiden reddit community

### ISSUE THREAD

**Issue by stakepile** [PlasmNetwork/growth-program#1655]
Discord: stakepile#7999
Shiden address: WGxS9u98ZDmwFdX6tVYGr2fL4NEK2BVYsvcNokgJ8p78rVX

I continue to grow the Shiden Reddit group. Membership in the community has grown from 163 in September to 297 by the end of October. The community can be found here: https://www.reddit.com/r/ShidenNetwork/

The following are stats for October
Pageview: **12345** views
Unique sessions: **1352** unique user sessions

![image](https://user-images.githubusercontent.com/90024770/140587481-c291e206-40bb-43d4-8968-d283b380a558.png)
![image](https://user-images.githubusercontent.com/90024770/140587519-b733ead0-0422-4312-986b-3cf8165edd48.png)
![image](https://user-images.githubusercontent.com/90024770/140587591-395e2e42-8dcc-4d01-8a15-efec38febfe5.png)

**Comment by fiexer** [comment]
Added!
