### ISSUE TITLE
C2 - Set Up and Launced AstarNetwork on Reddit Community

### ISSUE THREAD

**Issue by kindwhitney** [PlasmNetwork/growth-program#1656]
Discord: kindwhitney
Shiden address: WzhJcGVYtpuHAd5Xw29qHbqxFmrUaswyTYk5u6wSwyUCqcg

I set up and launched a new reddit community dedicated to Astar to help share Astar information with Reddit users. Members of this community are able to ask questions and receive answers on a range of topics regarding staking, wallets, and others. Membership in this community has grown from 1 to 46 in the last two months. Membership in the community continues to grow as new members discover the subreddit. The community can be found here: 
https://www.reddit.com/r/AstarNetwork/

Pageview stats for September: 186 pageviews 
Pageview stats for October: 486 pageviews

Total page views for September & October = 672

<img width="489" alt="Screen Shot 2021-11-05 at 4 36 51 PM" src="https://user-images.githubusercontent.com/91760552/140589556-632919d7-e50a-40ac-a0b4-cd4b13e8094a.png">

<img width="832" alt="Screen Shot 2021-11-05 at 4 37 40 PM" src="https://user-images.githubusercontent.com/91760552/140589567-356c4be3-24d5-457c-95fe-69ee6c3f3054.png">

**Comment by fiexer** [comment]
https://github.com/stakepile
This is you ☝️

**Comment by kindwhitney** [comment]
Hi 

> https://github.com/stakepile
> This is you ☝️

Hi Fiexer,

That is not me but I do work with stake pile!

**Comment by fiexer** [comment]
Added!
