### ISSUE TITLE
A3 - Article about ways to participate in Astar Crowdloan in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1657]
I wrote an article about ways to participate in Astar Crowdloan in persian
https://telegra.ph/نحوه-شرکت-در-crowdloan-پروژه-Astar-Network-11-06

Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
Sdn address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
This will be added to November

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
