### ISSUE TITLE
C2 - Community Management Vietnamese

### ISSUE THREAD

**Issue by thanhmycm** [PlasmNetwork/growth-program#1658]
My name is Le Thanh My 
Telegram Username : @ThanhCayMoney
Vietnamese community manager
Telegram group :
https://t.me/PlasmOfficialVietnam
Telegram Channel : https://t.me/astarshidenvietnam

My address Shiden :
ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
