### ISSUE TITLE
A1- Astar part 3 turkısh translate 

### ISSUE THREAD

**Issue by iamcem007** [PlasmNetwork/growth-program#1659]
https://medium.com/@cempehlivan7/astar-crowdloan-etkinli%C4%9Fi-3-b%C3%B6l%C3%BCm-885e3e217a85

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
