### ISSUE TITLE
C2 - Community Management Thai

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1661]
My name is Panupong Chunid
Telegram Username : @pnp_404
Thai community manager
Telegram group : https://t.me/Astarthai

My Shiden address:
Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
