### ISSUE TITLE
C2 - Community Management - October

### ISSUE THREAD

**Issue by Kahonnohak** [PlasmNetwork/growth-program#1662]
Hello,

These are where I was active promoting/helping people for Astar/Shiden Network in October.

Discord : Astar & Shiden Network , Open Japanese community Polkadot channel(https://discord.gg/afSXzb6k), Closed Japanese community Polkadot channel
Telegram : Astar Network Japan

Telegram : @kaoriatcrypto
Discord : @kaori#1166
Twitter : https://twitter.com/kaori_ruku
Wallet : 5FjFGo8DUWB5PFzg7TVMJ2hQEtYCQLE9UtEUyd88Ee4DEzQa

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
