### ISSUE TITLE
C2- COMMUNITY MANAGEMENT AFRICA

### ISSUE THREAD

**Issue by cryptosats** [PlasmNetwork/growth-program#1663]
@cryptopedia
Chris Malize

I Managed the community in collaboration with Brian. The community has relatively around 31 members as at the time I joined, but we grew it to 68 members presently through online meetup and other engagement. Answered questions asked by community members, shared official information from the team and also gave my feedback.

OCTOBER 2021
https://t.me/AstarAfrica

I also contributed in the management of the Astar official telegram group, I answered questions asked by community members to the best of my knowledge during my shift (Monday -Sunday, 3 hours each day). I was able to identify an impostor who used Hoon Kim personal information which I reported  as well. I also deleted several spam messages in the group.

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month! Also added you as a mod for the official channel.

Thanks for your hard work.
