### ISSUE TITLE
C-2 Astar & Shiden Community in Spanish-October

### ISSUE THREAD

**Issue by ercab2408** [PlasmNetwork/growth-program#1664]
During the month of October, the group increased by 7% and we started the voice channel on Thursdays to listen to the community.
Attached are the images of growth and interaction with the community.
![statisticsOctober4](https://user-images.githubusercontent.com/76635320/140650562-0a735980-4a53-478f-8082-a5abb777a288.jpg)
![statisticsOctober3](https://user-images.githubusercontent.com/76635320/140650565-22bd6702-0e19-4bd7-bf00-cc6b94426987.jpg)
![statisticsOctober2](https://user-images.githubusercontent.com/76635320/140650566-750ae7b3-fd62-447d-b64e-1d675233ef4f.jpg)
![statistics_October1](https://user-images.githubusercontent.com/76635320/140650567-8e81b4f1-bf5b-47ea-b57a-2741f5ef5471.jpg)

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
