### ISSUE TITLE
A5 - Live Event Meet ASTAR and SHIDEN NETWORK- Spanish Community

### ISSUE THREAD

**Issue by ercab2408** [PlasmNetwork/growth-program#1665]
Hi Community

Recently we organize an event on the Mercader_Venecia channel in Twich.
We explain ShidenNetwork and everything about DaapStaking plus the main topic about Polkadot's Parachain and how to support ASTAR NETWORK at this event
We had an audience of 171 users and the video have until today 11-07-2021 with more than 1,600 views. Our community is Spanish increased in 24 hours after event in more than 10%.

Also we give out 100SDN of prizes to the community (50-30-20)

Link event: https://www.twitch.tv/videos/1196936650
![flyerfi](https://user-images.githubusercontent.com/76635320/140651254-b13433d7-e5a7-49f2-ac38-989431cc4654.jpg)
![StatisticEvent1](https://user-images.githubusercontent.com/76635320/140651259-e6908ea6-065e-464f-880c-9cb60e7a225c.jpg)
![StatisticEvent3](https://user-images.githubusercontent.com/76635320/140651267-3227648f-0ae4-4311-b526-8bef6ec8a1e0.jpg)
![GifusersEvent](https://user-images.githubusercontent.com/76635320/140651276-91c90964-0d76-492e-a7c7-5db3b77f4a12.jpg)

**Comment by fiexer** [comment]
Great work!
Will be added to next months rewards.

**Comment by togamamora** [comment]
Points have been added to Nov.

**Comment by togamamora** [comment]
Points have been added.
