### ISSUE TITLE
C2 - Community Management - Korean October

### ISSUE THREAD

**Issue by RHEEUNION** [PlasmNetwork/growth-program#1667]
Hi, this is Rhee, Korean Ambassador.
I've almost achieved all of my goals from the previous CM report: https://github.com/PlasmNetwork/growth-program/issues/89
(29 members left till 500 members in total)

Telegram Username : @rheeunion
Telegram group : https://t.me/astar_kr
Parachain Korea : https://t.me/parachain_korea
Shiden Address : bUUve83HysJPyXGfbAPcGdV2YujGPVMqZgM61fio4WTrQSs

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
