### ISSUE TITLE
A4 - Korean Telegram AMA with Hoon (via Parachain Korea Channel)

### ISSUE THREAD

**Issue by RHEEUNION** [PlasmNetwork/growth-program#1668]
![image](https://user-images.githubusercontent.com/39883171/140670754-7f870e9d-c1a8-4ede-814e-c4ec2c1a40b5.png)

**Date:** October 16th, 2021.
**Host:** @RHEEUNION 
**Special Guest:** @hoonsubin 
**Running Time:** 30 Minutes
**Number of Viewed:** 744 Members
**Record:** https://t.me/astar_kr/15729
**Contents:** Overview of Astar, features (dApps Staking, Layer 2), Shiden Metamask Tutorial, Community Program, Ecosystem News, Q&A

**Comment by fiexer** [comment]
Added!
