### ISSUE TITLE
C2 - Astar Africa Community  telegram group 

### ISSUE THREAD

**Issue by ahimbisibwebrian** [PlasmNetwork/growth-program#1669]
We have managed to grow the Astar Africa community telegram group with my other colleague Chris Malize
Looking forward to inviting more of the relevant community members from Africa by the end of Q4
https://t.me/AstarAfrica

**Comment by fiexer** [comment]
Added!
You are on the sheet now, so I'll check it automatically every month!

Thanks for your hard work.
