### ISSUE TITLE
C2 - Shiden MEME Campaign - Week 1 Results

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#167]
We have closed the first week of the MEME Campaign for Shiden Network

Received 90 entries for the Competition. 

We decided to open Round2 of the MEME Campaign to entertain more users and give extra rewards for Round2 of the Campaign. 

We received great feedback for the Campaign

Here are is the Medium Summary Article about the first week of the campaign:
https://stakenode.medium.com/shiden-network-multi-chain-dapp-hub-on-kusama-listing-week-meme-campaign-update-c58542999f37

Here are the stats from the First Round:
https://medium.com/me/stats/post/a968bba8f591

Let's build a Strong and Organic Shiden & Astar Ecosystem!

**Comment by fiexer** [comment]
Great work @jimmy-tudeski 
We need more of this :-)
