### ISSUE TITLE
A1 - Create Thai Article

### ISSUE THREAD

**Issue by boomblb** [PlasmNetwork/growth-program#1670]
🟨 Mon 8 Nov'21

✔️ Telegram : @boomblb124 

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Shiden Address : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Topic : How to Create Polkadot Wallet

https://medium.com/@thanapatchamnam/%E0%B8%82%E0%B8%B1%E0%B9%89%E0%B8%99%E0%B8%95%E0%B8%AD%E0%B8%99%E0%B9%83%E0%B8%99%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9B%E0%B9%8B%E0%B8%B2-polkadot-7a3becd023cf

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by boomblb** [comment]
Dear Maarten,

Acknowledge with Thanks

Best Regards,
Boom

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing (Screenshot)
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by boomblb** [comment]
Dear Gunit,

Sorry for late reply.
Stats as below details

![image](https://user-images.githubusercontent.com/84943107/144515131-0aa8cb78-245f-490f-91c4-9ec7dbbbf61a.png)

![image](https://user-images.githubusercontent.com/84943107/144515173-a024c7e7-e113-4a43-91a6-fe021e867f88.png)

Thank you so much

Best Regards,
Boom

**Comment by Gunit2481** [comment]
Added !
