### ISSUE TITLE
A6 - Instructions to send SDN from Polkadot.js to Metamask and Withdraw SDN from Metamask to Polkadot.js

### ISSUE THREAD

**Issue by thanhmycm** [PlasmNetwork/growth-program#1672]
I have created a video tutorial for users on how to use polkatools and some necessary notes.

Username Telegram : @ThanhCayMoney

Address Shiden : ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

My Video : https://youtu.be/CuDpYUbYcrg

**Comment by fiexer** [comment]
Great work on this!

**Comment by Gunit2481** [comment]
Added !
