### ISSUE TITLE
A1 - Medium article on Shiden/Astar 

### ISSUE THREAD

**Issue by FlynewsToDay** [PlasmNetwork/growth-program#1673]
The purpose of the article is to highlight the philosophy of Astar/Shiden. how value construction is managed; agility, collaborative intelligence and design thinking. 
I tried to highlight the human behind the project and to do this I had the chance to interview bLd.
**https://flynewstoday.medium.com/astar-shiden-qui-a-t-il-dans-mon-smart-contract-f446fb10c85f**

This article was shared on my tweeter, the Telegram group Astar français, discord Polkadot francophonie, Discord Astar #french
https://discord.com/channels/856183900199321650/863390200292704266/906900787039436801
https://discord.com/channels/644182966574252073/830483658779263008/906903895392010280
https://twitter.com/FlyNewsToday/status/1457344446585085955?s=20
https://t.me/PlasmNetwork_FR/4867

X8WrVs3LFwdTEwi7R2KtqjJxDe3u8usYA1SYMnZeNpp2ohg

thank you :)

**Comment by fiexer** [comment]
Very cool!

Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by FlynewsToDay** [comment]
hello, this is the stats
![twitter](https://user-images.githubusercontent.com/92853343/143222380-595212df-823a-46f3-be89-7798f06c271a.png)
![medium1](https://user-images.githubusercontent.com/92853343/143222393-57118655-01b3-4468-9717-0f80538adce7.png)
![medium2](https://user-images.githubusercontent.com/92853343/143222406-7ab4b5c9-e1c0-48e0-8538-0d1902b7810e.png)
![medium3](https://user-images.githubusercontent.com/92853343/143222408-0fbe437e-826f-4872-8830-642fcf0673d6.png)

thank you

**Comment by Gunit2481** [comment]
Added !
