### ISSUE TITLE
A1 - FAQ ASTAR Crowdloan Eng/Thai version

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1674]
since I'm bilingual speaking English and Thai, I created 2 FAQ articled for both language 

English version
https://panupongpnp.medium.com/faq-troubleshoot-astar-crowdloan-1f23e3a8c9a8

Thai version
https://panupongpnp.medium.com/%E0%B8%84%E0%B8%B3%E0%B8%96%E0%B8%B2%E0%B8%A1%E0%B8%9E%E0%B8%9A%E0%B8%9A%E0%B9%88%E0%B8%AD%E0%B8%A2-astar-crowdloan-2c6a7914e82e

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by fiexer** [comment]
Great work!

Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by pnpdude** [comment]
English version
![image](https://user-images.githubusercontent.com/90048622/142770208-385ba112-3792-40a1-a6a4-7934cf19a33f.png)

Thai version
![image](https://user-images.githubusercontent.com/90048622/142770224-b7c2bafd-21dd-4e66-af36-044b870b4d8e.png)

**Comment by Gunit2481** [comment]
Added !
