### ISSUE TITLE
A8 - Astar parachain Auctions

### ISSUE THREAD

**Issue by kevinmrn** [PlasmNetwork/growth-program#1676]
Created an opening and a closing animation for the Astar Parachain auctions, which were posted in TG.

Screenshots:
https://ibb.co/tccZ0sv
https://ibb.co/cYZbKyB

Discord handle: kapot#1421
Telegram handle: @kapot_again
SDN wallet: YaWdJZhLjkQGd5QHUkXh8JEXMxx6bgVpb8wVwDYRcWZVhEV

**Comment by fiexer** [comment]
Did you created an issue for your intro animation?

**Comment by kevinmrn** [comment]
Hey mate, yeah. bLd told me to log it in here. Did I do it wrong?


________________________________

**Comment by fiexer** [comment]
Question was if you already made contribution about your previous work, like the logo animation?

**Comment by kevinmrn** [comment]
Nope, cheers will do that now!

**Comment by Gunit2481** [comment]
Added !
