### ISSUE TITLE
A8 - Astar Logo Animation #1676

### ISSUE THREAD

**Issue by kevinmrn** [PlasmNetwork/growth-program#1679]
Created a logo animation for Astar as used in below Medium Article:
https://medium.com/astar-network/last-call-for-starting-astar-crowdloan-event-part-iii-ee8a18346f5b

Discord handle: kapot#1421
Telegram handle: @kapot_again
SDN wallet: YaWdJZhLjkQGd5QHUkXh8JEXMxx6bgVpb8wVwDYRcWZVhEV

**Comment by kevinmrn** [comment]
Hey, why was this one closed?  

Cheers

**Comment by togamamora** [comment]
> Hey, why was this one closed?
> 
> Cheers

Bacause the points have been added to the spreadsheet.

**Comment by kevinmrn** [comment]
Cool all good!
