### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by chillyvee** [PlasmNetwork/growth-program#1681]
Discord ID: chillyvee#1883                                                                                    
Node name on Telemetry: FluffyCrypto                                                                          
Subscan link to my account: https://shibuya.subscan.io/account/Wthoy5SinJPGmxTHYvxASA5MqDNzFURCEG9Phq4MgKMgzTk
Email address for contact: blockhead@chillvalidation.com                   

Shiden Address for Rewards: Wthoy5SinJPGmxTHYvxASA5MqDNzFURCEG9Phq4MgKMgzTk

Node upgraded to 2.7.1 -> 3.1.4 and more CPU and RAM than ever!

Collator running since the beginning of Shibuya
https://github.com/PlasmNetwork/growth-program/issues/169 - FLUFFYCRYPTO

This is my new github account for node operations.  If you need further authentication, let me know.

**Comment by fiexer** [comment]
Added to the sheet!
