### ISSUE TITLE
A3 - Pixel art animation by @Egartez (NoCritics)

### ISSUE THREAD

**Issue by NoCritics** [PlasmNetwork/growth-program#1682]
This is my little pixel art project i did for Astar. Message me on @egartez (tg) if you need the source files or wish to collaborate in any way.

The DOT auctions are live and its time to engage!

https://user-images.githubusercontent.com/79338604/141518090-7f2873c5-1e64-484e-b3ad-939a99e24c30.mp4

**Comment by togamamora** [comment]
Please leave your Shiden address on this post.

**Comment by fiexer** [comment]
Please add address of Shiden in this post or we cant add rewards from the program.
Not done at the end of the month result in no rewards.

**Comment by NoCritics** [comment]
> Please add address of Shiden in this post or we cant add rewards from the program. Not done at the end of the month result in no rewards.

Sorry, I missed the first messages - currently in the process of finishing my Bachelor thesis.
Here is the address - WBYY1SMbBArTc17LYveWBM4tuaHWZwnEY6gLNCexJgvprNa
