### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by DHK-krm** [PlasmNetwork/growth-program#1686]
Discord - DHK_krm#2422
Node name - DHK-NODE
subscan account - https://shibuya.subscan.io/account/afJrBhTEn5YGgdM9sNEri9PxsAmYLJvS6x1ui6HvnFUgQG6
email - dhkshop@gmail.com
Shiden adress afJrBhTEn5YGgdM9sNEri9PxsAmYLJvS6x1ui6HvnFUgQG6

The node is kept up to date, updates as soon as possible. In work 15 days

**Comment by fiexer** [comment]
32k SBY sent!
Please onboard your collator.

**Comment by Myfixgold** [comment]
Discord - Myfix#3305
Node name - MyfixGold
subscan account - https://shibuya.subscan.io/account/WcyzrNv7vvTHswmSth6mQVyRybo4Kb9F5gK9masKyKMQdwC
email - mifixgold@gmail.com
Shiden adress WcyzrNv7vvTHswmSth6mQVyRybo4Kb9F5gK9masKyKMQdwC

The node is kept up to date, updates as soon as possible. In work 10 days

**Comment by fiexer** [comment]
Added!
