### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by igoodvvin** [PlasmNetwork/growth-program#1687]
1. Your Discord ID - igoodvvin#9101
2. Node name on Telemetry - DOMINODES
3. Subsca link of your account - https://shibuya.subscan.io/account/XZnocgu3rfRKfMmJV593SQgp4UTgkVSbHtET3U2kwZbYufw
4. Email address to send important updates for your node - igoodvvin@gmail.com
5. Shiden wallet address to payout your rewards - XZnocgu3rfRKfMmJV593SQgp4UTgkVSbHtET3U2kwZbYufw

Hi Maarten, I have been participating in the testnet Shibuya since the beginning of September. In the google table, I did not find myself in the list of Shibuya testnet collators.

**Comment by fiexer** [comment]
Thanks
Will add you to the list. The reason for not being added is that there was no application found to apply for the fund application to earn rewards.
