### ISSUE TITLE
C2 - Community Management - Italian Community 🇮🇹

### ISSUE THREAD

**Issue by Poggi-Luca** [PlasmNetwork/growth-program#1688]
Hello Maarten,

this is November submission for Italian community management on Astar Italian Community Telegram group (https://t.me/AstarShidenNetworkItalia).

Thank you 😊

My Telegram Username: @LucaPoggi
Discord Username: GaGa7#6937
Shiden Address: Yr7ZxQJX6Ho4qBFywoA5hvFSxpBtLQv5T4LnLpzy3MffKJa

**Comment by togamamora** [comment]
Please share your TG statistics.

**Comment by fiexer** [comment]
Official ambassadors dont need to do monthly reports anymore!
