### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by ercab2408** [PlasmNetwork/growth-program#1690]
Hi guys
This is my application request to run a Shibuya Collator. These are my data
 Discord ID: Ercab24#2125
Node name on Telemetry: AMRCSTKE
SubscanLink: https://shibuya.subscan.io/account/aTcyU5BRJgrfvwpYiseDoWHW9BjWRwbAnKuo6Mhc9muJ9VV
Email address: ecaballero@amrcorp.net or noderc0411@protonmail.com
Shiden wallet payout reward: ae2asEfpmWsL378ywSnN7skvyARFV4qFyLM35Agwt1MBa5w

Regards
ERCAB24

**Comment by fiexer** [comment]
Please let me know when node is up & running for 14 days.
Thanks @ercab2408

**Comment by ercab2408** [comment]
Hi Maarten
I am writing to request the evaluation again. The node is up for 16 days and updated 4 days ago to version 3.1.1 also I am attached some basic information about Grafana.
![Grafana_status](https://user-images.githubusercontent.com/76635320/143982822-cd253e73-546d-47c1-9c3d-8774d7ef584b.JPG)
![Node_upbefore](https://user-images.githubusercontent.com/76635320/143982847-0af4cc62-49e0-496f-8e84-e6c83fc60ecf.JPG)

**Comment by fiexer** [comment]
Also upgrade node to 3.1.4

**Comment by ercab2408** [comment]
Great
