### ISSUE TITLE
A1 - translate Astar crowdloan event part III

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1691]
I have translated Astar Crowdloan event part III
https://link.medium.com/raav7AkT9kb

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by togamamora** [comment]
Please share your statistics after 14 days from the date you published the artcile.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۲۴-۰۷۳۶۴۷_Medium.jpg](https://user-images.githubusercontent.com/91786817/143173319-ca7838e4-44c0-446c-860f-55e988268926.jpg)

**Comment by Gunit2481** [comment]
Added !
