### ISSUE TITLE
A1 : Translation Thai Article

### ISSUE THREAD

**Issue by boomblb** [PlasmNetwork/growth-program#1692]
🟨 Sun 14 Nov'21

✔️ Telegram : @boomblb124

✔️ Twitter : @TrafalgarL9

✔️ Discord : boomblb#9447

✔️ Shiden Address : WTAn3LgY4pszDPXJZFpPMDqgBRpDjxaQsTQ82MdhjoNYtek

🟩 Topic : Astar Crowdloan Event Summary

https://medium.com/@thanapatchamnam/astar-crowdloan-event-summary-ea965716e8b1

**Comment by togamamora** [comment]
Please share your statistics after 14 days of publication.

**Comment by boomblb** [comment]
Here is the statistics.

https://medium.com/me/stats/post/ea965716e8b1 https://medium.com/me/stats/post/ea965716e8b1

Thanks in advance.

**Comment by togamamora** [comment]
I can't the stats from the links. You need to share the screenshots here.

**Comment by boomblb** [comment]
Dear Toga,

The stats is in attached file

Thank you so much

Best Regards,
Boom

**Comment by togamamora** [comment]
I can't view the stats from the links that you shared. Only you can see that. So please screenshot the stats like this.

![Screenshot_20211126_212624](https://user-images.githubusercontent.com/37278708/143588359-16df97d3-b4c5-4670-b685-5f1c3ed8074a.jpg)

**Comment by boomblb** [comment]
Dear Toga,


Maybe my attached screenshot didn't go to you

Sorry for that. May I resent to you again as following details?

![image](https://user-images.githubusercontent.com/84943107/143618161-633b3c4f-1c97-4c2e-9bf2-86aea34cde7d.png)


![image](https://user-images.githubusercontent.com/84943107/143618173-21b9b5cc-eb18-4cc9-a0e5-efb0f1bdcd29.png)


Thank you so much

Best Regards,
Boom

**Comment by Gunit2481** [comment]
Added !

**Comment by boomblb** [comment]
Thank a lot 🙏
