### ISSUE TITLE
A1 - Translate Astar crowdloan event part IV

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1693]
I have translated Astar Crowdloan event part IV
https://link.medium.com/edICtgrT9kb

Discord handle: pooya#0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.  
These stats are needed to finalize your points.

How to see stats:  
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۲۵-۱۲۱۰۱۲_Medium.jpg](https://user-images.githubusercontent.com/91786817/143407870-c588bc96-4123-48e0-bff3-997ec968f02e.jpg)

**Comment by Gunit2481** [comment]
Added !
