### ISSUE TITLE
A1 - Translate Astar crowdloan event part IV

### ISSUE THREAD

**Issue by jdrevon** [PlasmNetwork/growth-program#1694]
Hello,

I have translated in French, the Astar Crowdloan event part IV:

https://medium.com/@juliendrevon/astar-crowdloan-event-partie-iv-1ed420aa30b8

Discord handle: Franck_Kerigman#3517 
Telegram handle: https://t.me/julien_drevon 
SDN address: aU4QjPSbkQqLQc87MVohk6iGWDyCLBbTZGNgaGcDg6x2Qws

Kind Regards

Julien

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.  
These stats are needed to finalize your points.

How to see stats:  
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by jdrevon** [comment]
@Gunit2481 Sure, here they are ;)

![image](https://user-images.githubusercontent.com/49060498/143658282-231c03c5-a7d8-4094-93fa-d4342ec86520.png)

**Comment by Gunit2481** [comment]
Added !
