### ISSUE TITLE
A1 - Translation of "Astar Crowdloan - Part I" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1695]
Hi,

I have translated "Astar Crowdloan - Part I" into Ukrainian - https://medium.com/@astarshidenua/%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%BE%D0%B0%D0%BD-astar-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-i-7d49a36e5007

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
#1696 
#1697
#1698
#1699 
#1700
#1701
#1702
#1703

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing of each translations
These stats are needed to finalize your points.
 ##
How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by ArtemCrypto6083** [comment]
#1703 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143584016-4e8cbc52-8732-4c47-941b-3bf9f782c47e.png">
#1701 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143584291-63c2a927-18a5-4a18-9ad3-57eb51e7735f.png">
#1702 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143584407-127bcb6f-3dac-48cb-a618-f393bedc7ba1.png">
#1699 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143584562-a470b01a-68f2-4635-a395-f1e0c953f49c.png">
#1698 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143584886-f2777d1f-5199-48c9-8a75-23d1d9646fc2.png">
#1697 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143585070-446f74b0-3d19-4146-be48-08ca2f4d8a09.png">
#1696 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143585160-54ed8b5e-1b1c-40a7-920d-b288e6608cfe.png">
#1695
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143585378-24280cc2-cbd5-48ed-a9b9-2b7da3145155.png">
#1700 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143585573-51a6e56d-dc13-4ac2-b467-15e485939fee.png">

**Comment by Gunit2481** [comment]
Added !
