### ISSUE TITLE
A1 - Translation of "dApp Staking is Live on Shiden Network #Build2Earn" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1696]
Hi,

I have translated "dApp Staking is Live on Shiden Network #Build2Earn" - https://medium.com/@astarshidenua/%D0%B2%D1%96%D0%B4%D0%B1%D1%83%D0%B2%D1%81%D1%8F-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-dapp-staking-%D0%B2-shiden-network-build2earn-6fa0010f39c9

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
