### ISSUE TITLE
A1 - Translation of "Shiden partners with AnySwap" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1697]
Hi,

I have translated "Shiden partners with AnySwap" into Ukrainian - https://medium.com/@astarshidenua/%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%BE%D0%BA-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%81%D1%82%D0%B2%D0%B0-shiden-%D0%B7-anyswap-4552abeab778

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
