### ISSUE TITLE
A1 - Translation of "Astar Community Program" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1698]
Hi,

I have translated "Astar Community Program" into Ukrainian - https://medium.com/@astarshidenua/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B0-%D1%81%D0%BF%D1%96%D0%BB%D1%8C%D0%BD%D0%BE%D1%82%D0%B8-astar-b530d6122129

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
