### ISSUE TITLE
A1 - Translation of "Announcing Astar v2.0: Multi-chain dApp Hub" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1699]
Hi,

I have translated "Announcing Astar v2.0: Multi-chain dApp Hub" into Ukrainian - https://medium.com/@astarshidenua/%D0%B0%D0%BD%D0%BE%D0%BD%D1%81%D1%83%D1%94%D0%BC%D0%BE-astar-v2-0-%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D1%87%D0%B5%D0%B9%D0%BD-dapp-%D1%85%D0%B0%D0%B1-a01f83b1ec60

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
