### ISSUE TITLE
A1 - Translation of "Astar Crowdloan - Part I" into Russian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1700]
Hi,

I have translated "Astar Crowdloan - Part I" into Russian - https://medium.com/@astarshidenua/%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%BE%D0%B0%D0%BD-astar-%D1%87%D0%B0%D1%81%D1%82%D1%8C-i-2ca28dcb74c1

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
