### ISSUE TITLE
A1 - Translation of "Last Call for Starting Astar Crowdloan Event - Part III" into Ukrainian

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1703]
Hi,

I have translated "Last Call for Starting Astar Crowdloan Event - Part III" into Ukrainian - https://medium.com/@astarshidenua/%D1%84%D1%96%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9-%D0%BA%D1%80%D0%BE%D0%BA-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%BF%D0%BE%D1%87%D0%B0%D1%82%D0%BA%D0%BE%D0%BC-%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%BE%D0%B0%D0%BD%D1%83-astar-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-iii-d014aa67dbff

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by Gunit2481** [comment]
Added to #1695
