### ISSUE TITLE
A6 - Detailed Guide for Ukrainian Community on Astar Community Program

### ISSUE THREAD

**Issue by ArtemCrypto6083** [PlasmNetwork/growth-program#1704]
Hi,

I have written a detailed guide for Ukrainian Community on Astar Community Program - https://medium.com/@astarshidenua/%D0%B4%D0%B5%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%B9-%D1%82%D1%83%D1%82%D0%BE%D1%80%D1%96%D0%B0%D0%BB-%D0%B7-astar-community-program-18280cff270

It was promoted via Astar & Shiden Network | Ukraine Telegram channel (https://t.me/astar_shiden_ua) moderated by me, crypto chats and a private CIS crypto blog (link can be shared in PMs only. Will hook up with it if necessary)

SDN address: YkQ1QFNKZfordAVb1RBaMZgwJmxCRGeycZ5UJxRf4F4mPpj
ArtemCrypto#6083
@fuckingbillionaire - telegram

**Comment by togamamora** [comment]
Please share your statistics after 14 days of publication.

**Comment by ArtemCrypto6083** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/83471580/143586451-d459358a-7177-47cf-bee0-e2e62308d9b8.png">
