### ISSUE TITLE
A3 - Video about Astar

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1706]
Video link:( in twitter)
https://twitter.com/AstarPersian/status/1459933852680560645?t=6EXZ21pdLQV3XBrSDfuPWw&s=19

Discord handle: pooya #0847
Telegram handle: https://t.me/Persian_ambassador
SDN address: bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by togamamora** [comment]
This is Category A8. Creative Work - animated logo
