### ISSUE TITLE
 A1 - Translation article by Alexmed911

### ISSUE THREAD

**Issue by Alexmed911** [PlasmNetwork/growth-program#1707]
Discord: alexmed#5188
Shiden wallet: bURRxf37gBbwUvHmxKHGBdmjQ61JexocDfA3aXfDUw8SaNM

Translation Ukrainian

1. https://takeshikovaks.medium.com/astar-crowdloan-event-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-iv-5ac27e3e37fc

2. https://takeshikovaks.medium.com/astar-crowdloan-event-%D0%BF%D1%80%D0%BE%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%8C-%D1%83-%D0%BF%D1%80%D1%8F%D0%BC%D0%BE%D0%BC%D1%83-%D0%B5%D1%84%D1%96%D1%80%D1%96-1bb8de344795

3. https://takeshikovaks.medium.com/astar-crowdloan-event-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-ii-efe9d4c819d8

4. https://takeshikovaks.medium.com/astar-crowdloan-event-%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0-i-a5d6706f5152

5. https://takeshikovaks.medium.com/shiden-%D1%81%D0%BF%D1%96%D0%B2%D0%BF%D1%80%D0%B0%D1%86%D1%8E%D1%94-%D0%B7-anyswap-bc1a9b66375a

6.  https://takeshikovaks.medium.com/%D1%81%D1%82%D1%80%D0%B5%D1%81-%D1%82%D0%B5%D1%81%D1%82-%D0%BD%D0%B0-%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D1%83-dapp-%D0%BD%D0%B0-shibuya-50cf00f473e6

7.  https://takeshikovaks.medium.com/%D0%BF%D0%BE%D0%B4%D1%96%D1%8F-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D1%83-evm-nft-a5690c59eb04

8.  https://takeshikovaks.medium.com/%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BF%D1%80%D0%B8%D1%94%D0%B4%D0%BD%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%BE-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8-astar-builders-%D1%96-%D0%BE%D1%82%D1%80%D0%B8%D0%BC%D1%83%D1%94-%D0%B3%D1%80%D0%B0%D0%BD%D1%82-f3f4a2922f93

9.  https://takeshikovaks.medium.com/bware-labs-%D0%BF%D1%80%D0%B8%D1%94%D0%B4%D0%BD%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%BE-%D0%BD%D0%B0%D1%88%D0%BE%D1%97-%D0%B5%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8-%D0%B2-%D1%8F%D0%BA%D0%BE%D1%81%D1%82%D1%96-%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B7-%D0%BD%D0%B0%D1%88%D0%B8%D1%85-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80%D1%96%D0%B2-%D0%BF%D0%BE-%D0%BE%D0%B1%D1%81%D0%BB%D1%83%D0%B3%D0%BE%D0%B2%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8E-6d86db08c58a

10.  https://takeshikovaks.medium.com/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-22-a697c36a73fa

11.  https://takeshikovaks.medium.com/staking-dapp-%D0%B2%D0%B6%D0%B5-%D0%B7%D0%B0%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%B0-%D0%B2-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96-shiden-2e1744d962b0

12.  https://takeshikovaks.medium.com/%D1%81%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%8F-growth-fund-%D0%B5%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8-astar-shiden-%D0%B2-%D1%80%D0%BE%D0%B7%D0%BC%D1%96%D1%80%D1%96-30-%D0%BC%D1%96%D0%BB%D1%8C%D0%B9%D0%BE%D0%BD%D1%96%D0%B2-%D0%B4%D0%BE%D0%BB%D0%B0%D1%80%D1%96%D0%B2-%D1%81%D1%88%D0%B0-d345761b192f

13.  https://takeshikovaks.medium.com/okex-%D1%96%D0%BD%D0%B2%D0%B5%D1%81%D1%82%D1%83%D1%94-%D0%B2-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%83-astar-c49a0def37e8

14.  https://takeshikovaks.medium.com/%D0%BE%D1%84%D1%96%D1%86%D1%96%D0%B9%D0%BD%D0%B8%D0%B9-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96-shiden-7e2b625f91bf

15. https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B0-astar-community-1f4d6a143261

16.  https://takeshikovaks.medium.com/%D0%BF%D0%B5%D1%80%D1%88%D0%B0-%D1%83%D1%81%D0%BF%D1%96%D1%88%D0%BD%D0%B0-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D1%96%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D1%96-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D1%8C-%D0%BF%D0%BE-%D0%BB%D0%B0%D0%BD%D1%86%D1%8E%D0%B6%D0%BA%D1%83-xcmp-%D1%83-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D1%96%D0%B9-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96-polkadot-6a50ccee68ad

17.  https://takeshikovaks.medium.com/%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D0%B0-astar-%D0%B7%D0%B0%D0%BA%D1%80%D0%B8%D0%B2%D0%B0%D1%94-%D1%80%D0%B0%D1%83%D0%BD%D0%B4-%D0%B2%D0%B0%D1%80%D1%82%D1%96%D1%81%D1%82%D1%8E-2-4-%D0%BC%D0%BB%D0%BD-%D0%B4%D0%BE%D0%BB%D0%B0%D1%80%D1%96%D0%B2-%D0%BD%D0%B0-%D1%87%D0%BE%D0%BB%D1%96-%D0%B7-binance-labs-f7ebbae3a2a5

18.  https://takeshikovaks.medium.com/%D1%81%D0%BF%D1%96%D0%B2%D0%BF%D1%80%D0%B0%D1%86%D1%8F-shiden-%D0%B7-covalent-499cc9480cee

19.  https://takeshikovaks.medium.com/nfty-labs-%D0%BF%D1%80%D0%B8%D1%94%D0%B4%D0%BD%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%BE-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%B8-builders-7d1921f0eb50

20.  https://takeshikovaks.medium.com/onfinality-%D1%96%D0%BD%D1%84%D1%80%D0%B0%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%BD%D0%B8%D0%B9-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80-astar-6d2dcc28b9c4

21.  https://takeshikovaks.medium.com/microsoft-japan-%D0%BE%D0%B3%D0%BE%D0%BB%D0%BE%D1%88%D1%83%D1%94-%D0%BF%D1%80%D0%BE-%D0%BF%D1%96%D0%B4%D1%82%D1%80%D0%B8%D0%BC%D0%BA%D1%83-%D1%83-%D1%81%D1%82%D0%B2%D0%BE%D1%80%D0%B5%D0%BD%D0%BD%D1%96-%D0%B5%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B8-astar-shiden-fe321691e5e

22.  https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D1%96-%D0%BF%D0%BE%D0%B2%D1%96%D0%B4%D0%BE%D0%BC%D0%BB%D0%B5%D0%BD%D1%8C-xcmp-%D0%B7-kylin-network-a7b7c949b32f

23.  https://takeshikovaks.medium.com/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-21-f53dc69254e7

24.  https://takeshikovaks.medium.com/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-20-9f053c9dfe34

25.  https://takeshikovaks.medium.com/%D0%B0%D0%BD%D0%BE%D0%BD%D1%81-astar-v2-0-astar-v2-0-multi-chain-dapp-hub-e4f8728c4f6d

26.  https://takeshikovaks.medium.com/astar-%D0%BE%D1%82%D1%80%D0%B8%D0%BC%D1%83%D1%94-%D0%B3%D1%80%D0%B0%D0%BD%D1%82-web3-%D0%BD%D0%B0-%D0%B2%D0%BF%D1%80%D0%BE%D0%B2%D0%B0%D0%B4%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F-zk-plonk-%D0%B2-polkadot-5f2466d50b9a

27.  https://takeshikovaks.medium.com/%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D0%B0-astar-%D0%BF%D1%80%D0%B8%D1%94%D0%B4%D0%BD%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F-%D0%B4%D0%BE-%D1%83%D0%B3%D0%BE%D0%B4%D0%B8-%D0%BF%D1%80%D0%BE-%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%BA%D0%BB%D0%B8%D0%BC%D0%B0%D1%82%D0%B5-crypto-climate-accord-15de0ae3d6c7

28.  https://takeshikovaks.medium.com/plasm-%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D1%8C-%D1%80%D0%B5%D0%B1%D1%80%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3-%D0%B2-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96-astar-fd1ce67cfd54

29. https://takeshikovaks.medium.com/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-19-9ac43fc8b673

30.  https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D1%94%D0%BC%D0%BE-x-%D0%B2%D1%96%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%83-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D1%83-%D0%B2-%D0%BC%D0%B5%D1%80%D0%B5%D0%B6%D1%96-shiden-78386d690e0

31.  https://takeshikovaks.medium.com/%D1%89%D0%BE%D1%82%D0%B8%D0%B6%D0%BD%D0%B5%D0%B2%D0%B5-%D0%BE%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F-18-6858663061f3

**Comment by Alexmed911** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/87994565/142939836-2a95418b-3516-4f73-8f20-b340960ce301.png)

**Comment by Alexmed911** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/87994565/142939883-67240e19-7596-4e6b-948f-c6482dd1d122.png)

**Comment by Alexmed911** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/87994565/142944847-d81386b3-a05d-4318-9020-d798049f22db.png)

**Comment by Alexmed911** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/87994565/142946172-e33ba700-dfab-4fb4-8c53-fcab1c0870cb.png)

**Comment by Alexmed911** [comment]
All articles have similar statistics on medium

**Comment by Gunit2481** [comment]
Added !
