### ISSUE TITLE
A8 - Overview about backers of Astar network 

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1708]
I wrote an article about backers of Astar network
This is part 1:  https://link.medium.com/qv86rSU4dlb

Discord handle: pooya #0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:  bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by togamamora** [comment]
Please share statistics after 14 days

**Comment by Gunit2481** [comment]
Added !
