### ISSUE TITLE
A1 Translation of "Vesting for Lockdrop participants for ETH" post

### ISSUE THREAD

**Issue by jdrevon** [PlasmNetwork/growth-program#1709]
Hello,

I have translated in French, the Astar Crowdloan event part IV:

https://medium.com/@juliendrevon/vesting-pour-les-participants-au-lockdrop-deth-ff257eac6aaa

Discord handle: Franck_Kerigman#3517
Telegram handle: https://t.me/julien_drevon
SDN address: aU4QjPSbkQqLQc87MVohk6iGWDyCLBbTZGNgaGcDg6x2Qws

Kind Regards

Julien

**Comment by jdrevon** [comment]
![image](https://user-images.githubusercontent.com/49060498/143658282-231c03c5-a7d8-4094-93fa-d4342ec86520.png)

**Comment by Gunit2481** [comment]
Added !
