### ISSUE TITLE
A3 - Youtube video explaining Astar/Shiden Network in Brazilian Portuguese

### ISSUE THREAD

**Issue by timbalabuch** [PlasmNetwork/growth-program#171]
Youtube video: https://www.youtube.com/watch?v=dTPl1kWyQrU

Twitter post: https://twitter.com/TimBalabuch/status/1436753506417975302
Telegram: timbalabuch
Discord: Tim Balabuch | timz.Ξth#5220

Shiden Address: Ww1qygT1rQXiPdnjP5ALKmWTfrnKReU2aoGyoWf55fzwGfJ

**Comment by fiexer** [comment]
Great work on creating this video!

Total points: 18
