### ISSUE TITLE
A6 - Tutorial : Thai How to transfer SDN from polkadot.js to MetaMask Article

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#1714]
https://panupongpnp.medium.com/%E0%B8%A3%E0%B8%A7%E0%B8%9A%E0%B8%88%E0%B8%9A-polkadot-js-metamask-a776ac12be10

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by Gunit2481** [comment]
I move this contribution from A1 to A6 as a tutorial.

Can you provide stats after 2 weeks of publishing.

Thank you PNP !

**Comment by pnpdude** [comment]
sure!

![image](https://user-images.githubusercontent.com/90048622/144274280-72cf9f83-aac8-456e-a203-966b82b8770e.png)

**Comment by Gunit2481** [comment]
Added !
