### ISSUE TITLE
C1 - Attracted Signally.Finance to Build2Earn on Shiden

### ISSUE THREAD

**Issue by theojamiller** [PlasmNetwork/growth-program#1717]
Brought in a unique project with 3+ months already been building and a solid minimum viable product to our ecosystem. 

I think the relationship will be symbiotic and help both projects grow over time. 

Shiden Address;
a7697urR1bFwkdu4979x9nP549ZbFUUrUDzu6JZuVEQAZVF

**Comment by fiexer** [comment]
Added

**Comment by theojamiller** [comment]
![image](https://user-images.githubusercontent.com/78944028/144954871-8cbc2675-c1e6-4eba-b286-50b26189f00d.png)
![image](https://user-images.githubusercontent.com/78944028/144954913-f0af4081-0cba-4675-a92e-b2bb905549be.png)
![image](https://user-images.githubusercontent.com/78944028/144954968-eb10c27c-99e0-43b5-8fad-be01f30d64ae.png)

I'm confused about the rewards structure, I thought the minimum was 20 points?
