### ISSUE TITLE
A5 - Social Engagement

### ISSUE THREAD

**Issue by theojamiller** [PlasmNetwork/growth-program#1718]
I have been unable to get statistics on my monthly contributions to the official channel from the admins however for the past few months I've regularly answered questions, deleted/banned spammers and moderated the discussion. 

I've also been doing moderation in the Astar Unnoficial (1.1k members), now Shiden Unnoficial (24) channel as well as the Astar Discord. 

I regularly contribute to Polkadot Unnoficial(4.4k) as the Moonbeam/Moonriver fanbase is strong there and I think it's important to have our project mentioned in a positive light regularly in that space. 

I post regularly in both Into the Cryptoverse (52k) and Into the Cryptocosm(12k) discussing Polkadot and Astar/Shiden 

I helped found two groups for discussing the auctions with the aim of discussing the auctions in more depth with sophisticated investors. 
https://t.me/Polkadot_auctions 80 members
https://t.me/KusamaAuctions 141 members

I've added COMBOT to start gathering stats in the groups where I can and asked admins for some stats to support this post.

**Comment by togamamora** [comment]
Can you please share your group Combot stats?

**Comment by fiexer** [comment]
This is part of your Ambassador work.
Month November will be added the multiplier again.

**Comment by theojamiller** [comment]
> o

I have not claimed A5 for moderation since I started as an ambassador as I have not had access to the statistics to do so.
