### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by CertHum-Jim** [PlasmNetwork/growth-program#1719]
Discord ID: Jim | CertHum#8065
Telemetry: CertHum-MaxStake-C01-A
Subscan: https://shibuya.subscan.io/account/Z7w1y5k4qsWBaq22rpfm7RJdtAgDQ94NG7fMtXU55zAKCME
Email: operations@certhum.com
Shiden Account: XnuKFFicAynN2Ka7Gu2ThFhcMUrxpmLCKfhzDVwWZ5S9iqS

Thanks!

**Comment by fiexer** [comment]
Added you to the list and send 32k SBY
Please onboard and update your collator to the latest version.
