### ISSUE TITLE
A1 – Translated article into Polish by kartaviy#9786

### ISSUE THREAD

**Issue by donatello345** [PlasmNetwork/growth-program#172]
Original - https://medium.com/astar-network/shiden-network-official-launch-38fe68d74812
in Polish - https://soulmatesblog.medium.com/oficjalna-premiera-shiden-network-b36cfee9f7b4
Discord - kartaviy#9786
Wallet - Z4EufabY6bZSfqM1ZsaEAeo3Z5srTuRtvCuoSzgeyxw1Ncu

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing. These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by fiexer** [comment]
Stats please
