### ISSUE TITLE
A1 - Translation article by Alexmed911

### ISSUE THREAD

**Issue by Alexmed911** [PlasmNetwork/growth-program#1720]
Discord: alexmed#5188
Shiden wallet: bURRxf37gBbwUvHmxKHGBdmjQ61JexocDfA3aXfDUw8SaNM

Translation Poland

1. https://takeshikovaks.medium.com/przedstawiamy-x-maszyn%C4%99-wirtualn%C4%85-w-sieci-shiden-71e8e3e29808
2. https://takeshikovaks.medium.com/cotygodniowa-aktualizacja-18-fe73b9a41946
3.  https://takeshikovaks.medium.com/plasm-przeprowadza-rebranding-w-sieci-astar-91a29976c33c
4. https://takeshikovaks.medium.com/cotygodniowa-aktualizacja-19-df7ce6ae771e
5. https://takeshikovaks.medium.com/plasm-przeprowadza-rebranding-w-sieci-astar-91a29976c33c
6. https://takeshikovaks.medium.com/tr%C3%B3j%C5%9Bciennych-astar-do%C5%82%C4%85cza-do-crypto-climate-accord-cd5319ce7c5f
7. https://takeshikovaks.medium.com/astar-otrzymuje-grant-web3-na-wdro%C5%BCenie-zk-plonk-w-polkadot-ea9d1efc53a
8. https://takeshikovaks.medium.com/zapowied%C5%BA-astar-v2-0-astar-v2-0-multi-chain-dapp-hub-74feca4ec87d
9. https://takeshikovaks.medium.com/cotygodniowa-aktualizacja-20-7f1a1be6c985
10. https://takeshikovaks.medium.com/cotygodniowa-aktualizacja-21-f474b7390259
11. https://takeshikovaks.medium.com/protok%C3%B3%C5%82-przesy%C5%82ania-wiadomo%C5%9Bci-xcmp-z-kylin-network-348179cb0681
12. https://takeshikovaks.medium.com/microsoft-japan-og%C5%82asza-o-wsparciu-w-tworzeniu-ekosystemu-astar-shiden-9f0ef5de4805
13. https://takeshikovaks.medium.com/nfty-labs-do%C5%82%C4%85cza-do-programu-builders-eff51c1bf0f7
14. https://takeshikovaks.medium.com/onfinality-partner-infrastrukturalny-astar-2937a9a26429
15. https://takeshikovaks.medium.com/wsp%C3%B3%C5%82praca-shiden-h-covalent-ac3051d78f5c
16. https://takeshikovaks.medium.com/pierwsza-udana-transakcja-przesy%C5%82ania-wiadomo%C5%9Bci-na-%C5%82a%C5%84cuchu-xcmp-w-testowej-sieci-polkadot-44e84f53db66
17. https://takeshikovaks.medium.com/sie%C4%87-astar-zamyka-runda-o-warto%C5%9Bci-2-4-mln-dolar%C3%B3w-na-czele-z-binance-labs-561a8e002747
18. https://takeshikovaks.medium.com/program-astar-community-a219e3a9cf64
19. https://takeshikovaks.medium.com/oficjalny-start-sieci-shiden-a11307ed7cb
20. https://takeshikovaks.medium.com/tworzenie-growth-fund-ekosystemu-astar-shiden-w-wysoko%C5%9Bci-30-milion%C3%B3w-dolar%C3%B3w-b2bd156ffec6
21. https://takeshikovaks.medium.com/okex-inwestuje-w-sie%C4%87-astar-5fc282c84690
22. https://takeshikovaks.medium.com/staking-dapp-ju%C5%BC-dzia%C5%82a-w-sieci-shiden-33560658d208
23. https://takeshikovaks.medium.com/cotygodniowa-aktualizacja-22-26b9411fdc1c
24. https://takeshikovaks.medium.com/bware-labs-do%C5%82%C4%85cza-do-naszego-ekosystemu-jako-jednego-z-naszych-partner%C3%B3w-serwisowych-przysz%C5%82ych-77ffd2291fcd
25. https://takeshikovaks.medium.com/bware-labs-do%C5%82%C4%85cza-do-naszego-ekosystemu-jako-jednego-z-naszych-partner%C3%B3w-serwisowych-przysz%C5%82ych-77ffd2291fcd
26. https://takeshikovaks.medium.com/standardowy-protok%C3%B3%C5%82-do%C5%82%C4%85cza-si%C4%99-do-programu-astar-builders-i-otrzymuje-grant-7bf8d35cdd75
27. https://takeshikovaks.medium.com/inauguracja-evm-nft-2e0d78f908f2
28. https://takeshikovaks.medium.com/stres-test-zak%C5%82ad-dapp-na-shibuya-39a40147a61
29. https://takeshikovaks.medium.com/shiden-wsp%C3%B3%C5%82pracuje-z-anyswap-c4b6f0cd4a51
30. https://takeshikovaks.medium.com/astar-crowdloan-event-cz%C4%99%C5%9B%C4%87-i-52a674238748
31. https://takeshikovaks.medium.com/astar-crowdloan-event-cz%C4%99%C5%9B%C4%87-ii-61449faa8b77
32. https://takeshikovaks.medium.com/astar-crowdloan-event-cz%C4%99%C5%9B%C4%87-iv-a616c20be697
33. https://takeshikovaks.medium.com/astar-crowdloan-event-odbywa-si%C4%99-na-%C5%BCywo-d50d89ce7464

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Alexmed911** [comment]
> Please share your stats after 2 weeks of publishing. These stats are needed to finalize your points.
> 
> How to see stats: https://help.medium.com/hc/en-us/articles/215108608-Your-stats
![Снимок экрана от 2021-11-27 18-03-44](https://user-images.githubusercontent.com/87994565/143688531-36af7eca-2e7d-4dcf-b26e-4f5160af0879.png)

**Comment by Alexmed911** [comment]
> Please share your stats after 2 weeks of publishing. These stats are needed to finalize your points.
> 
> How to see stats:
![Снимок экрана от 2021-11-27 18-22-35](https://user-images.githubusercontent.com/87994565/143689065-1c35ea39-0e78-4001-8bd7-c9de3c12b768.png)
 https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Alexmed911** [comment]
![Снимок экрана от 2021-11-28 14-21-18](https://user-images.githubusercontent.com/87994565/143767529-ac4111e6-1956-4ee1-8713-ff297dee6f88.png)

**Comment by Alexmed911** [comment]
All articles have + - similar statistics

**Comment by Gunit2481** [comment]
Added !
