### ISSUE TITLE
A8 - Astar tokenomics in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#1722]
I made an article about ASTR tokenomics in persian
https://link.medium.com/CAUUOXTMolb

Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address: bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by Gunit2481** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by Gunit2481** [comment]
Added !
