### ISSUE TITLE
A1 - Writing an article about how to participate in Astar's Crowdloan

### ISSUE THREAD

**Issue by yudai-ogata** [PlasmNetwork/growth-program#1723]
I created an article for Japanese on how to join Astar's Cloud Loan.

Release Date : November 6
URL : https://note.com/you425/n/n5b2d386ca7dd
View : 2752
Like : 19

Tweet
URL : https://twitter.com/you425you/status/1456674400665681923?s=20
Impression : 12743
Engagement : 549
Like : 98
Retweet : 24
Comment：22

**Comment by Gunit2481** [comment]
Thank you for your great work !
Added.
