### ISSUE TITLE
A3 - Created a video on how to Stake SDN coin

### ISSUE THREAD

**Issue by snars2018** [PlasmNetwork/growth-program#1725]
I have created a step by step video tutorial on how to Stake SDN coin at Astar Dashboard. Here's the link below.

https://www.youtube.com/watch?v=iFnNJ08Vio0

https://twitter.com/snars11
SDN wallet address: 
Xg1oajKXxYDMQh6RPSWTX3ScAmdcAA41gVpHmJw5TuhmhFJ

**Comment by Gunit2481** [comment]
Added !
