### ISSUE TITLE
Publication of information about the project on crypto forums.

### ISSUE THREAD

**Issue by donatello345** [PlasmNetwork/growth-program#1727]
I believe that a lot of people do not know about Astar Network yet and this needs to be corrected. Therefore, I will publish the news of the project on cryptocurrency forums.

Both in Russian and in English, and I will publish all new topics in this branch.

Cryptotalk | Russian Post about Astar Network - https://cryptotalk.org/topic/359128-astar-network/
Cryptotalk | English Post about Astar Network -

**Comment by vladylime** [comment]
written in simple language, easy to read. But there are few views and reactions from the community

**Comment by fiexer** [comment]
Will not be added to the rewards program.
