### ISSUE TITLE
A1 – Translated article into Polish by kartaviy#9786 | 2

### ISSUE THREAD

**Issue by donatello345** [PlasmNetwork/growth-program#173]
Original - https://medium.com/astar-network/astar-community-program-ee30b34f50f9
In Polish - https://soulmatesblog.medium.com/program-społeczności-astar-e1960debd0ed
Wallet - Z4EufabY6bZSfqM1ZsaEAeo3Z5srTuRtvCuoSzgeyxw1Ncu

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing. These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by fiexer** [comment]
Total points: 13
