### ISSUE TITLE
A8 - Partnerships template

### ISSUE THREAD

**Issue by kevinmrn** [PlasmNetwork/growth-program#1730]
Created an animated template in After Effects for Astar & Shiden to announce Partnerships and Collaborations, can be used animated as well as for still images.

https://ibb.co/NSHkFC3

Discord handle: kapot#1421
Telegram handle: @kapot_again
SDN wallet: YaWdJZhLjkQGd5QHUkXh8JEXMxx6bgVpb8wVwDYRcWZVhEV

**Comment by fiexer** [comment]
Added
