### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by 2TheMooon** [PlasmNetwork/growth-program#1731]
1.Discord ID - 2TheMoon ッ#3371
2.Node name - 2TheMoon
3.Subscan link - https://shibuya.subscan.io/account/YJHHwWzMMFyrvXGxnTQhu6oGkH2aRDCB71Fk7WquZpoW963
4.Email address - kononenkostas@gmail.com

**Comment by fiexer** [comment]
Added you the list + send you the 32k SBY.
Please onboard your collator to the active set. I also used the same address you shared here on Shibuya as Shiden payout address.

**Comment by 2TheMooon** [comment]
> Added you the list + send you the 32k SBY. Please onboard your collator to the active set. I also used the same address you shared here on Shibuya as Shiden payout address.

Done. Maybe you can check if everething is ok
