### ISSUE TITLE
A1 - Wrote an Thai article about Astar/Shiden Network

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#174]
Hi, I wrote an Thai article about Astar/Shiden. 

In first paragraph, I start with what's different between Shiden network, canary network and Astar, the mainnet, by comparing to Polkadot and Kusama.

In the next paragraph, I briefly inform the reader about Shiden/Astar.

The third one, what makes Astar/Shiden unique.

The last one is about Roadmap and Astar/Shiden does not have plan to ICO, only Crowdloan currently

Medium:
https://panupongpnp.medium.com/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-astar-shiden-178573346b7c

Blockdit:
https://www.blockdit.com/posts/613dbc6824255a0c6f841dcb

I will share stats from Medium and Blockdit in next 2 weeks
Thanks,

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Great work!
Please share your stats after 2 weeks of publishing. 
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pnpdude** [comment]
> Great work!
> Please share your stats after 2 weeks of publishing.
> These stats are needed to finalize your points.
> 
> How to see stats:
> https://help.medium.com/hc/en-us/articles/215108608-Your-stats

Here:

![messageImage_1632667551445](https://user-images.githubusercontent.com/90048622/134812664-af17141a-177f-4702-a17d-8222aea348e7.jpg)

![messageImage_1632667634617](https://user-images.githubusercontent.com/90048622/134812690-69908cec-4cfb-4ffb-83b4-e7b18d5a1e79.jpg)

**Comment by fiexer** [comment]
Total points: 13
