### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by Prufful** [PlasmNetwork/growth-program#1741]
Discord ID: prufful#6879
Node name on Telemetry: NataDark
Subscan: https://shibuya.subscan.io/account/5Gj3NzesZqKe5k3fzSQ7dsPEM19LWFXeXMMH9XM24xdY6Kcj
Email: prufful@gmail.com
Shiden Account: 5Gj3NzesZqKe5k3fzSQ7dsPEM19LWFXeXMMH9XM24xdY6Kcj

**Comment by fiexer** [comment]
I used this address: abdpHcxM4xkJa5WUjrEfXYWS3rTUUEPYYrRPEYswKdVgKo9
Added you to the list.
