### ISSUE TITLE
【A1】Two Articles on how to join Astar's Crowdloan from Binance

### ISSUE THREAD

**Issue by megan097** [PlasmNetwork/growth-program#1747]
- Two Articles on how to join Astar's Crowdloan from Binance in Japanese
- The first article is about the Polkadot ecosystem/auctions and Astar's relationship . The second article is about how to vote on Astar from Binance.
Due to the large amount of text, I have split the article into two parts, but both are related to how to participate in Astar's Cloud Loan.

Publish Date: 3th November/4th November
URL: 
[First article ](https://www.yamato0506.info/what-is-polkadot/) 
[Second Article](https://www.yamato0506.info/how-to-join-polkadot-auction/)
- created original images and own words
- also spread this article on these Twitter posts ([URL①](https://twitter.com/sunteam097/status/1455831369230086151) /[URL②](XX) )

Total number of accesses : 6062
Total number of Impression in Twitter : 80629 (20838 + 59791)
Total number of engagement in Twitter : 3562(1097 + 2465)
Total number of Like in Twitter : 293 (125 + 168)
Total number of Retweet in Twitter:  56 (25 + 31)

**Comment by Gunit2481** [comment]
Please, can you provide your SDN address here ?

**Comment by megan097** [comment]
Sorry, I forgot to include the address.
My address for Shiden in Kusama-chain is here.

XyUn6MFk8k2tkq91CSE5AXYpzvdMYbC2agjA7QVoFFPsc8h

**Comment by megan097** [comment]
Sorry, I forgot to include the address.
What network address should I share?
If I can use SDN Address in Kusama-chain, the address is here
XyUn6MFk8k2tkq91CSE5AXYpzvdMYbC2agjA7QVoFFPsc8h
