### ISSUE TITLE
C2 : Didn't recieve reward last month for TG support as formula multiplied by zero

### ISSUE THREAD

**Issue by theojamiller** [PlasmNetwork/growth-program#1752]
![image](https://user-images.githubusercontent.com/78944028/144047576-ecd89282-c5d5-4bd7-989b-c3e09d234d9d.png)

Theo :
a7697urR1bFwkdu4979x9nP549ZbFUUrUDzu6JZuVEQAZVF

**Comment by fiexer** [comment]
Calculation will be done by me this week.
