### ISSUE TITLE
A3 - Videos - November 2021 Contributions

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#1756]
A3 - Videos - November 2021 Contributions

Metioning Shiden and Astar in Video news releases and video
https://www.youtube.com/watch?v=3a7sbIpBx_I
https://www.youtube.com/watch?v=NrnJwqmQh0s
https://www.youtube.com/watch?v=OPdcsimVazA
https://www.youtube.com/watch?v=IETWDfnZQCU

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by Gunit2481** [comment]
Added !
