### ISSUE TITLE
A3- Video in Spanish/ what is Astar Network and how can we contribute on its parachain

### ISSUE THREAD

**Issue by Criptoygana** [PlasmNetwork/growth-program#1763]
Spanish video Contributión

https://youtu.be/4TNLdyMaO74

Telegram:  @Alecrypto1

Shiden Network account
YSGeo6TrEJs9jc3XJegSSciivGEMPD4TgmhWMbirR9gU7VN

**Comment by Gunit2481** [comment]
Added !
