### ISSUE TITLE
C2 - Community Management - November 2021

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#1765]
Hi, this is my community management participation for November 2021 and all the stats of the groups to follow the evolution of our ecosystem’s involvement and my participation in those groups.
Discord : Polkadot francophonie (507 members), CryptoMatrix (19k members). Astar & Shiden Network (17k members), Polkadot (Official) (19k members), Journal Du Coin (8k members), ChaosDAO (320 members)
With bld, we manage the twitter of @AstarNetworkFR (533 followers) and the telegram group of Astar Network France (444 members).

Telegram : @Gunit31
Discord : @g'ₑₓₚₑcₜ cₕₐₒₛ#3121
Twitter : @gunit3124 https://twitter.com/gunit3124
Wallet : Z5VAv3wwBuH15d1gAgjztz8CQPG6rwekFYxavgjhggJicsk

**Comment by fiexer** [comment]
Keep in mind that we only can reward Astar-related communities.
