### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by swasilenko** [PlasmNetwork/growth-program#1773]
1. Discord ID - 781260927819186246
2. Discord name - swasilenko#9850
3. Node name on Telemetry - swasilenko_shibuya
4. Subscan account link - https://shibuya.subscan.io/account/dDyu53YeoWEodemh313HCXGaTF2bjz3sAMHsBGSvaNJxbaNza
5. Email - vasilenko.sveta2308@gmail.com
6. Shiden wallet - WpDgyvW3db7p6WeTJJCYS883aHhd2pFV1sF13ZQN2ju8sDW

**Comment by fiexer** [comment]
Added you to the list and send the funds.
Please onboard your collator on Shibuya.

**Comment by swasilenko** [comment]
@fiexer thank you! done
