### ISSUE TITLE
A1 - Introduction to the collaboration between Shiden Network and PolkaEx and the value of dApp Staking

### ISSUE THREAD

**Issue by kuma56** [PlasmNetwork/growth-program#1776]
Since the announcement of the partnership between Shiden Network and PolkaEx, I wrote about how to use it and the benefits of dAppStaking.

It describes in detail how to move the SDN and provide liquidity on PolkaEx.

And, Astar/Shiden's dApp Staking is not a DEX for the purpose of APR rewards, but a project that has the power to connect developers together and has great potential for future development.
Since it was just before Astar's PLO started, we thought it would be a good idea to introduce more details about dApp Staking, the core of the project, to attract new fans.

https://twitter.com/kuma56_munage/status/1457281969348222976?s=21

At the same time, I'm sharing it with the Discord community.
https://discord.com/channels/644182966574252073/659677166241447956/906850388496515102

Opinions from people who have actually tried it based on my post.
https://twitter.com/yurari09949949/status/1457391044648005632?s=21
https://twitter.com/daidairow/status/1459936972667908096?s=21

![スクリーンショット 2021-12-08 10 25 40](https://user-images.githubusercontent.com/92496350/145132432-355a5fb8-66e0-4369-9b58-ca9a4ecb68f7.png)

**Comment by fiexer** [comment]
Program closed

**Comment by kuma56** [comment]
Hi Maarten.
I didn't know that the program is closed.
Can I just apply again next month for the same thing?

Also, if there is an official announcement about the renewal of the program, can you give me the URL so I can share it?
