### ISSUE TITLE
A1 - Wrote a blog about Astar/Shiden and Crowdloan 

### ISSUE THREAD

**Issue by Kahonnohak** [PlasmNetwork/growth-program#178]
I thought there aren't many info about what actually Astar/Shiden do in Japanese so I wrote a summary for new people to understand the project get ready for the coming Crowdloan before Dot token goes up.

Blog(jp):
https://note.com/kahon_design/n/ndbdce6bfe699

Address:
Zbqi66JFjpBc62WbkwUKgrgKwFKNYvtW5jdDLKz714Aq3nH

Discord:
kaori#1166

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by Kahonnohak** [comment]
Had 336views, I plan to update when Crowdloan details are finalised.

**Comment by fiexer** [comment]
Total points: 13
