### ISSUE TITLE
A3 - Video about Astar/Shiden Network

### ISSUE THREAD

**Issue by vladylime** [PlasmNetwork/growth-program#18]
News https://youtu.be/_4_lSFAo9WQ

Telegram: @vladylimes
Wallet: av6AYeM556wzE6ct1RKyCfTnZNXCfhWuxc93PVo7BWmXsMW

**Comment by fiexer** [comment]
Video is also mentioned here:
https://github.com/PlasmNetwork/growth-program/issues/24
