### ISSUE TITLE
A1 - Translate the article "Announced Astar v2.0" into Japanese.

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#180]
The article link is 
https://t.co/6OYAJvpyAa?amp=1

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by realtakahashi** [comment]
<img width="313" alt="20210921_AstarV2 0_evidence" src="https://user-images.githubusercontent.com/38233656/134110330-2b35190d-9df8-4f9f-ad51-3cab934dcd88.png">

**Comment by fiexer** [comment]
Total points: 3
