### ISSUE TITLE
A4 - Hosted a meetup about Aster in my local community

### ISSUE THREAD

**Issue by Mucunguzi256** [PlasmNetwork/growth-program#181]
I was able to introduce Astar Network to my local community in Uganda. I started off with introduction to Polkadot and Kusama, highlighting how these address the scalability, interoperability and cost efficiency challenges of the legacy blockchains. I then explained the cross chain nature of Astar and Dapp staking.

https://twitter.com/cute_dianie/status/1437884942655053827?s=20
https://drive.google.com/drive/u/0/folders/1TcwCpcX1RTEQLMyQ-Ju9Zl28I8vdbKCd

Address
Wr3L92YY3fcyCWAPFEKxbwLKHwo7mtf5ShNWJfn9xizzQjT

Discord 
Mucu256#3205

**Comment by fiexer** [comment]
Great!
Please grant me access to the Google drive.

Total points: 13

**Comment by Mucunguzi256** [comment]
Hi @fiexer I have made the link open. Sorry for any inconveniences caused.
