### ISSUE TITLE
A3 - Created an italian YT video about Astar/Shiden Network

### ISSUE THREAD

**Issue by Poggi-Luca** [PlasmNetwork/growth-program#184]
Hello Maarten, let me introduce @Irbisfulmineo ! (I submitted this submission for him, in order to show how to make a request for tip for his contribution.........next time he will make submission himself).
Francesco is an italian crypto YouTuber and he made the following YT video about Shiden Network:
https://youtu.be/ZvJdSbVls2g

I still watched it and it is completely correct (there aren't wrong concepts about the project).

This is Francesco's Shiden address: XyMkzEzGrccgnjdrs8ynb6Z7UiMoHsKv9xTBfDo6ozjahqq

**Comment by fiexer** [comment]
That's great!
I will leave his Github name open for now, would be great if he creates a video he would like to this contribution.

Points will be given 2 weeks after publication.
I will follow-up with his stats for this video. Thanks for promoting Astar

**Comment by fiexer** [comment]
Total points: 15

**Comment by Poggi-Luca** [comment]
> That's great! I will leave his Github name open for now, would be great if he creates a video he would like to this contribution.
> 
> Points will be given 2 weeks after publication. I will follow-up with his stats for this video. Thanks for promoting Astar

Hello Maarten, his Github username is @Irbisfulmineo

**Comment by fiexer** [comment]
Thanks
