### ISSUE TITLE
A3 - Video about Astar/Shiden Network

### ISSUE THREAD

**Issue by vladylime** [PlasmNetwork/growth-program#19]
News https://youtu.be/oinyeyGJfPI

Telegram: @vladylimes
Wallet: av6AYeM556wzE6ct1RKyCfTnZNXCfhWuxc93PVo7BWmXsMW

**Comment by fiexer** [comment]
Video is also mentioned here:
https://github.com/PlasmNetwork/growth-program/issues/24
