### ISSUE TITLE
C2 - Set up and launched Shiden Reddit community

### ISSUE THREAD

**Issue by stakepile** [PlasmNetwork/growth-program#190]
Discord: stakepile#7999
Shiden address: WGxS9u98ZDmwFdX6tVYGr2fL4NEK2BVYsvcNokgJ8p78rVX

I set up and launched a new Reddit community dedicated to Shiden to help Reddit users get info on Shiden and receive answers to many questions the community have on a range of topics including staking, wallets, and others. Membership in the community has grown from 1 to 163 in the last month and continue to grow strongly as new members discover the subreddit. The community can be found here: https://www.reddit.com/r/ShidenNetwork/ 

Pageview stats totals 4463 page views for the last 7 days and 9783 page views for September as of 9/17. With another 2 weeks remaining, I expect Sept page view stats to reach about 15K total at the end of Sept.

![image](https://user-images.githubusercontent.com/90024770/133879943-9dc6164d-be3a-468c-8d71-3e6be306bf3c.png)
![image](https://user-images.githubusercontent.com/90024770/133879959-0d919431-65ef-45d2-ac0e-9dc822ea92d3.png)

**Comment by fiexer** [comment]
That's great work!
Please let me know if you need more support on Reddit, we can also add some Ambassadors to help you with this.

Please share the stats at the end of the month so I can calculate the points for running the Reddit.
Appreciate the work! If you have questions please contact me.

**Comment by fiexer** [comment]
Please share the final stats for September.

**Comment by earnstash** [comment]
Here are the stats for September.
Pageviews: 12,891
Uniques: 1,039
Total members: 195
New member joins: 187
 
![image](https://user-images.githubusercontent.com/91220114/135701744-ed4b1fa7-a333-4dcb-aa35-e760afc0b38f.png)
![image](https://user-images.githubusercontent.com/91220114/135701726-bdbb7b31-9a6e-480c-a6cc-084628b653ca.png)

**Comment by stakepile** [comment]
Here are the stats for September.

Pageviews: 12891
Uniques: 1039
Total members: 195
New member joins: 187

![image](https://user-images.githubusercontent.com/90024770/135701863-601f5292-56ff-448e-b033-3e58c1c638c7.png)
![image](https://user-images.githubusercontent.com/90024770/135701884-ae537c41-5c53-4624-ae45-d65a25fd7bd1.png)
![image](https://user-images.githubusercontent.com/90024770/135701891-0a090ffa-a806-4a62-8833-a2b9994ba7f8.png)

**Comment by fiexer** [comment]
Very cool!
Can I ask you to also be very active in the Polkadot reddit community? The auctions are coming and we need to make a lot of noise there ;-). I will help you as well.
