### ISSUE TITLE
A1 - Translated 1 article into Thai and published in my medium and blockdit

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#196]
I published on 2 platforms which are Medium and Blockdit, the Thai reader platform.
I will share stats in 2 weeks, counted from the published date. (17/09/2021)

medium
https://panupongpnp.medium.com/astar-v2-0-multi-chain-dapp-hub-fc1efdb7746c

blockdit
https://www.blockdit.com/posts/614489e982530f38721f6e20

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pnpdude** [comment]
![messageImage_1633091783987](https://user-images.githubusercontent.com/90048622/135620493-743821c3-3e94-480d-904d-62d98b7c2e6e.jpg)

![messageImage_1633091781526](https://user-images.githubusercontent.com/90048622/135620522-799ae00b-392b-40d9-9f0e-fa5e118d50be.jpg)

**Comment by fiexer** [comment]
Total points: 2
