### ISSUE TITLE
A3 - Created and posted a video on YouTube about Astar Network in Russian

### ISSUE THREAD

**Issue by CrNeppos** [PlasmNetwork/growth-program#198]
Hi, I created a video about Astar Network in Russian. All in all, it's a friendly dive into the topic, a problem that Astar is willing to solve, what makes Astar unique and what partners / investors the project already attracted.

Youtube
https://www.youtube.com/watch?v=WGQFUeW3uuc&t=3s

Discord:
CrNepos#3430

Shiden wallet address: bE7zjnrfocRypYgfpzLiUgPm4m4PrgPKCrxnX4TG1BJXVvZ

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

If you got Twitter, please spread out this article to Russian communities.
Would be great to generate outreach to receive more points for your video.

**Comment by fiexer** [comment]
Total points: 2
