### ISSUE TITLE
A8 - Astar Animated logo for Discord

### ISSUE THREAD

**Issue by boodovskiy** [PlasmNetwork/growth-program#200]
![discord-icon-3](https://user-images.githubusercontent.com/15303736/133927124-7963ab7d-ad04-41bb-a66d-bea7e76bf361.gif)
![discord-icon-1](https://user-images.githubusercontent.com/15303736/133927126-9bcd0b54-0cee-411f-9f01-06dcf7a985dc.gif)
![discord-icon-2](https://user-images.githubusercontent.com/15303736/133927127-bab9e5b0-ab6e-4b0d-bc15-1783f88ca9f1.gif)

Discord: budovskiy#4624
Telegram: budovskiy87
Twitter: @boodovskiy

Shiden address: YFTJBnTYxmVES377a1iwnY8SHmNZHYaBhhRPxwBSQ7tKJHq

**Comment by fiexer** [comment]
Total points: 2
