### ISSUE TITLE
A7 - Shibuya explorer

### ISSUE THREAD

**Issue by Floxter** [PlasmNetwork/growth-program#201]
We Just setup a[ Nethereum](https://nethereum.com/) based block explorer for shibuya.
writed in C#/Blazzor /webassembly, served in apache.

https://shibuya-explorer.eusko.in

**Comment by Floxter** [comment]
Update: Added css, fixed some bugs.

Feedback and new feature ideas are welcome.

**Comment by fiexer** [comment]
Thanks a lot for this developer's work!
Like the design.

We will share this in our documentation together with other explorers.

Total points: 40
