### ISSUE TITLE
A8 - Challenge: create dApp staking infographic

### ISSUE THREAD

**Issue by fiexer** [PlasmNetwork/growth-program#203]
Hi everyone

During the community program, we will also add challenges for our community to engage in. Our second challenge is for those with graphical skills! **Create an infographic about dApp staking.**

What is dApp staking:
Instead of staking to validators, users can choose to nominate their Astar/Shiden tokens on the project. These users are also known as nominators. At every block, half of your block rewards are used for dApp staking. This reward is further divided into a 4:1 ratio between operators (developers) and nominators.

40% of block rewards is a huge incentive for dApp developers to build in the Astar ecosystem. In other blockchains like Ethereum, dApp developers need to apply for grant programs, issuance of tokens, fundraising etc. to earn some money. In the Astar ecosystem, as long as your dApp has been nominated, you will receive some basic income. As your dApp grows in popularity, more members of the community will nominate you and this means that you will receive a greater percentage of the block reward!

We must also not forget the nominators. 10% reward is quite substantial and can serve as an alternative to staking to validators or lending on other DeFi platforms. 

## Rewards
**Total spots:** 3 winners
**Rewards:** top 3 will be rewarded after the community poll. 
* 1st place: 100 points
* 2nd place: 50 points
* 3rd place: 25 points

## How to participate
Create an infographic to explain dApp staking. Use the resources below to create the perfect infographic.
An infographic is a collection of imagery, charts, and minimal text that gives an easy-to-understand overview of a topic.

## Rules
* Use brand guidelines to fit our house style
* Submit your infographic to this topic
* Send your design (psd, ai) to maarten@stake.co.jp or share your Figma url.
* Challenge ends **Tuesday September 28th - 12PM UTC**

## Resources
* Astar [brand guidelines](https://github.com/PlasmNetwork/growth-program/blob/main/media-kit/AstarGuidelines.pdf)
* [What is dApp staking?](https://forum.astar.network/t/faq-what-is-dapps-staking/1247)
* [dApp staking infographic example](https://speakerdeck.com/astarnetwork/astar-network-slide-deck-september-2021?slide=8)
* [Community reward program](https://forum.astar.network/t/start-of-our-community-program/1367)

**Comment by donatello345** [comment]
Can I edit some of my works?

**Comment by fiexer** [comment]
> Can I edit some of my works?

Sure you can.

**Comment by crypto-pithecus** [comment]
Interesting!

**Comment by mxmvslv** [comment]
@fiexer where should i share my Figma URL? I created infographic

**Comment by fiexer** [comment]
> @fiexer where should i share my Figma URL? I created infographic

Yes please do it here.

**Comment by mxmvslv** [comment]
> > @fiexer where should i share my Figma URL? I created infographic
> 
> Yes please do it here.

Here is my work: https://www.figma.com/file/dsyk1RfKUStTL0TU6IzYcb/Astar-Network-DApp-Staking-Infographic?node-id=0%3A1

**Comment by boodovskiy** [comment]
@fiexer 
![astar-dapp-staking](https://user-images.githubusercontent.com/15303736/134783269-e5689d71-1143-48cf-bdce-8a849082c56e.jpg)

Hi Maarten! This is my work.

I will send PSD also on your email.

Best regards.

**Comment by fiexer** [comment]
> @fiexer
> ![astar-dapp-staking](https://user-images.githubusercontent.com/15303736/134783269-e5689d71-1143-48cf-bdce-8a849082c56e.jpg)
> 
> Hi Maarten! This is my work.
> 
> I will send PSD also on your email.
> 
> Best regards.

Looks great! Thanks a lot for  your contribution

**Comment by Kahonnohak** [comment]
Hi I'm submitting my challenge! I do understand that Staking isn't actually going through dApps but to make it super simple I'd go with this.
![dApps-staking](https://user-images.githubusercontent.com/77480847/134915854-eac81efa-fe1a-4775-8a8c-3bbed39c392f.jpg)
.

**Comment by fiexer** [comment]
Voting started!

https://forum.astar.network/t/community-challenge-create-an-infographic-results-poll/1541

**Comment by fiexer** [comment]
@mxmvslv what is your Shiden address?
Thanks!
