### ISSUE TITLE
A7 - Challenge: onboard collator on Shibuya #169

### ISSUE THREAD

**Issue by chainhostorg** [PlasmNetwork/growth-program#204]
I set up a collator running Shibuya testnet successfully for more than 7 days. This is 30 points.
https://github.com/PlasmNetwork/growth-program/issues/169

This is my first submission, please see my details:
Shiden wallet address: XhjeeePDpx2R8FA2voCdcZKJ4f9rEHNkfzZ72hFFrXvGocs
Discord handle: moon_reporter#2961

**Comment by fiexer** [comment]
No need to create a new issue.
I'll follow up in the original thread.
