### ISSUE TITLE
A3 - How to Import wallet on Polkadot extension and check Astar and Shiden Balance

### ISSUE THREAD

**Issue by snars2018** [PlasmNetwork/growth-program#205]
I have created a video on how to Import wallet on Polkadot extension and check balance on Astar and Shiden network.

https://youtu.be/7zm3eBZs5dc

discord username:
snars2020#1629

twitter: https://twitter.com/snars11

Astar/Shiden wallet: Xg1oajKXxYDMQh6RPSWTX3ScAmdcAA41gVpHmJw5TuhmhFJ

**Comment by fiexer** [comment]
Total points: 2

**Comment by snars2018** [comment]
Got it. Thanks a bunch Sir.
