### ISSUE TITLE
A2 - Meme About Shiden/Astar by kriptachina#6123

### ISSUE THREAD

**Issue by zhekakrip** [PlasmNetwork/growth-program#207]
https://twitter.com/zhekakrip/status/1440870170134679552?s=20
 In one funny picture, this is how dapps staking is supposed to work

**Comment by fiexer** [comment]
Total points: 1

**Comment by fiexer** [comment]
Please share your SDN address

**Comment by zhekakrip** [comment]
Hi! WV3m497uYnknvLq4qyJbvWX2bcBr71qdhyj9gc7cAGsS3BF


пт, 1 окт. 2021 г. в 18:38, Maarten ***@***.***>:

**Comment by zhekakrip** [comment]
hi! WV3m497uYnknvLq4qyJbvWX2bcBr71qdhyj9gc7cAGsS3BF
