### ISSUE TITLE
A2 - Creating interesting memes by Absorberch#0341

### ISSUE THREAD

**Issue by absorberch** [PlasmNetwork/growth-program#210]
First Meme - https://twitter.com/AndyHODL/status/1440958469180362767?s=20
Second Meme - https://twitter.com/AndyHODL/status/1440983649634160640?s=20

My Shiden address - Z1jASjGDgtikEn6Vr5hmR7dQYNxSfFZHgS9D96nDBs2aY8b
Node name - absnode
Discord - Absorberch#341
Twitter - @AndyHODL

**Comment by fiexer** [comment]
Total points: 2
