### ISSUE TITLE
A1 - Article on promoting builders program & community program in Turkey community

### ISSUE THREAD

**Issue by ismetygc** [PlasmNetwork/growth-program#212]
Created a medium article with two objectives:

Inviting two ongoing programs- builders program and community program in the Turkey community.
Sharing the articles within a few closed groups of the Turkey community - WhatsApp group, telegram group to expand the popularity

https://link.medium.com/rO45IY2rNjb https://twitter.com/ismetygc_/status/1441161845293867010?s=21
Telegram ID :@ismetygc
Sdn Wallet adress: YYTK5PmtrwKiZNFDfnaemJ4LCjakX8wbG7iDB4GALgLRBYa

**Comment by ismetygc** [comment]
> Created a medium article with two objectives:
> 
> Inviting two ongoing programs- builders program and community program in the Indian community.
> Sharing the articles within a few closed groups of the Indian community - WhatsApp group, telegram group to expand the popularity
> 
> https://twitter.com/ismetygc_/status/1441161845293867010?s=21

Telegram ID :@ismetygc
Sdn Wallet adress: YYTK5PmtrwKiZNFDfnaemJ4LCjakX8wbG7iDB4GALgLRBYa

**Comment by ismetygc** [comment]
> Created a medium article with two objectives:
> 
> Inviting two ongoing programs- builders program and community program in the Indian community.
> Sharing the articles within a few closed groups of the Indian community - WhatsApp group, telegram group to expand the popularity
> 
> https://link.medium.com/rO45IY2rNjb https://twitter.com/ismetygc_/status/1441161845293867010?s=21
> Telegram ID :@ismetygc
> Sdn Wallet adress: YYTK5PmtrwKiZNFDfnaemJ4LCjakX8wbG7iDB4GALgLRBYa

**Comment by ismetygc** [comment]
> Created a medium article with two objectives:
> 
> Inviting two ongoing programs- builders program and community program in the Turkey community.
> Sharing the articles within a few closed groups of the Turkey community - WhatsApp group, telegram group to expand the popularity
> 
> https://link.medium.com/rO45IY2rNjb https://twitter.com/ismetygc_/status/1441161845293867010?s=21
> Telegram ID :@ismetygc
> Sdn Wallet adress: YYTK5PmtrwKiZNFDfnaemJ4LCjakX8wbG7iDB4GALgLRBYa

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by ismetygc** [comment]
https://help.medium.com/hc/article_attachments/4403467279127/yourstats.png


1 Eki 2021 Cum, saat 13:49 tarihinde Maarten ***@***.***>
şunu yazdı:

**Comment by ismetygc** [comment]
1 Eki 2021 Cum, saat 13:54 tarihinde ismet yağcı ***@***.***>
şunu yazdı:

**Comment by ismetygc** [comment]
https://help.medium.com/hc/article_attachments/4403467279127/yourstats.png


1 Eki 2021 Cum, saat 13:56 tarihinde ismet yağcı ***@***.***>
şunu yazdı:

**Comment by fiexer** [comment]
Please share your stats before Tuesday November 9th.
