### ISSUE TITLE
A8 - Art work About Shiden/Astar by kriptachina#6123

### ISSUE THREAD

**Issue by zhekakrip** [PlasmNetwork/growth-program#215]
https://twitter.com/zhekakrip/status/1441237012606898187?s=20

**Comment by fiexer** [comment]
Like this tweet!
Total points: 8

**Comment by fiexer** [comment]
Do not forget to share your Shiden address

**Comment by zhekakrip** [comment]
thank you so much!!!
WV3m497uYnknvLq4qyJbvWX2bcBr71qdhyj9gc7cAGsS3BF

пт, 1 окт. 2021 г. в 18:58, Maarten ***@***.***>:
