### ISSUE TITLE
A8 - Challenge: create dApp staking infographic #203

### ISSUE THREAD

**Issue by Kahonnohak** [PlasmNetwork/growth-program#225]
Made my submission to the challenge and Email has been sent from Kahori.

**Comment by fiexer** [comment]
Please reply here:

**Comment by fiexer** [comment]
https://github.com/PlasmNetwork/growth-program/issues/203

**Comment by fiexer** [comment]
also add a screenshot of your contribution :-)

**Comment by Kahonnohak** [comment]
Hi I just received 4 emails from you but I’ll just add a screenshot which I think what you wanted to me to do? Anything that I missed could you please let me know.

Thanks,

Kahori

**Comment by fiexer** [comment]
Hi

Please add your contribution in this topic:
https://github.com/PlasmNetwork/growth-program/issues/203

It would be great for our community to see your work, so it would be great if you could add a screenshot in the post.

**Comment by Kahonnohak** [comment]
Got it 😃

Thanks,

Kahori
