### ISSUE TITLE
C2 - Russian Community Support and Development / Telegram Group / August 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#227]
C2 - Russian Community Support and Development / Telegram Group / August 2021
Russian TG group	900+ (+120)	support, Q&A, 																						
Discord: AlexPromoTeam#0488
Telegram: https://t.me/AlexPromoTeam
Shiden address: ZRRdA8GG5kdAvHa3o3mZqXAw2iHo7iyLRko8bWNCYCKVqTa

**Comment by fiexer** [comment]
This should be part of social engagement.
C2 is only for Astar ecosystem communities 🙏 

This is part of https://github.com/PlasmNetwork/growth-program/issues/232
