### ISSUE TITLE
C2 - Russian Community Support and Development / Telegram Group / September 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#228]
C2 - Russian Community Support and Development / Telegram Group / September 2021
Russian TG group	1100+ (+200)	support, Q&A, 																						
Discord: AlexPromoTeam#0488
Telegram: https://t.me/AlexPromoTeam
Shiden address: ZRRdA8GG5kdAvHa3o3mZqXAw2iHo7iyLRko8bWNCYCKVqTa

**Comment by fiexer** [comment]
https://github.com/PlasmNetwork/growth-program/issues/13
