### ISSUE TITLE
A5 - Promotion and mentionings in Ecosystem Telegram Groups / August -September 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#229]
A5 - Promotion in Telegram Groups / September 2021

Providing the info about the Astar/Shiden in this groups - I am admin there. Invitations to Shiden/Astar twitter/telegram/medium.

- https://t.me/PolkadotRu	2,5k	Providing info about the project 																							
- https://t.me/PromoTeamRus	2k	Providing info about the project 																							
- https://t.me/polkaprojectcom	20k	Providing info about the project 																							

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: ZRRdA8GG5kdAvHa3o3mZqXAw2iHo7iyLRko8bWNCYCKVqTa

**Comment by fiexer** [comment]
Points will be added to:
https://github.com/PlasmNetwork/growth-program/issues/231

August already calculated with:
https://github.com/PlasmNetwork/growth-program/issues/232
