### ISSUE TITLE
A5- Astar/Shiden social network activities and Russian community support

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#23]
Here is the contribution in social network activities section for March/May/June/July 2021.
I am Alex PromoTeam. I am  contribute for Astar/Plasm from the early days of the project , from the first Lockdrop times.  

Astar - Shiden х PromoTeam activity report March - May 2021 		
Plasm		
https://t.me/ParachainNews/159	1,5k+	mention
https://twitter.com/DotParachains/status/1376424625689796608?s=20	1k+	mention
https://t.me/ParachainNews/152	1,5k 	tg + retweet
https://t.me/ParachainNews/151	1,5k 	tg + retweet
https://t.me/ParachainNews/117	1,3k+	promo of comf tw + tg
https://t.me/PolkadotRu	2,2k	Providing info about the project 
Russian TG group	660+	support, Q&A, and so on
https://twitter.com/DotParachains/status/1366049080623968260?s=20				
		
Astar - Shiden х PromoTeam activity report June 2021 		
https://t.me/PolkadotRu	2,2k	Providing info about the project 
Russian TG group	850+	support, Q&A, and so on
https://t.me/ParachainNews/427	0,8k	
https://t.me/ParachainNews/395		
https://t.me/ParachainNews/387		
https://t.me/ParachainNews/379		
https://t.me/ParachainNews/343		
https://t.me/ParachainNews/338		
https://t.me/ParachainNews/325		
https://twitter.com/DotParachains/status/1410166027690942469?s=20		
https://twitter.com/PromoTeamPD/status/1409835009880563716?s=20		
https://twitter.com/AstarNetwork/status/1409831016584318977?s=20		retweet
https://twitter.com/WatanabeSota/status/1409833814373945346?s=20		retweet
and many other retweets		
https://twitter.com/HuobiGlobal/status/1406167366711615489?s=20		
https://twitter.com/DotParachains/status/1406152594041548804?s=20		
https://twitter.com/PromoTeamPD/status/1400361226815815687?s=20		
	
Astar - Shiden х PromoTeam activity report July 2021 		
https://t.me/PolkadotRu	2,2k	Providing info about the project 
Russian TG group	850+	support, Q&A, and so on
https://t.me/ParachainNews/524		
https://t.me/ParachainNews/521		
https://t.me/ParachainNews/520		
https://t.me/ParachainNews/510		 
https://t.me/ParachainNews/508		
https://t.me/ParachainNews/505		
https://t.me/ParachainNews/504		
https://t.me/ParachainNews/493		
https://t.me/ParachainNews/487		
https://t.me/ParachainNews/478		
https://t.me/ParachainNews/463

**Comment by fiexer** [comment]
Please share the PromoTeam Shiden address.
I will only list July in the spreadsheet.
