### ISSUE TITLE
A3 - 3 Videos about Shiden and Astar / September 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#230]
A3 - 3 Videos about Shiden and Astar / September 2021
Providing the info about the Astar/Shiden in this videos

https://www.youtube.com/watch?v=QqbDMx1fwck																									
https://www.youtube.com/watch?v=QkMUAuf15VE																									
https://www.youtube.com/watch?v=h4ba0T2vu1Q&t=3s																																												

Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: ZRRdA8GG5kdAvHa3o3mZqXAw2iHo7iyLRko8bWNCYCKVqTa

**Comment by fiexer** [comment]
Last video already rewarded here: https://github.com/PlasmNetwork/growth-program/issues/53

Total points: 11
