### ISSUE TITLE
A5 - Social engagement (twitter/telegram) / September 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#231]
A5 - Informational support in social networks (twitter/telegram) for Shiden and Astar  / September 2021
Providing the info about the Astar/Shiden , in telegram and twitter

Telegram
https://t.me/ParachainNews 2,6k
https://t.me/PolkadotParachains 0,7k

https://t.me/ParachainNews/788																									
https://t.me/ParachainNews/774																									
https://t.me/ParachainNews/771																									
https://t.me/ParachainNews/768																									
https://t.me/ParachainNews/761																									
https://t.me/ParachainNews/743																									
https://t.me/ParachainNews/734																									
https://t.me/ParachainNews/722																									
https://t.me/ParachainNews/687																																																
https://t.me/ParachainNews/670																									

Twitter support - retweets from  4 accounts 
https://twitter.com/DotParachains 20k 
https://twitter.com/PromoTeamPD 8,5k
https://twitter.com/Alex_PromoTeam
https://twitter.com/vladylimes
 																																																																							
Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: ZRRdA8GG5kdAvHa3o3mZqXAw2iHo7iyLRko8bWNCYCKVqTa

**Comment by fiexer** [comment]
Total points: 45
