### ISSUE TITLE
A5  - Social engagement (twitter/telegram)  / August 2021

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#232]
A5 - Informational support in social networks (twitter/telegram) for Shiden and Astar  / August 2021
Providing the info about the Astar/Shiden , in telegram and twitter

Telegram
https://t.me/ParachainNews 2,6k
https://t.me/PolkadotParachains 0,7k

https://t.me/ParachainNews/642																									
https://t.me/ParachainNews/618																									
https://t.me/ParachainNews/606																									
https://t.me/ParachainNews/603																									
https://t.me/ParachainNews/586																									
https://t.me/ParachainNews/583																									
https://t.me/ParachainNews/578																									
https://t.me/ParachainNews/569																									
https://t.me/ParachainNews/564																									
https://t.me/ParachainNews/541																								

Twitter support - retweets from  4 accounts 
https://twitter.com/DotParachains 20k 
https://twitter.com/PromoTeamPD 8,5k
https://twitter.com/Alex_PromoTeam
https://twitter.com/vladylimes
 																																																																							
Discord: AlexPromoTeam#488
Telegram: https://t.me/AlexPromoTeam
Shiden address: aCMzcvPoq54PR3VPndvv4143moRmYfiALp3EFf8bvphZi36

**Comment by fiexer** [comment]
Telegram already counted:
https://github.com/PlasmNetwork/growth-program/issues/68

Twitter stats:
Total rewards: 30

Already obtained points are extracted to the Twitter amount.
