### ISSUE TITLE
A5 - Social engagement (twitter/telegram) / September 2021

### ISSUE THREAD

**Issue by donatello345** [PlasmNetwork/growth-program#234]
![image](https://user-images.githubusercontent.com/82183467/135166724-b8183d31-7917-4fd4-a7d9-d04dfdc4e3f8.png)

In September, I practically did not develop this Twitter, in October I plan to increase the audience coverage to 500 people.

**Comment by fiexer** [comment]
Points added here:
https://github.com/PlasmNetwork/growth-program/issues/138
