### ISSUE TITLE
A4 - Hosted communty meetup in Kampala City

### ISSUE THREAD

**Issue by ahimbisibwebrian** [PlasmNetwork/growth-program#235]
We successfully hosted our first community meetup with a turn up of over 28 attendees 
These were invited to join all the Astar social media channels, we had topics on over on the Blockchain technology and polkadot blockchain, introduction to Astar Network/Shiden network, Unique features on the networks ,smartcontracts and dApps among others 
Telegram id;                      brayoahimbisibwe
discord                             brian778#4181
SDN address                    bfwxC8oTD4PVa9mb21W9uEVweUnkBSXrvxbM1Ci3RLczdd7
Link to Event photos       https://drive.google.com/drive/folders/1xIMa_7udTGQyNo6w4gThG0L7OyA39lId?usp=sharing
Group channel(Astar Africa telegram group)    https://t.me/AstarAfrica

**Comment by fiexer** [comment]
Community management for the Africa community will be added from October.

Total points: 13
