### ISSUE TITLE
A7 - Add custom networks to MetaMask with one click

### ISSUE THREAD

**Issue by roy1210** [PlasmNetwork/growth-program#237]
## Summary

I created an app that users can use to add custom networks (such as Shiden and Shibuya) to MetaMask with one click.

SDN address: YyaqqvoACtudUvrqBXp7RxyAHkccvtj5BuESchUWY8EvBMF
Telegram: @Roy_Shoe_Kure

### Links 

App URL: 
https://web3-gateway.pow.codes

Demo video:
https://www.loom.com/share/c332dd51639046bdb57ad926fb824ce0

Ref:
https://docs.astar.network/integration/network-details

**Comment by fiexer** [comment]
Total points: 25
