### ISSUE TITLE
A3 Videos and Mentionings of Astar/Shiden for 4 months 

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#24]
**Here is the  Videos and Mentionings of Astar/Shiden for March/May/June/July 2021:**
https://t.me/ParachainNews/121	6k+	video about the shiden - editing and promotion / views - 700, total contacts 5k+ (tg + tw)	
https://www.youtube.com/watch?v=Tv-xOsgPA7Y&ab_channel=PromoTeamChannel	800+	Hot Dot News video
https://www.crowdcast.io/e/---2-2	100+	mentioned in russian meetup
https://www.youtube.com/watch?v=UFiNXxh8Wm4	0,5к	mentioning
https://www.youtube.com/watch?v=RkmsZNC3ACU	0,7k	mentioning
https://www.youtube.com/watch?v=o1C-e2wfWE8	0.5к	special video
https://www.youtube.com/watch?v=0PDQGOvzJC0	0,8k	special video
Metioning in news releases		
https://www.youtube.com/watch?v=oinyeyGJfPI		
https://www.youtube.com/watch?v=_4_lSFAo9WQ	
https://twitter.com/huobiglobal/status/1409385824089559041?s=21	200K+	Huobi mentioned
https://twitter.com/HuobiGlobal/status/1406167366711615489?s=20	200K+	Huobi Mentioned

**Comment by fiexer** [comment]
Video is also mentioned here:
https://github.com/PlasmNetwork/growth-program/issues/18

**Comment by fiexer** [comment]
And here:
https://github.com/PlasmNetwork/growth-program/issues/19
https://github.com/PlasmNetwork/growth-program/issues/20
