### ISSUE TITLE
A5 - Social engagement.

### ISSUE THREAD

**Issue by igorporoshin** [PlasmNetwork/growth-program#242]
Twitter account has been created:
https://twitter.com/Astarhub_io

New topics about Astar and Siden has been created:

https://www.altcoinstalks.com/index.php?topic=235266.0
https://bitcointalk.org/index.php?topic=5362748.new#new

And video for begginers has been posted in the old topics:

https://bitcointalk.org/index.php?topic=5355407.msg58040511#msg58040511
https://cp0x.com/topic/419-plasm-realizaciya-plasma-na-osnove-substrate/page/3/?tab=comments#comment-11344

I`m planning to post ecosystem updates in this topics weekly. 

Telegram: @igporoshin
Shiden address: aXueqwkrgUTVufyocGeBPm6NeSYp5k1ooPPJAGq3Ts7FtgF

**Comment by fiexer** [comment]
Thanks for your work.

Total points: 3
