### ISSUE TITLE
A7 - Development work for the Astar ecosystem

### ISSUE THREAD

**Issue by igorporoshin** [PlasmNetwork/growth-program#243]
The first iteration of information hub, which has been discussed on the forum: https://forum.astar.network/t/information-hub-for-astar-shiden/1341

First iteration consists of:

— Main page: https://astarhub.io/ (tutorials block is not working because tutorials page is under development now);
— Why Astar: https://astarhub.io/why-astar/ (page for users);
— Why build on Astar: https://astarhub.io/developers/ (page for developers);
— Beginners guide: https://astarhub.io/beginners-guide/.

(There are some issues in the layouts. We will fix it soon)

Second iteration:

— Wallets/dApps catalogue;
— Tutorials/materials catalogue.

The second iteration (full launch) will have been done by the end of Oct.

Wider promotion of the site will begins after the full launch. 

Design for all pages is done: https://www.figma.com/file/j0wJSOITf6fAtUsw6oQdmP/Astarhub?node-id=92%3A6

Telegram: @igporoshin
Shiden address: aXueqwkrgUTVufyocGeBPm6NeSYp5k1ooPPJAGq3Ts7FtgF

**Comment by fiexer** [comment]
Points will be given at the end of October when it's more evolved.
Thanks for your hard work, this is a great start and huge help for our dev community.

Keep it up!

**Comment by igorporoshin** [comment]
Second iteration is done:

— Ecosystem pages (Wallets/dApps/DevTools/Exchanges catalogue):

- https://astarhub.io/dapps/;
- https://astarhub.io/wallets/;
- https://astarhub.io/tools/;
- https://astarhub.io/exchanges/.

— Tutorials/materials catalogue:
https://astarhub.io/materials-for-users/;
and first material has been published: https://astarhub.io/tutorials/639/

Publishing is working via GitHub. Here is our repository https://github.com/Astarhub/guides-materials/. Everybody can publish a material via PR. E.g. here is an example of the first article: https://github.com/Astarhub/guides-materials/blob/main/users/materials/what-is-astar/index.md. Publication of external links (Medium etc.) will be possible during next 2 weeks. 

Also, we have started a development of courses section. Here is a page with all available courses: https://courses.astarhub.io/courses/.
And particular course page: https://courses.astarhub.io/course/stardard-protocol/. A lot of improvements coming. Will have been done by the Nov. 15.

So we need 7-10 days to to finish a small improvements, fix bugs and fill the site with a materials and tutorials. Then we can publish it and share with the community.

**Comment by fiexer** [comment]
Already added points for your work for the month October!

**Comment by igorporoshin** [comment]
1. 39 new tutorials/materials in 4 sections have been added:

— https://astarhub.io/materials-for-users/;
— https://astarhub.io/tutorials-for-users/;
— https://astarhub.io/materials-for-developers/;
— https://astarhub.io/tutorials-for-developers/.

2. Filtres for the tutorials/materials have been developed:
![filtres](https://user-images.githubusercontent.com/89736510/144129218-658bf4e8-354c-4738-89a1-256cbaee4e01.png)

**Comment by fiexer** [comment]
Added!
