### ISSUE TITLE
A8 - Shibuya collator fund application - All4Hodler

### ISSUE THREAD

**Issue by all4hodler** [PlasmNetwork/growth-program#245]
Discord ID : all4hodler#5953
Name on Telemetry : All4Hodler
Subscan link : https://shibuya.subscan.io/account/bF5pkmq6uQ1MHtvgNVuMD1kNUEPxo2onvuSrXHJwYsgvFVE
Email address : contact@all4hodler.com

**Comment by fiexer** [comment]
One of the rules to join collator fund is 15 days uptime!
Your collator has at time of writing 19h.
