### ISSUE TITLE
A8 - Challenge: create Astar/Shiden graphics

### ISSUE THREAD

**Issue by fiexer** [PlasmNetwork/growth-program#246]
Hi everyone

During the community program, we will also add challenges for our community to engage in. Our next challenge is for those with graphical skills! **Create Astar/Shiden graphics.**

What are we looking for:
* Hero images
* Social media mockups
* Art design
* Infographics about the ecosystem

## Rewards
**Rewards:** based on quality. 
Points to be earned: 0-50

## How to participate
Create a high-quality graphic that fit's the look and feel of Astar and Shiden Network. 
We would appreciate it if you tweet your contribution and tag @AstarNetwork and @ShidenNetwork.

## Rules
* Use brand guidelines to fit our look & feel
* Submit your graphic to this topic
* Challenge ends **Monday October 25th - 12PM UTC**

## Resources
* Astar [brand guidelines](https://github.com/PlasmNetwork/growth-program/blob/main/media-kit/AstarGuidelines.pdf)
* [Website](https://astar.network)
* [Marketing Slide Deck](https://speakerdeck.com/astarnetwork/astar-network-slide-deck-september-2021)
* [Mediakit](https://drive.google.com/drive/folders/1No-5CKE_3UI7OfsEjXdQt2be3K1r0xAb)
* [Community reward program](https://forum.astar.network/t/start-of-our-community-program/1367)

**Comment by donatello345** [comment]
Everyone will get reward for his work?

**Comment by fiexer** [comment]
> Everyone will get reward for his work?

Yes
Rewards: based on quality.
Points to be earned: 0-50

**Comment by zhekakrip** [comment]
My art work https://twitter.com/zhekakrip/status/1444642634572648452?s=20

**Comment by marvelet** [comment]
Hi Maarten, can you describe what ratio requirement? such as 16:9 for pdf pitch. Or it's free to us?

**Comment by fiexer** [comment]
Free to do so.

**Comment by donatello345** [comment]
My work about Shiden Network - https://twitter.com/soulmatescrypto/status/1449466632250744835

.png - https://ibb.co/NynySQk
Also, I can send in PSD format.

**Comment by fiexer** [comment]
Challenge closed! Points added

@mycryptoabs @vovaratskevich 
Please do share your Shiden address. Thanks

**Comment by vovaratskevich** [comment]
My wallet - bZE6VNTrWfw1orQq57Yd2Dfww4D1U9RQsoG2cekhebErtZt
