### ISSUE TITLE
A7 - Promotion of Shiden crowdloan campaign in CrowLoan Telegram Bot

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#26]
@crowdloanbot	5к+ users / 50+ integrations to TG
The first-ever Parachain Auction Crowdloan Telegram Bot. 
People use it to get info on every crowdloan campaign.
We added and promote Shiden  crowdloan campaign in our Crowdloan Telegram Bot.

**Comment by fiexer** [comment]
Please share PromoTeam Shiden address.

**Comment by fiexer** [comment]
Created in July or before and will not count for the new reward program
