### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by freestriker00** [PlasmNetwork/growth-program#267]
Telemetry name: ShibuyaNode
Discord: Pedro00@2039
mail: polkadot.stake@gmail.com
Subscan: https://shibuya.subscan.io/account/WovYkxuHfaf9RMJCeinnPVkgFfRqRA7rgbbLztrHXqn5qrk

**Comment by fiexer** [comment]
Please add your Shiden address in this thread.
Thank you.

**Comment by fiexer** [comment]
No points for the month October
