### ISSUE TITLE
A1 - Astar Shiden Indonesia - Medium Blog 

### ISSUE THREAD

**Issue by marvelet** [PlasmNetwork/growth-program#27]
**Link** : https://medium.com/@astarshiden-id
**Purpose** : Reach and engage both devs and community in Indonesia.
**Content** : Infos and simple tutorials translated directly from Astar and Shiden main Medium. 
**Target** : 2 - 4 entries a week (depending on the news)
**Start Date** : Week 1 - August 2021

**Delivery** :
Montly stat report every Week 1 (entries, claps, followers, etc)

**Note**:
Need somebody beside me to verify what I wrote (could be done using Google Translate)

**Comment by fiexer** [comment]
Great!
Could you make a contribution for each article? We will ask for your stats, 2 weeks after publication to calculate your points. 

So please create an issue for each article.
Thanks

**Comment by marvelet** [comment]
Sure Maarten, since last month we are busy at listing so I will update
every translation of the article that you wrote begin at tomorrow.

Later maybe I need a boost of tweet from Astar Twitter for this Indonesian
Medium 🙏

**Comment by fiexer** [comment]
Great! Thanks for you work.
