### ISSUE TITLE
A8 - Brand Guidelines book for Astar

### ISSUE THREAD

**Issue by greatbond007** [PlasmNetwork/growth-program#273]
To bring a little professionalism to Astar's branding, I have tried to create a branding guideline book that serves as a bible to everything related to Astar's branding world. 

It can help us maintain a structure in our marketing collaterals, define our aesthetics, and how we use our logo on different media collaterals. 

The idea is to bring aesthetics sense in our branding and marketing collaterals. 

Attached is the branding book.

[AstarGuidelines copy.pdf](https://github.com/PlasmNetwork/growth-program/files/7273338/AstarGuidelines.copy.pdf)

**Comment by fiexer** [comment]
This is a great guideline for everyone!
We highly appreciate this work.

Total points: 50
