### ISSUE TITLE
A2 - Creating interesting memes by Absorberch#0341

### ISSUE THREAD

**Issue by absorberch** [PlasmNetwork/growth-program#275]
First Meme - https://twitter.com/AndyHODL/status/1444700156671283211?s=20

My Shiden address - Z1jASjGDgtikEn6Vr5hmR7dQYNxSfFZHgS9D96nDBs2aY8b
Node name - absnode
Discord - Absorberch#341
Twitter - @andyhodl

**Comment by fiexer** [comment]
Points added!
