### ISSUE TITLE
A8 - Art About Shiden/Astar by Absorberch#0341

### ISSUE THREAD

**Issue by absorberch** [PlasmNetwork/growth-program#276]
https://twitter.com/AndyHODL/status/1444741686572339207?s=20

My Shiden address - Z1jASjGDgtikEn6Vr5hmR7dQYNxSfFZHgS9D96nDBs2aY8b
Node name - absnode
Discord - Absorberch#341
Twitter - @andyhodl

**Comment by fiexer** [comment]
Points added
