### ISSUE TITLE
A8 - Art About Shiden/Astar by kriptachina#6123

### ISSUE THREAD

**Issue by zhekakrip** [PlasmNetwork/growth-program#277]
https://twitter.com/zhekakrip/status/1444642634572648452?s=20

My Shiden address - WV3m497uYnknvLq4qyJbvWX2bcBr71qdhyj9gc7cAGsS3BF
Discord - kriptachina#6123

**Comment by fiexer** [comment]
Points are already given when posted in the Challenge
https://github.com/PlasmNetwork/growth-program/issues/246
