### ISSUE TITLE
A1  - Use Case Article About Shiden and Kinstsugi

### ISSUE THREAD

**Issue by pro100programmer** [PlasmNetwork/growth-program#279]
Wrote an article to educate people on the value of Shiden network
https://medium.com/@gavrysh.vova/featured-use-case-kintsugi-and-shiden-8b3616a42f60

Shiden wallet: YAXMMDKYhJoKKMWhr1qHTcaEroJhvqsVSMmABdEkxUimwyz
Telegram handle: @vova_op
Discord handle: PRO100SKILL#3728

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by pro100programmer** [comment]
![stats](https://user-images.githubusercontent.com/87698760/140648484-65b72f00-151a-46c1-88cd-9cd2cd7f1fd7.png)

Here are the stats of the article

**Comment by fiexer** [comment]
Thanks!
Points added

**Comment by fiexer** [comment]
Duplicate: https://github.com/PlasmNetwork/growth-program/issues/1596
