### ISSUE TITLE
C1 - Introducing projects

### ISSUE THREAD

**Issue by bLd75** [PlasmNetwork/growth-program#281]
Created groups with different projects to set future collaborations:
- Kodadot - founder Matej Wao - for integration of Kodadot explorer on Shiden/Astar - application to builder program to be coming
https://kodadot.xyz
- Crypto Moments - creation of a NFT serie based on Shiden EVM activation transaction + NFT explorer - new features and builder application program to be coming
https://cryptomoments.art/#/astarview
- Immunefi - CTO Duncan Townsend - just created, to be grown
https://immunefi.com

Shiden address: VxKQJYPqPQhuF4haU4M2BGYy434f2KWo2Ak4Z2PjUhtrChH

**Comment by fiexer** [comment]
Please do share your Shiden address.

**Comment by bLd75** [comment]
Sure, here it is
VxKQJYPqPQhuF4haU4M2BGYy434f2KWo2Ak4Z2PjUhtrChH
