### ISSUE TITLE
C2 - Persian community Development 

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#282]
Persian telegram group and channel
Persian  community in twitter 
Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share links of the channels.
Thanks

**Comment by Persianboy1382** [comment]
TG persian group:
https://t.me/Astarnetwork_Persian
TG persian Channel:
https://t.me/astar_persianANN
Persian Twitter:
https://twitter.com/AstarPersian?s=09

**Comment by fiexer** [comment]
Added to communities for monthly follow-up!
