### ISSUE TITLE
A1 - How to Create Shiden Wallet with Polkadot.js Article in Thai

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#288]
I also add Dark Mode tip and how to change language on Extension in the article

https://panupongpnp.medium.com/%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9B%E0%B9%8B%E0%B8%B2-shiden-network-%E0%B9%81%E0%B8%A5%E0%B8%B0-%E0%B8%AD%E0%B8%B7%E0%B9%88%E0%B8%99%E0%B9%86-99a5bd27e78a

Shiden Wallet : Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
Telegram: @pnp_404

**Comment by fiexer** [comment]
Points added
