### ISSUE TITLE
A8 - Telegram Stickers

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#289]
Telegram stickers for ASTAR
https://t.me/addstickers/asrarpersian
Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
My SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Points added!
