### ISSUE TITLE
A2 - Creating interesting memes by @minhquang262

### ISSUE THREAD

**Issue by chickenivy** [PlasmNetwork/growth-program#291]
Hi there,
My meme : https://twitter.com/chickenivy1/status/1445449741085544455
My tweetter : @chickenivy1
My telegram : @minhquang262
Shiden wallet : aqJqLFTwsvQy8GxCFNvnubLxU886eFLCy4Knz3piGQHrnRU

**Comment by fiexer** [comment]
Not added to rewards.
Total points: 0
