### ISSUE TITLE
A8 - My art @chickenivy1

### ISSUE THREAD

**Issue by chickenivy** [PlasmNetwork/growth-program#293]
https://twitter.com/chickenivy1/status/1445455493711818767

My Shiden wallet : aqJqLFTwsvQy8GxCFNvnubLxU886eFLCy4Knz3piGQHrnRU
My telegram : @minhquang262
My tweetter : @chickenivy1

**Comment by fiexer** [comment]
Not added to rewards sheet based on low quality.
