### ISSUE TITLE
A4 - Meet up

### ISSUE THREAD

**Issue by chickenivy** [PlasmNetwork/growth-program#294]
Astar French AMA on Twitter space - 2021 Sept 6th
Organized with Gunit - around 1 hour
https://twitter.com/AstarNetwork_FR/status/1434923264086843407?s=20

French Polkadot validators meetup - 2021 Sept 16th
Present Astar dApp Staking
Replay on Youtube: https://youtu.be/EZpxalDGTPg?t=4010
From 1:07:00 to 1:09:00 (2mn)
Summary article: https://medium.com/polkadot-francophonie/validators-enter-the-scene-immersion-in-the-heart-of-the-security-system-of-polkadot-b792f234799

**Comment by fiexer** [comment]
Meetup also mentioned in https://github.com/PlasmNetwork/growth-program/issues/286
Can you please explain your part in this? Thanks

**Comment by bLd75** [comment]
I think @chickenivy posted an unfortunate copy/paste, please submit the right content
