### ISSUE TITLE
A1 - Article about How to create shiden wallet in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#295]
Link:
https://telegra.ph/نحوه-اضافه-کردن-شبکه-shiden-network-در-کیف-پول-متامسک-10-05

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
My SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Can you share some stats about this article?

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۷-۲۳۵۹۵۲_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140661196-3293108c-a300-456f-a261-a311c8b5ee80.jpg)
