### ISSUE TITLE
Welcome masage and bot in Persian telegram group 

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#297]
Video for welcome massage in Persian telegram group:
https://t.me/Astarnetwork_Persian/295
Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
My SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
This is part of community management.
No additional rewards.
