### ISSUE TITLE
A1 - Recap of PromoTeam AMA session with VP of Growth for Astar & Shiden Network

### ISSUE THREAD

**Issue by vladylime** [PlasmNetwork/growth-program#30]
https://medium.com/polkadot-ecosystem-promoteam/recap-of-promoteam-ama-session-with-vp-of-growth-for-astar-shiden-network-maarten-e9fbcc7214be

Telegram: @vladylimes
Wallet: av6AYeM556wzE6ct1RKyCfTnZNXCfhWuxc93PVo7BWmXsMW

**Comment by fiexer** [comment]
Can you share the current stats for the story so we can calculate the points?

Please add screenshots.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by vladylime** [comment]
> Can you share the current stats for the story so we can calculate the points?
> 
> Please add screenshots.
> 
> How to see stats:
> https://help.medium.com/hc/en-us/articles/215108608-Your-stats

https://yadi.sk/i/ZpEoIsSpQell-w

**Comment by fiexer** [comment]
Total point: 9
