### ISSUE TITLE
Make the main group's sticker

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#303]
Telegram main chat stickers
https://t.me/PlasmOfficial/168635
Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN wallet:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Point already given here:
https://github.com/PlasmNetwork/growth-program/issues/289
