### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by alex-m24** [PlasmNetwork/growth-program#304]
1. Alex [Masternode24]#0722
2. 🔱Masternode24🔱
3. https://shibuya.subscan.io/account/XqbJjWyRVFcZKvrtszJC7ebzJCe7zQMaPhekQquVcYSVTQY
4. astar@masternode24.de

**Comment by fiexer** [comment]
Same address will be used:
XqbJjWyRVFcZKvrtszJC7ebzJCe7zQMaPhekQquVcYSVTQY
