### ISSUE TITLE
Introduce Dapp staking system Article in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#305]
An article about Dapp staking
https://telegra.ph/توضیحاتی-راجع-به-Dapp-staking-10-06

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۷-۲۳۵۹۵۸_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140661163-aa4cfd0a-d0c3-4167-9513-0d0b52f107f2.jpg)
