### ISSUE TITLE
C2 - Started a new community channel for Indian community - Telegram 

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#31]
I feel that the narrative of Astar and Polkadot needs to be marketed to its full potential in the Indian market. The Indian crypto market is growing at a tremendous rate since 2021, with exchanges like Coinswitch registering 2000% growth and user adoption in investment growing more than 5x every quarter. 

With Astart | Shiden being a dApp hub and an important pillar in the Polkadot ecosystem, I certainly feel that it is time that the project vision needs to be marketed in a way that people come to this eco-system with a strong sense of adoption.

With this small step of starting a telegram channel, I hope to accomplish a real positive sentiment for the project while also catering to all their queries | concerns | issues and provide a helping hand on behalf of the community.

The next step to this is inviting the Indian community and developers to this channel and help them with the resources that they require. 

Link to the telegram channel: https://t.me/AstarandShidenNetworkIndia

My SDN address: WGCXopi36Gbo8qDQgp9JuqdPKSQNVepXnP3JGBn5qQnzzaN

**Comment by SotaWatanabe** [comment]
This is a cool initiative! I would like to support you!

**Comment by fiexer** [comment]
Great work! Thanks for creating this
Glad to have you in our ambassador team

**Comment by fiexer** [comment]
Do not forget to mention your Shiden address!

**Comment by fiexer** [comment]
Please make sure you promote your Indian channel:
https://t.me/AstarandShidenNetworkIndia

**Comment by fiexer** [comment]
Community for August
Stats on September 5th

Total points: 0
No users joined the channel on Telegram

Feedback is always welcome, if not this issue will be closed at the end of the month.
