### ISSUE TITLE
A8 - Telegram sticker pack about shiden in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#311]
15 telegram stickers about shiden in Persian 
https://t.me/addstickers/shiden_persian

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN wallet:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Point added!
