### ISSUE TITLE
A2 - Meme about Astar

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#314]
Meme about Astar
https://twitter.com/AstarPersian/status/1446435276751097881?t=hjglz3hbbQU0dlyKGfpxaw&s=19

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Points added!
