### ISSUE TITLE
A2 - Understanding of Astar with memes

### ISSUE THREAD

**Issue by cryptodmeme** [PlasmNetwork/growth-program#32]
I created the meme with the utmost respect for Astar.
I hope it will spread on Twitter and get the word out to the crypto/web3 community.
Memes may seem like just a game, but they can only be created if you understand the project. And I think the key is to balance playfulness with respect.

[NEW]

I think sota-san is a character loved by everyone. He is the main character of blockchain/web3 and thus this meme was born.
https://twitter.com/cryptodmeme/status/1429095316175736845
![sota in parity2019](https://user-images.githubusercontent.com/82617175/130326257-fc8d9b0e-6d56-4a2c-91ef-7315025ee16c.gif)

I've created and posted shiden memes in the past. Please see it for reference.

[OLD]

Dapps staking may wake up your brain [RT 16 LIKE 23]
https://twitter.com/cryptodmeme/status/1409383871641055232
![image](https://user-images.githubusercontent.com/82617175/130326066-37128480-ee48-4439-a84b-de0af932a842.png)

Personify shiden developers and let the listeners relive the experience [RT 13 LIKE 12]
https://twitter.com/cryptodmeme/status/1408977311962079240
![image](https://user-images.githubusercontent.com/82617175/130326437-84da944f-5d84-42c8-885a-a4b9b0d75c2f.png)

The atmosphere of the shiden community is expressed here [RT 32 LIKE 35]
https://twitter.com/cryptodmeme/status/1408365286009409538
![image](https://user-images.githubusercontent.com/82617175/130326498-7972fa0f-500e-4c73-84ee-b41932f68ef8.png)

Sota-san is loved by dogs too! [RT20 LIKE18]
https://twitter.com/cryptodmeme/status/1408117680909942784
![image](https://user-images.githubusercontent.com/82617175/130326575-c3846a67-4d2b-44b6-8b4d-31224d914c26.png)

My grandmother fully understands blockchain. [RT12 QRT1 LIKE 10]
https://twitter.com/cryptodmeme/status/1407213663212118037
![image](https://user-images.githubusercontent.com/82617175/130326633-107b75bd-bb0b-4431-a21e-ac2f23b735e3.png)

It looks like he needs web3 [RT11 LIKE9]
https://twitter.com/cryptodmeme/status/1406821724079812617
![image](https://user-images.githubusercontent.com/82617175/130326786-8f102b38-62cc-4a31-b7de-f7548fbd0581.png)

shiden dislikes excessive announcements. And it's a technology (company) [RT18 LIKE 21]
https://twitter.com/cryptodmeme/status/1406389072881328128
![image](https://user-images.githubusercontent.com/82617175/130326855-4fc7ba58-8b62-422e-b91b-d5cdb6e31880.png)

Developers used to pay their own budgets to the blockchain. That was a long time ago? [RT12 LIKE17]
https://twitter.com/cryptodmeme/status/1405938696776339457
![image](https://user-images.githubusercontent.com/82617175/130326904-f1f8b684-2b52-434f-b22c-a2ffe3b0cfb8.png)

[my shiden address]
Ww388xVGbU2HAyRbabXEkERZJBpw8R1XGxXXQSW3pUXoPBg

Discord - CrypTod#5916 / Telegram - cryptodmeme

**Comment by fiexer** [comment]
Love your new meme! So funny 🤣 
Can you please add your Shiden address in this issue or future one so we have it logged. Thanks a lot

**Comment by SotaWatanabe** [comment]
This is so funny lol

**Comment by cryptodmeme** [comment]
> Love your new meme! So funny 🤣
> Can you please add your Shiden address in this issue or future one so we have it logged. Thanks a lot

@fiexer Added the address to this issue, thanks too! (Ww388xVGbU2HAyRbabXEkERZJBpw8R1XGxXXQSW3pUXoPBg)

**Comment by fiexer** [comment]
Thanks a lot
We can't add your older memes in our rewards program. We can only include the latest one.

Total points: 5

Feedback is always welcome, if not this issue will be closed at the end of the month.

**Comment by cryptodmeme** [comment]
> Thanks a lot
> We can't add your older memes in our rewards program. We can only include the latest one.
> 
> Total points: 5
> 
> Feedback is always welcome, if not this issue will be closed at the end of the month.
