### ISSUE TITLE
A7 - Setup the localization config and add translations on Astar-portal

### ISSUE THREAD

**Issue by impelcrypto** [PlasmNetwork/growth-program#320]
## Summary

Contributed on Astar-portal app.

* Moved words in HTML inline to the i18n file.
* Added translation file for Japanese and Chinese (Simplified and Traditional)
* Added translate documentation in ReadMe

SDN address: avf5nPmTfztUfq3gi1Bm3vBcEUHghUyrqRppXmsmDZ5hfrD
email: impelcrypto@gmail.com

PR:
https://github.com/PlasmNetwork/astar-apps/pull/52

**Comment by fiexer** [comment]
The scores put the importance of the work and the time into consideration.
Added!
