### ISSUE TITLE
SDN Buying Guide

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#323]
Exchanges that list SDN and a little Meme😁
https://twitter.com/AstarPersian/status/1446844015488507916?t=-pUxjW6jMtqJwk4RIJR0eQ&s=19

Discord handle: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Part of community management.
