### ISSUE TITLE
A1 – FAQ article in French - 2

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#326]
September 2021 :

- FAQ about Astar & Shiden in French : https://medium.com/@Gunit3124/faq-sur-astar-shiden-9a332bde0f98

![image](https://user-images.githubusercontent.com/85451570/136678294-daa19cf7-9b4c-41e0-94f1-1b6784347fb1.png)

**Comment by fiexer** [comment]
Added to: https://github.com/PlasmNetwork/growth-program/issues/331
