### ISSUE TITLE
A1 - Started a new Medium page for Indian audience and translated 12 articles in Hindi

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#33]
Started a new medium channel for the Indian community, so they can refer to the available resources - https://medium.com/@astarnetworkindia 

Have taken 12 latest and important announcement articles/releases and translated them in Hindi so everyone who isn't comfortable reading in English can refer to these Hindi articles.

I'm just conducting a final check of the articles again, in case there are some errors to it and this should be finished by today. 

Do let me know if there is some input on them.

**Comment by SotaWatanabe** [comment]
यह कमाल का है!

**Comment by fiexer** [comment]
Do not forget to tag your contributions with the correct task ID.
See article or Github readme.

https://medium.com/astar-network/astar-community-program-ee30b34f50f9
https://github.com/PlasmNetwork/growth-program/

**Comment by fiexer** [comment]
Please create a new issue for every article.
Also add stats when the article is published for 2 weeks, points will be given after 2 weeks.

We will close down this issue.
