### ISSUE TITLE
A4 - French AMA on Twitter space with Bld

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#334]
September 2021 : 

- Astar French AMA on Twitter space - 2021 Sept 6th : https://twitter.com/AstarNetwork_FR/status/1434923264086843407?s=20
Organized with Bld #286 - around 1 hour.

Overview of Astar, features (dApps Staking, Layer 2), Ambassador Program, Builder program, Community Program, Ecosystem, News, Q&A

**Comment by fiexer** [comment]
Points added
