### ISSUE TITLE
A5 - Social engagement / Giveaway NFT

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#335]
With Bld (#208), we organized a giveaway event to the french community to celebrate the EVM launch on Shiden :  
Giving the best ideas of dApps for Astar/Shiden

Prize : 1 NFT of Crypto Moments and 50 SDN (30 + 10 + 5 + 5).
23 applications received, 5 winners
Announcement: https://twitter.com/AstarNetwork_FR/status/1441144271831068675?s=20
Winners: https://twitter.com/AstarNetwork_FR/status/1443876546348044289?s=20

Medium article : https://medium.com/@Gunit3124/gagnez-un-nft-cryptomoments-pour-la-communaut%C3%A9-francophone-abfbecf7aa52

![image](https://user-images.githubusercontent.com/85451570/136678901-128d3bd1-2c77-4a6f-a7f5-6be55670cdcb.png)

**Comment by fiexer** [comment]
Do you want to get the funding of 50 SDN back?
Or want to use this in the community rewards program as a contribution?

**Comment by Gunit2481** [comment]
Using this as a contribution in the program

**Comment by fiexer** [comment]
Added
