### ISSUE TITLE
A3 - Video AstarHub : Introduction to Astar & Shiden

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#336]
To promote AstarHub, I helped igorporoshin (#239) by doing the translation of the scripts and slides into French and I did the voice acting for the video. 

- Introduction to Astar and Shiden in French : https://www.youtube.com/watch?v=qydJLP0fJ24

![image](https://user-images.githubusercontent.com/85451570/136679056-21d4a5ec-5ce5-44e4-a008-2e2650aa336d.png)

**Comment by fiexer** [comment]
Points added
