### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by wzzYtu** [PlasmNetwork/growth-program#337]
Telemetry Name: HashBamboo
My Shibuya Addr: XLhquTSNLgQKhzt4eV1L4J142GM2CEFxkESWb6bs1Whe1Kq
Discord Name: James Wang#8021
mail: wzzytu@163.com
Subscan: https://shibuya.subscan.io/account/XLhquTSNLgQKhzt4eV1L4J142GM2CEFxkESWb6bs1Whe1Kq
Specs:
4 CPU Cores
8 GB RAM
200 GB SSD

**Comment by fiexer** [comment]
Node needs updated version!
Will be added to the list after update!

Please reply when node is ready + add Shiden address

**Comment by fiexer** [comment]
No reaction and node not on Telemetry!
Not added to the program.
