### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by crypto-arcadia** [PlasmNetwork/growth-program#338]
Hi @fiexer, my node is online for more than 8 days. This is 30 points. ;) [#169](https://github.com/PlasmNetwork/growth-program/issues/169) and [#204](https://github.com/PlasmNetwork/growth-program/issues/204)

I am sorry to bother you and thanks in advance. Please find the details as follows:
- Node Name: `arcadia_shibuya`
- Subscan Link: https://shibuya.subscan.io/account/ZZ65pmnibywQ7sCNdxSDnsYJCaKgSLiCk58LD5Qh7foQWAj
- Discord Handle: `DK#8526`
- Twitter Handle: `@crypto_arcadia` or `@KAFFE360`
- Element Handle: `@lifewonderhow:matrix.org`
- Shiden Wallet Address: `5DoM7LKaV7p6GUjHRbkw5w5uoLF1e5qALRC51J5ekwwqGXG4`

**Comment by lagoJin** [comment]
Address is correct

**Comment by lagoJin** [comment]
@fiexer Hi,
Node Name: ShibuyaBox
Address: XwCUcDZCuBCWU32HungoYiET6g5nA4wneNmZNaDkoDzP74H
Please sent some SBY 32K to my address.
