### ISSUE TITLE
C2 - Created Astar Network Twitter channel for Indian community

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#34]
Just the start of a new channel for Twitter for the Indian audience - https://twitter.com/astarnetworkIN/

This channel will be used for translating our content into the Hindi language and engage with stakeholders in the Indian market.

In the start, it'll follow all the important stakeholders from the Polkadot | Astar ecosystem, globally and later some KOLs from the Indian fraternity and then engaging them to garner some level of engagement.

**Comment by fiexer** [comment]
Do not forget to tag your contributions with the correct task ID.
See article or Github readme.

https://medium.com/astar-network/astar-community-program-ee30b34f50f9
https://github.com/PlasmNetwork/growth-program/

Please send me the email and password of this Twitter to me in DM on Telegram, please.

**Comment by fiexer** [comment]
This will be added to your community work as Ambassador.

Points for August for running Twitter: 2
Please create an issue every month with your stats.

Can you also share your Shiden address?

**Comment by Greatbond-007** [comment]
Sure. I'll publish consolidated stats with a new issue at the end of the month for Twitter.
