### ISSUE TITLE
A1 - Translated Weekly Update 21 into Japanese. 

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#35]
This is link.
https://medium.com/stake-technologies-japan/weekly-update-21-8c42c37beb47

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats: 
https://help.medium.com/hc/en-us/articles/215108608-Your-stats

**Comment by realtakahashi** [comment]
![image](https://user-images.githubusercontent.com/38233656/132143280-72575f94-e196-4d99-afbe-ac265fc9a960.png)

**Comment by fiexer** [comment]
Total reward points: 2
