### ISSUE TITLE
C2 - Created a Chinese community WeChat media WeChat official account for Astar

### ISSUE THREAD

**Issue by Gravesyou** [PlasmNetwork/growth-program#36]
Last September, Astar Network WeChat official account was founded, and more than 50 original articles (including English translation and original articles) were published
https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=Mzg5NzQ2MTkxNg==&scene=124#wechat_redirect

**Comment by fiexer** [comment]
Hi Graves

Could you share your monthly stats every month here as an issue?
Can you share the stats for the month of August? Total members/messages/growth/... is this possible to see on WeChat?

**Comment by fiexer** [comment]
Also please share your Shiden address.

**Comment by Gravesyou** [comment]
Hi，Marrten
I'm Graves.
I'm glad to receive your email.&nbsp;I need to count the information and send it to you by email. Including shiden's address, is it also sent to you?



发自我的iPhone


------------------ Original ------------------
From: Maarten ***@***.***&gt;
Date: Sun,Sep 5,2021 5:52 PM
To: PlasmNetwork/growth-program ***@***.***&gt;
Cc: Gravesyou ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [PlasmNetwork/growth-program] C2 - Created a Chinese community WeChat media WeChat official account for Astar (#36)





 
Hi Graves
 
Could you share your monthly stats every month here as an issue?
 Can you share the stats for the month of August? Total members/messages/growth/... is this possible to see on WeChat?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gravesyou** [comment]
Hi,Maarten,
I'm Graves, this is my address about shiden:
Zt2Vxd2bUSKePmxZhQD6Qq8LfFQPzfnZ1g4RqF5z686VR3Z,
Thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PlasmNetwork/growth-program"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月5日(星期天) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PlasmNetwork/growth-program] C2 - Created a Chinese community WeChat media WeChat official account for Astar (#36)





 
Also please share your Shiden address.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fiexer** [comment]
You can leave your stats in this thread! Thanks a lot.

**Comment by Gravesyou** [comment]
Hi，Maarten，This is Official Account message template Data：
Fans: 5,697,
Article: 80,
Total views: 119,618.

**Comment by fiexer** [comment]
Can you inform me about the use of WeChat now?
Will this be still possible or will it completely migrate to Telegram with Chine new regulations?
