### ISSUE TITLE
C2 - Community Management Vietnamese

### ISSUE THREAD

**Issue by thanhmycm** [PlasmNetwork/growth-program#37]
My name is Le Thanh My
Vietnamese community manager
Telegram :
https://t.me/PlasmOfficialVietnam

My address Shiden :
ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

**Comment by fiexer** [comment]
Can you please make me admin so I can follow the stats?

I will also add you to our official community as a manager!

**Comment by thanhmycm** [comment]
Done sir
