### ISSUE TITLE
A7 - Public Dusty endpoints

### ISSUE THREAD

**Issue by Floxter** [PlasmNetwork/growth-program#39]
We just setup 3 public Dusty enpoints.

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdusty0.eusko.in#/explorer  (wss://dusty0.eusko.in)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdusty1.eusko.in#/explorer  (wss://dusty1.eusko.in)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdusty2.eusko.in#/explorer  (wss://dusty2.eusko.in)

Discord: Mcloud#4576
shiden adress: YcU6b2JCdc2g5TyBPK6ruYy4SL7MxMgQMRtN8vmaXPne9Qf

**Comment by fiexer** [comment]
Thanks a lot! 

Can you share requests received /day?
Also infrastructure you used? Users can create a free API on Bware Labs for Dusty, why would users use yours? Please share more information about Euskoin for the community.

**Comment by Floxter** [comment]
**Can you share requests received /day?**

Of course, we got also raw acces data from  reverse proxys if needed.

**last month data:**

![image](https://user-images.githubusercontent.com/83981055/132253280-4fc0c7e5-bc8a-448c-ac77-b0437676e0b1.png)

![image](https://user-images.githubusercontent.com/83981055/132253319-42c238cb-934f-4770-b1f0-e676652d5679.png)

**Also infrastructure you used?**

At first we were thinking about set one endpoint with the 3 endpoints load balancing service charge but then we realised that every endpoint was able to process decent amount of request whithout problems, so we decided to setup 3 separate endpoint that can be load balanced if request charge  increases significantly.

here is the architecture:

![image](https://user-images.githubusercontent.com/83981055/132253461-adf71f33-c998-4ab2-89b9-f37f392fc8b4.png)

**Users can create a free API on Bware Labs for Dusty, why would users use yours?**

Users can decide what to use, could use bware ,could use ours or both, thats people decision, we just want to give one more option to decide from.

By the way we dont get any user data for endpoint use, its just another comunity service and we will try  to maintain it 100% uptime and stable.


 **Please share more information about Euskoin for the community.**

Our Project is starting right now from the beginning. We are a team consisting of 4 people at the moment, we are selecting and hiring more members till we reach a structure of around 6-8 people. Our profiles are different, and we complement each other.
In principle, we would like to be self-financed, without banks or big funds, trough trading, parachain crowdload, etc. 

We are learning by doing, and when implemented, we will create our whole environment based on substrate, and interacting with all of the substrate ecosystem. 
So far, we are able to install the whole infrastructure by ourselves, and our testnet is in an advanced development state.
At due time, we will properly introduce ourselves and provide more details about the project (white paper, etc.). 

Please find atached our  pitch deck ppt to know a litle bit more about euskoin project.

Kind regards.

Floxter.

[Euskoin PD.pptx](https://github.com/PlasmNetwork/growth-program/files/7117576/Euskoin.PD.pptx)

**Comment by fiexer** [comment]
Great!
Thanks a lot for your extended research. I would like to add rewards but it would be great if you could switch from Dusty to Shibuya network. Shibuya will be our main testnet in the future and is from now for EVM projects. Could you build these RPC endpoint for Shibuya please?

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.shibuya.astar.network#/explorer

Node setup:
- Download binary here: https://github.com/PlasmNetwork/Astar/actions/runs/1206537950
- You can download the tokyo relay chain db here: http://65.21.145.34/tokyo-db.tar.xz
- Start node with ./astar-collator --validator --name NODNAME --chain shibuya --parachain-id 1000 --rpc-cors all --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' --execution wasm
- Get synced
- Send address to receive some SBY for session key
- Set session key
- Share address so we can add you to the whitelist

**Comment by Floxter** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshibuya.eusko.in#/explorer
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshibuya1.eusko.in#/explorer
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshibuya2.eusko.in#/explorer

Same Arquirecture now on Ubuntu 21.04, dusty endpoints has been removed.

**Comment by fiexer** [comment]
Added Shibuya endpoints to our documentation:
https://docs.astar.network/integration/network-details

Total points: 30
