### ISSUE TITLE
A1 - Translation of the article "Weekly Update #20" into Czech language #40

### ISSUE THREAD

**Issue by Fernglenburnaby** [PlasmNetwork/growth-program#40]
I translated the article "**Weekly Update #20"** into Czech language for the Czech Astar community.

https://medium.com/@thomasjaros/astar-network-update-ff2592c55c9

telegram handle: @Vespertiliocap
my Shiden wallet address:  XkxrBnVjcwwD8Buo7U66s2tvDMrsXrJsFkbhfmqWi9TxK5L

**Comment by fiexer** [comment]
Can you share the current stats for the story so we can calculate the points?
Please add screenshots.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by fiexer** [comment]
No stats no points.
