### ISSUE TITLE
A1 - Blog article on Astar/Shiden Technologies

### ISSUE THREAD

**Issue by anaelleltd** [PlasmNetwork/growth-program#41]
**Topic:** Shiden's deployment & technologies
**Link:** [Parachains unchained ](https://app.subsocial.network/4323/parachains-unchained-19052)
**Shiden wallet:** Z1fHUw3G38sDiuJ8mGBGoiCJwyV5Qg2zdrNxzV49Drhf2ft

**Comment by fiexer** [comment]
Total points: 7

Feedback is always welcome, if not this issue will be closed at the end of the month.

**Comment by anaelleltd** [comment]
Thank you, @fiexer. :)
