### ISSUE TITLE
A1 - Translated article into Belarusian language and published in my medium

### ISSUE THREAD

**Issue by kubvil** [PlasmNetwork/growth-program#44]
A1 - Translated 1 article into Belarusian language and published in my medium

https://kub198828.medium.com/onfinality-%D1%96%D0%BD%D1%84%D1%80%D0%B0%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%BD%D1%8B-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D1%91%D1%80-astar-57915ada45c5

telegram handle: @kubvil88
my Shiden wallet address: WBR6xowc6fNGhKkJgaF5ELx4UfLVjr14iFdpXqJ5w9jZMC5
Discord kubvil#4326

**Comment by fiexer** [comment]
Can you share the current stats for the story so we can calculate the points?
Please add screenshots.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by kubvil** [comment]
![Uploading 121.jpg…]()

**Comment by kubvil** [comment]
![121](https://user-images.githubusercontent.com/36472994/134770719-0625655e-2c17-4a9b-9654-e7a9ee685f6a.jpg)

**Comment by fiexer** [comment]
Can you please share the links where you shared this article?
Thanks :pray:

**Comment by kubvil** [comment]
I published in crypto groups on facebook. I can share the groups in which I published. A month has passed, where can I find links? If you clarified right away that you need links, then I would write everything down and provide it to you. I published some articles on my twitter.

**Comment by fiexer** [comment]
Total points: 4
