### ISSUE TITLE
C2 - Community Management

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#45]
My name is Shin Takahashi.
My job is software engineer of japanese securities.
I'm interested in implemeting smart contract and pallet. 

2021/08:
- I worked to actively answer questions on Discord. However, I remember the number of responses within a month was 10 or less.
- I attended the Ambassador Call.
- I spoke at the Astar Forum and always voted for voting rights.
- I implemented and proposed a faucet pallet.

**Comment by fiexer** [comment]
Thanks for sharing your contributions.
See spreadsheet for community management.
