### ISSUE TITLE
A1 - Translated "Community Rewards" article into Japanese

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#46]
The link is as following.
https://medium.com/stake-technologies-japan/astar-community-program-1ecddb9d11ab

**Comment by realtakahashi** [comment]
![image](https://user-images.githubusercontent.com/38233656/132143247-a3f4ffff-bfe2-4c47-ae36-a5ce425da4ad.png)

**Comment by fiexer** [comment]
Total points: 3
