### ISSUE TITLE
Shiden Airdrop

### ISSUE THREAD

**Issue by Adityudhatama** [PlasmNetwork/growth-program#469]
https://twitter.com/aytiday/status/1447616536949055489

Shiden address:- XanWKGJcmwEAfZ5gN7QSojN8RyDM8kv8d3zu91Jh3Lb97Tx

**Comment by bimaibra** [comment]
https://twitter.com/ManOfTheNorth17/status/1447618571631169537?t=Ka8SqDONk4CspJaRqIGXZA&s=19

Shiden Address : XMckvNKL8SS5GuRhVaMFw9McsTDSe8naRmFeXxi2JfsGo5r
