### ISSUE TITLE
C2 - Community Management - Poland

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#47]
As Polkadot and Kusama ecosystems are growing strong, and we had a successful first batch of auctions where Shiden performed super well, we also see that blockchain community interest in the Polkadot ecosystem is growing even more than the ecosystem itself. 
We discovered a lot of local Polish blockchain users and enthusiasts keen on Polkadot, Kusama and parachains, and Web3 in general. 

As Astar Ambassador and long-term supporter and a founder of ELEVATE Community Ventures, which focuses mainly on supporting projects in community and ecosystem development on a local and global basis, I decided to launch Astar and Shiden Polish Community dedicated telegram group under ELEVATE Community Ventures management and my curation. 

Please feel more than welcome to join our launch - https://t.me/Astar_and_Shiden_Network_Poland

In ELEVATE we have gathered a lot of local community users and investors who like and do support projects on their development way and are willing to engage in local social space creation and project support. We are already working closely and supporting many projects from the Polkadot ecosystem, building trust in the Polish local community, Polkadot ecosystem awareness, and building one big Internet of People on top of the Polkadot ecosystem which is the working ground for Astar and Shiden Network. - https://elevate-cv.medium.com/ 

It's time for dedicated space for Astar and Shiden Network in our local ecosystem development! 

We already prepared some materials and Infos to linearly publish on the newly established telegram group. Starting from now, I as Astar Ambassador, Elevate founder, and leader and my community will develop that space and make it user-friendly, educational. informational, fun, and nice place to hang around in crypto space and mainly Astar and Shiden ecosystem. 

We have some ideas ready to present in regards to the local community development roadmap and informational articles, youtube videos, tutorials, meme campaigns, and other activities which will present all aspects, utilities, and functionalities of Astar and Shiden protocols to users. 
Taking into consideration that ELEVATE takes a big focus on community and users activity, we develop the community, by encouraging users to do translations, tutorials, graphics, etc as contributions. We think that when users actively take part in developing the ecosystem and their own social space on top of the project it's the best way for them to dive deep into project details, understand all nuances, architecture, and utilities of the project and then, they are ready and more open to actively join project development and identify with all ideas, utilities, and values. 

I also think as Elevate and Stakenode founder and leader that users should have a chance to be rewarded for such contribution and support when actively taking part in its development. To be able to create such user friendly and encouraging local social space on top of Astar and Shiden I would like to commit such proposal:

Elevate Community Ventures as a legally registered organization under Polish law, can spin up Collator Node on Shiden Network under my curation and management. This collator node will be securing the network in addition to other collator nodes, so its network benefit, and will be generating collator rewards. Those rewards would then be used to be distributed among local Polish community members who actively create the space and ecosystem, produce content, do translations, etc. Additionally, we would use those rewards to later reward users in our local campaigns and community competitions. 

I would love to hear Team and Council comments about my idea of community development and I'm more than happy and honored to be able to start growing the local community around Shiden and Astar Network and supporting Team in future development and network growth. 

Together we can do more! 

My Shiden Wallet Address as requested:
bUVmJR3gu1hi9qa41pzFWWfFP4QVUYPyntNKjhort4BPovK

Stakenode Twitter Account: 
https://twitter.com/stakenode_dev

**Comment by fiexer** [comment]
Great to see your commitment to this program Jimmy!
I added you for the Polish community in the spreadsheet. Can you please make me admin in the group so I can check the stats of the community on Telegram?

It's great what you are doing with Elevate and please do share all the work you did to this program. We do support all initiatives done by our Ambassadors and do believe they can work autonomy because of their long-term commitment to the project. 

If you would like to have a call, you can always book a slot in my calendar.
Keep up the good work! Really like the work you do.

**Comment by jimmy-tudeski** [comment]
Maarten, I added You to the Polish telegram channel as admin. But it seems like I can't see the stats as those are available for groups with more than 1000 members, or maybe You have some trick to get those.
