### ISSUE TITLE
C2 - Community Management Funding - Council Governance Proposal

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#48]
I would like to present the Local Community Management Development Funding to Astar Team and Council. 

1. Me as Stakenode and Elevate founder will spin up a node under ELEVATE Community Ventures instance - a legally registered company in Poland which I manage. 
2. Collator Node would be maintained and curated by me and Elevate Community support and would be a Community Collator Node.
3. Funds coming from collator rewards would be used for local Polish community development. 
4. All funds would only be ever used for community development, rewards for users actively taking part in social space development, and being active contributors to the local and global community. The funds would be also used for community campaigns, competitions - like meme contests, challenges which we will actively imply and develop on along the community growth. 
5. Funds would be used for rewarding additional Polish Community Telegram Group admins and moderators - if such would be needed further on community development and users growth. 

Funds distribution as rewards can be presented to Astar and Shiden Council and Team on monthly basis in form of a report or summary. 

I'm ready to discuss further details of this proposed development and looking forward to seeing Council and Team comments about the idea in general. 

Jimmy - Stakenode & Elevate

**Comment by Greatbond-007** [comment]
Hey, from an ideation perspective it is really cool. This idea IMHO achieves two objectives. One, it helps on the tech front and secondly, the rewards are given back to strengthen the community.

**Comment by fiexer** [comment]
This really looks interesting Jimmy!
Block rewards, will only be used for the Polish community? Maybe Elevate can use these funds to be used in all local communities? I think a lot of our communities can grow with this idea?

**Comment by fiexer** [comment]
This is an open topic for discussion.
The issue is not included in the community reward program.

**Comment by jimmy-tudeski** [comment]
Maarten, Thx for Your feedback. 
Elevate Community Node can be a general Community Node and funds would be used for all local communities' development if required. We can make it some general Community node for local communities development. I want this to be a big general community development plan - from that collator rewards we can fund all local communities initiatives also. Happy to develop the idea further and Yes, this is an invitation also to other community leaders. 

Node is already synced and running for some time. I even applied with google for and set the identity. If You will only decide and give the green light - You can whitelist the node and it can start sealing blocks and generating rewards. They will not be used until we will set the final structure and design.

**Comment by fiexer** [comment]
Thanks for your comments.

I will add your node in the next batch for Shiden.
Make sure your IP will not be blocked by your provider ;-)

You will receive an email with more information when you are set as a collator.
Please book a slot in my agenda to discuss this further: https://calendly.com/maarten-astar/ambassador-candidate

**Comment by fiexer** [comment]
Could you please share your address for the Elevate community node?
Thanks!

**Comment by jimmy-tudeski** [comment]
Zi2FAd7j1YdERDKKnYBh3Rd3WQNPoGDmAKfXasNqYZryaEi

**Comment by fiexer** [comment]
@jimmy-tudeski your community node is onboarded!
First block produced: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fshiden.api.onfinality.io%2Fpublic-ws#/explorer/query/329120

**Comment by fiexer** [comment]
Would it be possible to create a forum topic about this?
A topic about more information and guidelines for Ambassadors who want to apply for the funds.

Thanks
