### ISSUE TITLE
A8 - Shibuya collator fund application

### ISSUE THREAD

**Issue by tunkas** [PlasmNetwork/growth-program#489]
Discord ID: tunkas#7609
Node Name on Telemetry: DogToothTuna
Subscan link: https://shibuya.subscan.io/account/Z7C92Huf8Ktv2K7XNWZ7muSDxEM64NJAqY14u13WBaGfqAo
Contact Email address: antuntun@tutanota.com
Shiden node address: bhLkxrRDRQnjNCVz5RNFfJpGAroyPw33it28MenNQMbMcJn

**Comment by fiexer** [comment]
Added to the sheet!
