### ISSUE TITLE
A7 - Public telemetry

### ISSUE THREAD

**Issue by Floxter** [PlasmNetwork/growth-program#49]
web interface : https://telemetry.eusko.in

to send your node data use:   

 --telemetry-url 'wss://telemetry-back.eusko.in/submit/ 0'

**Comment by fiexer** [comment]
Can you please explain why we should need another Telemetry?
Thanks a lot.

**Comment by Floxter** [comment]
If general telemetry fails this can allways be a good option, also devs can use it for testing without charge principal one because 
we dont filter any network.

The infraestructure is like this:

nodes ------> backend server <------> frontend server.

conection between back/front its  establised over secure web sockets, backend server receives node conections trougth reverse proxy over SSL.

frontend server also gots a proxy cache for http conections.

kind regards.

**Comment by fiexer** [comment]
Can you build this to point to Shibuya testnet?
Thanks

**Comment by Floxter** [comment]
yes it works with Shibuya.

![image](https://user-images.githubusercontent.com/83981055/132900965-ef5bef66-3694-402c-a226-6454c90efa67.png)

**Comment by fiexer** [comment]
Total points: 15
