### ISSUE TITLE
A1 - Introduce crowdloan and auctions Article in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#498]
Introduction Article about ksm/dot auctions 
https://telegra.ph/توضیحاتی-راجب-crowd-loan-و-حراجی-های-پولکادات-و-کوساما-10-11

Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

**Comment by Persianboy1382** [comment]
![Screenshot_۲۰۲۱۱۱۰۸-۰۰۰۰۰۸_Telegram.jpg](https://user-images.githubusercontent.com/91786817/140661141-3d18b080-b194-486e-89dc-0a3014e8f995.jpg)
