### ISSUE TITLE
A6 - The community of Bulemountain Labs BMLOfficial Account message template Promoting Astar and Shiden

### ISSUE THREAD

**Issue by Gravesyou** [PlasmNetwork/growth-program#52]
BML Output 4 Astar articles, in-depth interpretation of the project development of Astars, I also made an Astar lock-in tutorial, analyzed the investment income of KSM crowdloan of Shiden, called on the partners of the community to participate in crowdfunding.
1、Last September pledge ETH tutorial：https://mp.weixin.qq.com/s/HpUEPGc-ZSO6nh8wtillZg
2、An in-depth analysis of Astar：https://mp.weixin.qq.com/s/JasYzV9zrnLfHRnQQ5na1w
3、Astar Network is based on application level interpretation.：https://mp.weixin.qq.com/s/2nv-JSqZ_coRdoCdV6LsDw
4、How Astar Forerunner's Shiden Network got involved in the Kusama auction：https://mp.weixin.qq.com/s/249pLYn_7SsxwtkReWeplA

**Comment by fiexer** [comment]
I'm not so familiar with weixin.
Can you get stats from each store published there?

It would be great if you could create an issue for each article you created. This makes it easier for me to manage the contributions. Thanks for answering.
