### ISSUE TITLE
C2 – Community Management – August 2021

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#55]
Hello everyone, my name is G’ and I’m a French ambassador for Astar and Shiden Network.

During the month of August 2021, I was involved in different communities and managed two French Astar channels. I helped community members by answering questions about Astar and Shiden and contributing to the growth of our ecosystem. 

Here, I share stats of the groups to follow the evolution of our ecosystem’s involvement and my participation in those groups.

- Discord : Polkadot francophonie (180 members), PolkaFrance (1800 members), CryptoMatrix (14k members). Astar & Shiden Network (10k members), Polkadot (Official) (10k members)
- Telegram : PolkaFrance (4k members),
- Twitter : 800 followers & 13 tweets about Astar & Shiden

With bld, we manage the twitter of @AstarNetworkFR (80 followers & 45 tweets) and the telegram group of Astar Network France (195 members). 

Telegram : @Gunit31
Discord : @G'ₑₓₚₑcₜ cₕₐₒₛ#3121
Twitter : @gunit3124 https://twitter.com/gunit3124 
Wallet : 5FCtjd5s9xGAnFbBBsEcyEpr7Mg98eEuj43pMDUsqKgM8RBf

**Comment by fiexer** [comment]
This is not a Shiden address, can you please verify:
5FCtjd5s9xGAnFbBBsEcyEpr7Mg98eEuj43pMDUsqKgM8RBf

Your community management work will be added for managing the French community.
Thanks for your hard work.

**Comment by Gunit2481** [comment]
Thank you Maarten,

Here is my Shiden address : 
Z5VAv3wwBuH15d1gAgjztz8CQPG6rwekFYxavgjhggJicsk
