### ISSUE TITLE
A1 – Blog article and translated articles into French

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#56]
Hello, during the month of August 2021 :

I created an article to present Astar and Shiden in French :
- Astar Network, the gateway to a multi-chain network :  https://link.medium.com/auDZvD314ib 

I translated 3 articles from Sota and Maarten in French :
- Weekly update 21 :  https://link.medium.com/MNDXjy214ib 
- Community rewards :  https://link.medium.com/goSx1vQS1ib 
- Shiden Network Official Launch : https://link.medium.com/xlOv5CYs8ib

**Comment by fiexer** [comment]
Hi G

Could you please make an issue for each contribution? This makes it much easier for me to manage.
If the article is older than 2 weeks, please also provide us with the stats. Thanks a lot.

How to see stats:

[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)
