### ISSUE TITLE
A6 – Tutorial step-by-step in French : 

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#57]
Regarding the upcoming listing of SDN, I made a tutorial step by step to see SDN tokens and to unlock vested tokens.

Medium : https://link.medium.com/irmAuxbM6ib

**Comment by fiexer** [comment]
Thanks for your contribution.
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by Gunit2481** [comment]
![image](https://user-images.githubusercontent.com/85451570/133014785-ac2b5653-1c5a-43a6-91a2-790e2271606d.png)

**Comment by fiexer** [comment]
Total points: 10
