### ISSUE TITLE
A2 - Creating memes!

### ISSUE THREAD

**Issue by nuttapat007** [PlasmNetwork/growth-program#58]
twitter - @nuttapat_chu
Telegram - @nuttapat007
Discord - nuttapat007 #2602
Wallet - a7df2mcfXK9ic7hJcTgtxXJ7WSrJSphqsopYVNFRhTcJtst

Meme 1 : https://twitter.com/nuttapat_chu/status/1432206494594789376
Meme 2 : https://twitter.com/nuttapat_chu/status/1432208830188834825
Meme 3 : https://twitter.com/nuttapat_chu/status/1432211528204230657

**Comment by fiexer** [comment]
Thanks a lot for your contributions.

Total points: 1
Feedback is always welcome, if not this issue will be closed at the end of the month.
