### ISSUE TITLE
A1 - Shiden Network FAQ

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#59]
Prepared and released medium article about FAQs asked by the community. 

https://stakenode.medium.com/shiden-astar-network-faq-6c2067a86cbf

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by jimmy-tudeski** [comment]
Sure, with pleasure - here are some stats for today  - 07.09.2021. Will update this in coming days

https://medium.com/me/stats/post/a968bba8f591

**Comment by fiexer** [comment]
Please share the screenshot.
It's not possible for me to see the stats with this link.

Thanks a lot

**Comment by jimmy-tudeski** [comment]
Here are the screenshots from Article Stats:
![Astar FAQ Stats 1](https://user-images.githubusercontent.com/68714636/134359462-88de3072-7dd8-46a3-9b7b-980a21615d72.png)
![Astar FAQ Stats 2](https://user-images.githubusercontent.com/68714636/134359486-6fa08bc9-ab7d-4a89-93fd-001d6d865911.png)

**Comment by fiexer** [comment]
Total points: 17
