### ISSUE TITLE
A8 - Poster to promote dApp staking

### ISSUE THREAD

**Issue by abk400** [PlasmNetwork/growth-program#604]
I Created Poster to promote dApp staking https://pbs.twimg.com/media/FBhfuYEWUAs077z?format=jpg&name=small
 
 In my personal Twitter 
 https://twitter.com/KoshelArt/status/1448013175467692034
 and corporate with 7k followers
 https://twitter.com/Hot_invest/status/1448014159606648840?s=20

Discord: KArt#3451
Shiden wallet address: 5DXENXeqdtxvNUcLJkqqtaZ2jb1zwYbdQUXHKxS44J3Duo1m
Telegram: @GoodService4u

**Comment by fiexer** [comment]
Please share your Shiden address.
You shared your Kusama address. Thanks

**Comment by abk400** [comment]
Hi my SDN address is bRUdLdK7grFt65Kj6Xtz6zECttJ485UKFXG1ipDARFp6Xj2

**Comment by fiexer** [comment]
Added!
