### ISSUE TITLE
A1 - Article on promoting builders program & community program in Indian community

### ISSUE THREAD

**Issue by Greatbond-007** [PlasmNetwork/growth-program#62]
Created a medium article with two objectives:
1. Inviting two ongoing programs- builders program and community program in the Indian community. 
2. Sharing the articles within a few closed groups of the Indian community - WhatsApp group, telegram group to expand the popularity.

https://medium.com/@astarnetworkindia/astar-shiden-network-welcomes-indian-developers-and-community-members-with-their-two-ongoing-6e2951deb266

https://twitter.com/astarnetworkIN/status/1432289876326686722

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by fiexer** [comment]
Please share stats!

**Comment by greatbond007** [comment]
Total views 23. Didn't reach the audience in the desired manner!

**Comment by fiexer** [comment]
Total points: 8
