### ISSUE TITLE
A2 - Creating memes for Shiden exchange launch

### ISSUE THREAD

**Issue by theojamiller** [PlasmNetwork/growth-program#63]
Telegram - @hidden_meaning1
Discord - Hidden_Meaning#0500
Wallet - Gk7N9HeG8y5UaRWLYU5pSz78bigRhavHeZc43NfWvSwKhBr

Meme 1 : 
![And Then There Was Shiden](https://user-images.githubusercontent.com/78944028/131333495-c265304d-9d6f-4124-8bc2-26110a0f3d38.gif)

Meme 2 : 
![Hello there](https://user-images.githubusercontent.com/78944028/131333506-60a2f26b-5641-400e-ac6e-06a58c2daed6.gif)

Meme 3 :
![Coming To Market](https://user-images.githubusercontent.com/78944028/131333539-98de73eb-c0c6-4b99-903d-1b199c4918ce.gif)

Meme 4 :
![Shiden Has Popped Out](https://user-images.githubusercontent.com/78944028/131333554-a2ae726d-10c1-4e0f-9f05-4d280328a889.gif)

Meme 5 :
![Get Ready](https://user-images.githubusercontent.com/78944028/131333578-47cd767a-40c3-4949-ba70-f4edee15a0a2.gif)

Meme 6 :
![Wen Now](https://user-images.githubusercontent.com/78944028/131333699-2dc67adf-5585-487a-8a06-8cd9bdb7e7a7.gif)

Meme 7 :
![Lazer Eyes Time](https://user-images.githubusercontent.com/78944028/131333741-f0ab7d7b-f483-4673-80db-28e7500bc83e.gif)

**Comment by fiexer** [comment]
Thanks for your contributions.

Total points: 2

Feedback is always welcome, if not this issue will be closed at the end of the month.
