### ISSUE TITLE
A5 - New listing allert in persian

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#641]
New listing allert and a poster for exchanges listed SDN
https://twitter.com/AstarPersian/status/1448289660229275654?t=kk51zbtYmhd9hVSMJ2kYYQ&s=19

Discord: pooya#0847
Telegram handle: https://t.me/Persian_ambassador
SDN wallet:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Part of community management.
