### ISSUE TITLE
A3 - Videos about Astar/Shiden

### ISSUE THREAD

**Issue by Tejasvithalani** [PlasmNetwork/growth-program#647]
I created a video tutorial about Astar/Shiden   

Video link : https://youtu.be/Qdhv_8N6P90

My youtube handel: https://youtube.com/channel/UCQ5OSv3l049M_zmYkudtYqA

And shared it on twitter : https://twitter.com/Tejas11122001/status/1448320326958415872?t=EiycfRVyBgoxEJNf48Qntg&s=19
Twitter handel :@Tejas11122001

SDN ADDRESS : avULcFvZbSCdW6SE2RZnhEmhWGVM7iFbSdGL99wLaaX2dEY

**Comment by fiexer** [comment]
Video provides incorrect information!
Wrong use of community rewards program
