### ISSUE TITLE
A4 - Guest Lecturing on dApps and Astar Network

### ISSUE THREAD

**Issue by theojamiller** [PlasmNetwork/growth-program#65]
Telegram : theojamiller
Discord : theojamiller#0500
Wallet : a7697urR1bFwkdu4979x9nP549ZbFUUrUDzu6JZuVEQAZVF

![image](https://user-images.githubusercontent.com/78944028/131340716-859dea4c-3f98-42ad-b86d-3c0acfb3fb9c.png)

![image](https://user-images.githubusercontent.com/78944028/131340589-5d182381-b65e-4d2d-a72f-97eac18744c8.png)

https://youtu.be/tMTvE6rH2-A

**Comment by fiexer** [comment]
Cool!

Total points: 8

Feedback is always welcome, if not this issue will be closed at the end of the month.
