### ISSUE TITLE
A1 - Create Article about dAppstaking and Requirement

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#650]
https://panupongpnp.medium.com/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81-dappstaking-%E0%B8%9A%E0%B8%99-shiden-astar-network-cf98c2375d37

Shiden wallet: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF
telegram : pnp_404

**Comment by fiexer** [comment]
Points added
