### ISSUE TITLE
A1 - Posts/Articles/Texts - August 2021 Contributions - Vlady Limes

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#66]
https://medium.com/polkadot-ecosystem-promoteam/recap-of-promoteam-ama-session-with-vp-of-growth-for-astar-shiden-network-maarten-e9fbcc7214be?source=collection_home---4------2-----------------------																									
Astar AMA and Recap | Russian and English																									
https://medium.com/polkadot-ecosystem-promoteam/promoteam-catches-its-breath-the-first-set-of-crowdloans-is-over-more-to-come-9fc1813c2e5d?source=collection_home---4------4-----------------------																									
Review article of crowdloan campaign Bifrost | Shiden | Karura | Khala

**Comment by fiexer** [comment]
If these are contributions from Vlady, why is this posted under your account?
This is very confusing.
