### ISSUE TITLE
A3 - Video About Shiden 

### ISSUE THREAD

**Issue by abhishek23x** [PlasmNetwork/growth-program#663]
Hi, I have made video on your community event. 

Video Link ( check from 19:45 Minute ) :
https://youtu.be/80Mfv0-xAQw

Address : Zc1h68fMxkJyvvhUzFEJ6u6M7a9VuEACSdQqiBLwMZNnZqW

**Comment by fiexer** [comment]
Wrong use of promoting the community rewards program.
