### ISSUE TITLE
A3 - Videos  - August 2021 Contributions - Alex PromoTeam / Vlady Limes																									

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#67]
Metioning Shiden and Astar in news releases																									
https://www.youtube.com/watch?v=xpcAldplYg0&t=3s  Shiden  																									
https://www.youtube.com/watch?v=GqHmrPDjKec  Astar  																								
https://www.youtube.com/watch?v=YiCXw68O0zk   Astar

**Comment by fiexer** [comment]
First video is already reported by Vlady!
Please make simple rules together because this is not working!
