### ISSUE TITLE
A6 - Instructions to create Polkadot.js wallet | Withdraw SDN | Staking on dApps Staking (Video)

### ISSUE THREAD

**Issue by thanhmycm** [PlasmNetwork/growth-program#675]
I have created a detailed video tutorial on **how to create a Polkadot.js wallet** and **withdraw SDN from the exchange** and **instruct users to place stakes in the store Portal.astar.network**

Youtube Channel: https://www.youtube.com/channel/UCTa3tGhBR4v_bG_4_5RBVvQ

Video: https://youtu.be/dhyV3l41wTA

Shiden Address: ZsW9bEh2uj9x7AfgmmxyydQiQpWBg8RpBE9cJkrNXFbc7rd

**Comment by fiexer** [comment]
Great video!
Points added!
