### ISSUE TITLE
A5 - Tweets/Telegram/ - August 2021 Contributions - Alex PromoTeam / Vlady Limes 

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#68]
Here is some of mentionigs of Astar and Shiden in social networks and telegram channels
https://t.me/ParachainNews/642																									
https://t.me/ParachainNews/618																									
https://t.me/ParachainNews/606																									
https://t.me/ParachainNews/603																									
https://t.me/ParachainNews/586																									
https://t.me/ParachainNews/583																									
https://t.me/ParachainNews/578																									
https://t.me/ParachainNews/569																									
https://t.me/ParachainNews/564																									
https://t.me/ParachainNews/541																									
Twitter support - retweets from  4 accounts ( up to 5-16k subscribers)

**Comment by fiexer** [comment]
Thanks a lot for your report.

Total points: 15

Feedback is always welcome, if not this issue will be closed at the end of the month.

**Comment by fiexer** [comment]
Please share your Shiden address for Promoteam.
Thanks
