### ISSUE TITLE
A5 - Russian Community Development - support/translations- August 2021 Contributions - Alex PromoTeam/ Vlady Limes

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#69]
Russian Community support/translations- August 2021 Contributions - Alex PromoTeam/ Vlady Limes
https://t.me/PolkadotRu	2,2k	Providing info about the project 																							
Russian TG group	900+ (+120)	support, promotion, Q&A, and so on

**Comment by fiexer** [comment]
We can only reward for the Russian Astar community because this is the official channel for the Russian community.
You will receive the same rewards as Vlady for managing the community. 

Please made me admin for the Russian community so I can see the stats.
Thanks a lot.

**Comment by fiexer** [comment]
Will add this to the list because it's related to social engagement.
Total points: 10
