### ISSUE TITLE
A7 - Improved styling in Astar portal

### ISSUE THREAD

**Issue by impelcrypto** [PlasmNetwork/growth-program#693]
- Fixed Tab's 'height' and 'margin' size. [PR](https://github.com/PlasmNetwork/astar-apps/pull/62)
 - Fixed styling broken for Transferable Balance UI . [PR](https://github.com/PlasmNetwork/astar-apps/pull/61)
 - Improved styling for language dropdown for mobile browser [PR](https://github.com/PlasmNetwork/astar-apps/pull/54)
 - Removed space before 'extension' in account UI [PR](https://github.com/PlasmNetwork/astar-apps/pull/76)
 - Removed the default '0' value in `Input` [PR](https://github.com/PlasmNetwork/astar-apps/pull/75)
 - Fixed avatar icon [PR](https://github.com/PlasmNetwork/astar-apps/pull/67)
 - Fixed 'toggle theme mode' bug [PR](https://github.com/PlasmNetwork/astar-apps/pull/72)

SDN address: avf5nPmTfztUfq3gi1Bm3vBcEUHghUyrqRppXmsmDZ5hfrD
email: impelcrypto@gmail.com

**Comment by fiexer** [comment]
The scores put the importance of the work and the time into consideration.
Added!
