### ISSUE TITLE
A7 - Added new features in Astar portal

### ISSUE THREAD

**Issue by impelcrypto** [PlasmNetwork/growth-program#694]
- Added subscan link [PR](https://github.com/PlasmNetwork/astar-apps/pull/66)
- Added Address UI in sidebar [PR](https://github.com/PlasmNetwork/astar-apps/pull/63)
- Added `vested` and `locked` value in the Balance UI [PR](https://github.com/PlasmNetwork/astar-apps/pull/59)
- Setup the `lint` configs, added content about `How To Contribute` in `readme`, and format codes. [PR](https://github.com/PlasmNetwork/astar-apps/pull/78)

SDN address: avf5nPmTfztUfq3gi1Bm3vBcEUHghUyrqRppXmsmDZ5hfrD
email: impelcrypto@gmail.com

**Comment by fiexer** [comment]
The scores put the importance of the work and the time into consideration.
Added!
