### ISSUE TITLE
A8 - Meme about astar

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#695]
Meme about astar in twitter 
https://twitter.com/AstarPersian/status/1448727915814850560?t=-66ttfJxcpyJZrUsDw5nXQ&s=19

Discord handle: pooya$0847
Telegram handle: https://t.me/Persian_ambassador
SDN wallet:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Memes are no longer supported in the community rewards program.
