### ISSUE TITLE
A8 - Art work About Shiden/Astar by Absorberch#0341

### ISSUE THREAD

**Issue by absorberch** [PlasmNetwork/growth-program#696]
My art work - https://twitter.com/AndyHODL/status/1448067822412836875?s=20

My Shiden address - Z1jASjGDgtikEn6Vr5hmR7dQYNxSfFZHgS9D96nDBs2aY8b
Node name - absnode
Discord - Absorberch#341
Twitter - @andyhodl

**Comment by fiexer** [comment]
Already rewarded in the Challenge contribution.
