### ISSUE TITLE
C2 - Community Management - Italian Community 🇮🇹

### ISSUE THREAD

**Issue by Poggi-Luca** [PlasmNetwork/growth-program#70]
Hello everyone,

I'm Luca Poggi from Italy and I'm an Official Ambassadors of Astar Network.
Let me introduce........ I discovered Astar (previously Astar) before 1st Lockdrop. Right after my partecipation in the 1st Lockdrop, I created the Astar Italian Community Telegram group (https://t.me/AstarShidenNetworkItalia)
Thanks to this group I started to build the Astar Italian Community which counts about 208 members at the moment.
You may remember me, because during the 2nd Lockdrop, I made the pdf guide that helped a lot of people: https://github.com/Poggi-Luca/Plasm-Network-Lockdrop-Guide/blob/master/Plasm%20Network%202nd%20Lockdrop%20Step%20by%20Step%20Guide%20-%20Rev.%201%20-%20EN.pdf
I'm supporting Shiden running :ice_cube: Iceberg Nodes :ice_cube: collators

Future Plans:
- Increase italian community
- Coordinate the translations work of docs.astar.network involving active italian members (I started alone to translate some content in the past)
- Organize online Meetup and Calls on Italian TG Group

My Telegram Username: @LucaPoggi
Discord Username: GaGa7#6937
Shiden Address: Yr7ZxQJX6Ho4qBFywoA5hvFSxpBtLQv5T4LnLpzy3MffKJa

**Comment by fiexer** [comment]
Can you make me admin in the Italian community so I can see the stats of the community?
Thanks for your contributions.

**Comment by Poggi-Luca** [comment]
Done! :+1:
