### ISSUE TITLE
A2 - Shiden Network Meme Campaign Creation and Management

### ISSUE THREAD

**Issue by jimmy-tudeski** [PlasmNetwork/growth-program#71]
Stakenode as Astar Network Ambassador, along with Elevate Community Ventures (Community Management and Development Organisation) is Launching Shiden Network Listing Week Meme Campaign. 

We want to entertain the Shiden community and create community engagement on top of Shiden Network and SDN token listing on various exchanges. We want to educate our present users and invite new users from the ecosystem to join the Shiden Network community and be a part of its future growth and development. To achieve this we implied an educational theme into the campaign design. 
We underlined Shiden Network's uniqueness in the campaign description and campaign tasks. Users will be asked to create memes about Shiden Network's unique functions and utilities. 

1. We created Meme Campaign design and competition rules and put them into the medium post.
https://medium.com/@stakenode/shiden-network-multi-chain-dapp-hub-on-kusama-listing-week-meme-campaign-a968bba8f591
2. We created and funded the rewards pool for the Meme campaign
3. We created a promo video for the Campaign:
https://www.youtube.com/watch?v=0iL40wP3ctI
4. We created the Shiden Network Wallet Account creation tutorial, as campaign details require users to give their wallet addresses for rewards distribution:
https://www.youtube.com/watch?v=gRiL20cBH_o
5. We created a google form for users to post their campaign entries:
https://docs.google.com/forms/d/e/1FAIpQLSeh3aiVMUGosE5K4wN1DixOwbztTGWYMp43IGSbfXvQCsZ1Yg/viewform?usp=sf_link
6. We will collect all entries data and transfer them to Shiden Network Council for validation and reward prize distribution.

We hope to see a lot of activity around the campaign and are happy to work with Shiden and Astar Team to support project development and build Shiden and Astar's organic and user-friendly ecosystem. 

Jimmy from Stakenode & Elevate

**Comment by SotaWatanabe** [comment]
Hello, @jimmy-tudeski Thank you very much for your hard work! I saw a lot of your great outputs. Would it be possible to post these on Discord as well?

**Comment by jimmy-tudeski** [comment]
Sure, Just wanted first to have Your acceptance for the campaign, and then I will post those on all official Astar social media and channels like telegram and discord. Just please if can give me a green light so I can proceed with the Meme Campaign Launch tomorrow at 12:00 CET.

**Comment by fiexer** [comment]
Great work Jimmy!
Let us know if you need any help from us.
