### ISSUE TITLE
A4-Represented Astar at The Blockchain Club of Uganda Convention

### ISSUE THREAD

**Issue by Mucunguzi256** [PlasmNetwork/growth-program#714]
I represented Aster at the Blockchain Club of Uganda convention held at Makerere University. This was held on 10th August and attended by and audience of 250 physically and about 500 virtually. The audience was comprised of the academia, researchers, common students and the larger community. The rest of the communities present were Polkadot, Near, Umbrella and Cainlink. I had 30 minutes presentation about the incentivizing early developers by Astar and the Need to build a formidable blockchain infrastructure in Africa.
https://drive.google.com/drive/folders/1-F44sh18vHVzNncqjxgy4ApgKkeiLQet?usp=sharing

Discord 
Mucu256#3205

SDN Address
Wr3L92YY3fcyCWAPFEKxbwLKHwo7mtf5ShNWJfn9xizzQjT

**Comment by fiexer** [comment]
Points added
