### ISSUE TITLE
A1 - Translation/Rewrite article by Alexmed911

### ISSUE THREAD

**Issue by Alexmed911** [PlasmNetwork/growth-program#718]
Twitter : @LeonFuse
Discord: alexmed#5188
Shiden wallet: bURRxf37gBbwUvHmxKHGBdmjQ61JexocDfA3aXfDUw8SaNM

Translation Russian

1) https://takeshikovaks.medium.com/%D0%BA%D1%80%D0%B0%D1%83%D0%B4%D0%BB%D0%BE%D0%BD-astar-network-%D1%87%D0%B0%D1%81%D1%82%D1%8C-i-a41a30add9f7

2) https://takeshikovaks.medium.com/dapp-%D1%81%D1%82%D0%B5%D0%B9%D0%BA%D0%B8%D0%BD%D0%B3-%D1%81%D1%82%D1%80%D0%B5%D1%81%D1%81-%D1%82%D0%B5%D1%81%D1%82-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-shibuya-b516aa7ba373

3) https://takeshikovaks.medium.com/staking-dapp-%D1%83%D0%B6%D0%B5-%D0%B7%D0%B0%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%B0-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-shiden-5875b36edc5b

4) https://takeshikovaks.medium.com/%D0%BE-%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B8-astar-network-%D1%81%D0%B5%D1%82%D1%8C-%D1%88%D0%B8%D0%B4%D0%B5%D0%BD-cc763749eaed

5) https://takeshikovaks.medium.com/bware-labs-присоединяется-к-нашей-экосистеме-в-качестве-одного-из-наших-партнеров-по-обслуживанию-172dc7b6d11

6) https://takeshikovaks.medium.com/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-22-cf213f2cb1e5

7) https://takeshikovaks.medium.com/okex-%D0%B8%D0%BD%D0%B2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D1%83%D0%B5%D1%82-%D0%B2-%D1%81%D0%B5%D1%82%D1%8C-astar-85a3d30e587f

8) https://takeshikovaks.medium.com/%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-growth-fund-%D1%8D%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-astar-shiden-%D0%B2-%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%80%D0%B5-30-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%BE%D0%B2-%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80%D0%BE%D0%B2-%D1%81%D1%88%D0%B0-25b0ee77ebff

9) https://takeshikovaks.medium.com/standard-protocol-%D0%BF%D1%80%D0%B8%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D1%8F%D0%B5%D1%82%D1%81%D1%8F-%D0%BA-astars-builders-program-%D0%B8-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D1%82-%D0%B3%D1%80%D0%B0%D0%BD%D1%82-ef2d5e9ce144

10) https://takeshikovaks.medium.com/%D0%BE%D1%84%D0%B8%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D1%81%D0%B5%D1%82%D0%B8-shiden-aa0bddf7616a

11) https://takeshikovaks.medium.com/nfty-labs-%D0%BF%D1%80%D0%B8%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D1%8F%D0%B5%D1%82%D1%81%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B5-builders-5c96050a2139

12) https://takeshikovaks.medium.com/%D1%81%D0%BE%D1%82%D1%80%D1%83%D0%B4%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE-shiden-%D1%81-covalent-1730522c941a

13) https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0-astar-community-ec6e868616ef

14) https://takeshikovaks.medium.com/onfinality-%D0%B8%D0%BD%D1%84%D1%80%D0%B0%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B0%D1%80%D1%82%D0%BD%D0%B5%D1%80-astar-7fe27082c08f

15) https://takeshikovaks.medium.com/%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0-evm-nft-719902854a99

16) https://takeshikovaks.medium.com/%D1%81%D0%B5%D1%82%D1%8C-astar-%D0%B7%D0%B0%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D0%B5%D1%82-%D1%80%D0%B0%D1%83%D0%BD%D0%B4-%D1%81%D1%82%D0%BE%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C%D1%8E-2-4-%D0%BC%D0%BB%D0%BD-%D0%B4%D0%BE%D0%BB%D0%BB%D0%B0%D1%80%D0%BE%D0%B2-%D0%B2%D0%BE-%D0%B3%D0%BB%D0%B0%D0%B2%D0%B5-%D1%81-binance-labs-daae69a756e8

17) https://takeshikovaks.medium.com/%D0%BF%D0%B5%D1%80%D0%B2%D0%B0%D1%8F-%D1%83%D1%81%D0%BF%D0%B5%D1%88%D0%BD%D0%B0%D1%8F-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-%D0%BF%D0%BE-%D1%86%D0%B5%D0%BF%D0%BE%D1%87%D0%BA%D0%B5-xcmp-%D0%B2-%D1%82%D0%B5%D1%81%D1%82%D0%BE%D0%B2%D0%BE%D0%B9-%D1%81%D0%B5%D1%82%D0%B8-polkadot-28fc000d10c

18) https://takeshikovaks.medium.com/microsoft-japan-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D1%8F%D0%B5%D1%82-%D0%BE-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B5-%D0%B2-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D1%8D%D0%BA%D0%BE%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-astar-shiden-f548b16bb189

19) https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%BE%D1%82%D0%BE%D0%BA%D0%BE%D0%BB-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8-%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B9-xcmp-%D1%81-%D0%BA%D0%B0%D0%B9%D0%BB%D0%B8%D0%BD%D0%BE%D0%BC-3ab509dfb44d

20) https://takeshikovaks.medium.com/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-21-995ab1d49f66

21) https://takeshikovaks.medium.com/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-20-2374f55e1454

22) https://takeshikovaks.medium.com/%D0%B0%D0%BD%D0%BE%D0%BD%D1%81-astar-v2-0-astar-v2-0-multi-chain-dapp-hub-d3e4b2da87a7

23) https://takeshikovaks.medium.com/astar-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B0%D0%B5%D1%82-%D0%B3%D1%80%D0%B0%D0%BD%D1%82-web3-%D0%BD%D0%B0-%D0%B2%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-zk-plonk-%D0%B2-polkadot-8692eaf07802

24) https://takeshikovaks.medium.com/plasm-%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%B8%D1%82-%D1%80%D0%B5%D0%B1%D1%80%D0%B5%D0%BD%D0%B4%D0%B8%D0%BD%D0%B3-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-astar-fa51b234e35

25) https://takeshikovaks.medium.com/%D1%81%D0%B5%D1%82%D1%8C-astar-%D0%BF%D1%80%D0%B8%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D1%8F%D0%B5%D1%82%D1%81%D1%8F-%D0%BA-%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BE-%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%BA%D0%BB%D0%B8%D0%BC%D0%B0%D1%82%D0%B5-crypto-climate-accord-7f15a4aa2877

26) https://takeshikovaks.medium.com/%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC-x-%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%83%D1%8E-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D1%83-%D0%B2-%D1%81%D0%B5%D1%82%D0%B8-shiden-716b916ef692 

27) https://takeshikovaks.medium.com/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-19-715defd6e783 

28) https://takeshikovaks.medium.com/%D0%B5%D0%B6%D0%B5%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-18-9320dfad01a0

**Comment by Alexmed911** [comment]
![Снимок экрана от 2021-10-31 12-18-20](https://user-images.githubusercontent.com/87994565/139578005-d95ace64-eec7-4f49-917c-cd91607b117a.png)

**Comment by fiexer** [comment]
Please provide me with where those articles got shared.
Thanks

Added our Russian Ambassador to check this.

**Comment by Alexmed911** [comment]
> Please provide me with where those articles got shared. Thanks
> 
> Added our Russian Ambassador to check this.

There are organic views from the medium, but I also drop articles in telegram chats about projects on Polkadot / Parachain auctions 
![photo_2021-11-07_22-58-02](https://user-images.githubusercontent.com/87994565/140661853-d592d6f1-020a-45f5-b624-efc485f97fe5.jpg)

**Comment by fiexer** [comment]
Added!

**Comment by vladylime** [comment]
I checked everything, translated through Google. BUT! he fixed the mistakes that google makes.
Translations are good, but sometimes difficult because of the choice of words
