### ISSUE TITLE
A1 - 2 Articles on promoting Astar and Shiden network.（日本語 note 記事投稿）_001_210901_さとわん＠仮想通貨

### ISSUE THREAD

**Issue by kom5566** [PlasmNetwork/growth-program#72]
1.【第１回】Astar Network（旧Plasm Network）ことはじめ【日本発パブリックブロックチェーン/ASTA(PLM)/SDN】
[https://note.com/satowan_crypto/n/n4ab5c8d1162e](https://note.com/satowan_crypto/n/n4ab5c8d1162e)
Twitter Post [https://twitter.com/Kasumi_Sato_JP/status/1433077581234929664:](https://twitter.com/Kasumi_Sato_JP/status/1433077581234929664)

2.【第２回】Astar Network（旧Plasm Network）ことはじめ【日本発パブリックブロックチェーン/ASTA(PLM)/SDN】
[https://note.com/satowan_crypto/n/nb90e6836c23b](https://note.com/satowan_crypto/n/nb90e6836c23b)
Twitter Post URL: [https://twitter.com/Kasumi_Sato_JP/status/1426391199359770624](https://twitter.com/Kasumi_Sato_JP/status/1426391199359770624)

telegram handle: @satowan0226
my Shiden wallet address: Zt4PcDJZs1mQ6d7ya6vSy4qF44JKN6EgjQ9F45ZZU3keiTz
Discord: st0226#0874
Twitter: @Kasumi_Sato_JP

**Comment by fiexer** [comment]
Hi

Thanks a lot for your contributions.
I don't know note.com but is it possible to see stats on articles you publish on note?

Thanks for your feedback.

**Comment by kom5566** [comment]
For translation of the article only.
