### ISSUE TITLE
A3 - Video on promoting Shiden network in YouTube.（日本語YouTube動画投稿）_002_210901_さとわん＠仮想通貨）

### ISSUE THREAD

**Issue by kom5566** [PlasmNetwork/growth-program#73]
1.【ポルカドット】Shiden Networkの今後数週間の動きと予想【日本発パブリックブロックチェーン】
[https://www.youtube.com/watch?v=z5EqX5WZGZA&t=173s](https://www.youtube.com/watch?v=z5EqX5WZGZA&t=173s)
Twitter Post [https://twitter.com/Kasumi_Sato_JP/status/1433078063663771653](https://twitter.com/Kasumi_Sato_JP/status/1433078063663771653)

telegram handle: @satowan0226
my Shiden wallet address: Zt4PcDJZs1mQ6d7ya6vSy4qF44JKN6EgjQ9F45ZZU3keiTz
Discord: st0226#874
Twitter: @Kasumi_Sato_JP

**Comment by SotaWatanabe** [comment]
Hello @kom5566

Could you share the Twitter URL of this post? If you don't share these on Twitter, please do. And please share this great video in our Japanese Telegram and Discord community?

Best,
Sota

**Comment by kom5566** [comment]
Thanks, I've added the Twitter post URL. Thank you very much.

**Comment by fiexer** [comment]
Great work!

Total points: 12
Feedback is always welcome, if not this issue will be closed at the end of the month.
