### ISSUE TITLE
A8 - Meme about shiden

### ISSUE THREAD

**Issue by Persianboy1382** [PlasmNetwork/growth-program#733]
Meme about shiden
https://twitter.com/AstarPersian/status/1449071260491714564?t=NL1MLKqidFoTpDFkFcnM3g&s=19

Discord handle: pooya #0847 
Telegram handle: https://t.me/Persian_ambassador
SDN address:
bWqVyk34jzcjQwsatdHMTquXzaoJ3Fy9VW1wBbbYck6h4wR

**Comment by fiexer** [comment]
Memes are no long supported in the community rewards program.
