### ISSUE TITLE
A1 - Translate DApp staking of Shibuya and Shiden article to Japanese 

### ISSUE THREAD

**Issue by realtakahashi** [PlasmNetwork/growth-program#734]
https://medium.com/stake-technologies-japan/dapp-staking%E3%82%B9%E3%83%88%E3%83%AC%E3%82%B9%E3%83%86%E3%82%B9%E3%83%88-shibuya%E3%83%86%E3%82%B9%E3%83%88%E3%83%8D%E3%83%83%E3%83%88-9f4cb47ebe21

https://medium.com/stake-technologies-japan/dapp-staking-is-live-on-shiden-network-build2earn-f049d76db3d0

**Comment by fiexer** [comment]
Please share your stats after 2 weeks of publishing.
These stats are needed to finalize your points.

How to see stats:
[https://help.medium.com/hc/en-us/articles/215108608-Your-stats](https://help.medium.com/hc/en-us/articles/215108608-Your-stats)

**Comment by realtakahashi** [comment]
<img width="496" alt="スクリーンショット 2021-11-08 19 59 51" src="https://user-images.githubusercontent.com/38233656/141015175-129c861f-b912-43d2-86c4-d5515ba0c78f.png">
<img width="375" alt="スクリーンショット 2021-11-08 19 55 49" src="https://user-images.githubusercontent.com/38233656/141015177-70b410d5-4ebb-44ad-86bd-058bd898c1d8.png">

**Comment by fiexer** [comment]
Added!
