### ISSUE TITLE
A1 - I translated two articles into Japanese and posted them on my own media (note).（日本語 note 記事投稿）_003_210901_さとわん＠仮想通貨

### ISSUE THREAD

**Issue by kom5566** [PlasmNetwork/growth-program#74]
1.【ASTA/SDN】OnFinalityとのIaaS記事翻訳調査(インフラストラクチャーパートナー)【ビルターズプログラム】
[https://note.com/satowan_crypto/n/n5c8ce1c42aaf](https://note.com/satowan_crypto/n/n5c8ce1c42aaf)
Twitter Post:[https://twitter.com/Kasumi_Sato_JP/status/1432668890937507843:](https://twitter.com/Kasumi_Sato_JP/status/1432668890937507843)

2.【ASTA/SDN】Covalent API翻訳調査【ビルターズプログラム】
[https://note.com/satowan_crypto/n/nc9a25bb376e8](https://note.com/satowan_crypto/n/nc9a25bb376e8)
Twitter Post [https://twitter.com/Kasumi_Sato_JP/status/1432668890937507843:](https://twitter.com/Kasumi_Sato_JP/status/1432668890937507843)

telegram handle: @satowan0226
my Shiden wallet address: Zt4PcDJZs1mQ6d7ya6vSy4qF44JKN6EgjQ9F45ZZU3keiTz
Discord: st0226#874
Twitter: @Kasumi_Sato_JP

**Comment by SotaWatanabe** [comment]
Hello @kom5566 

Could you share the Twitter URL of this post? If you don't share these on Twitter, please do. And please share these great articles in our Japanese Telegram community?

Best,
Sota

**Comment by kom5566** [comment]
Thanks, I've added the Twitter post URL. Thank you very much.

**Comment by fiexer** [comment]
Hi

Thanks a lot for your contributions.
I don't know note.com but is it possible to see stats on articles you publish on note?

Thanks for your feedback.

**Comment by kom5566** [comment]
For translation of the article only.
