### ISSUE TITLE
NFTart of Plasm Network (Astar) 

### ISSUE THREAD

**Issue by robert6662** [PlasmNetwork/growth-program#75]
Twitter: https://twitter.com/stakenode_dev/status/1375139295967784965 (Thanks Jimmy for a tweet)

OpenSea: https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/10824196917330709098701303069498069997674252073229714640171830476318628118529  (I sent 2 Queens of Plasm to Polkapet Plasm NFT whale) 

OpenSea: https://opensea.io/assets/0x1cca97e4592053c481abb753c4c631ccdf8d341a/74322988700649838191149397625782199255 (mine account) 

Twitter: @KarwataRobert
Discord: NFTcoach#2831
Telegram handle: @bobiiione
my Shiden wallet address:  WAugdTLZVhBtxjkeGN2EHCWUL8o6oRuHakszw1DKu1oTRgt

![ExV55VvXMAAWbHU](https://user-images.githubusercontent.com/36108630/131721168-6a85c1fd-d9f8-47ae-8dc9-48f0ff530c3d.jpg)

**Comment by fiexer** [comment]
It's a great piece of art!
For the community program, we can max except contributions made in August.
