### ISSUE TITLE
A8 - I create an illustration for Astar Network

### ISSUE THREAD

**Issue by Oswald2395** [PlasmNetwork/growth-program#76]
Twitter: @AkpedjeR
Telegram: @Akpedje23
Discord: Brunel#7117
Shiden address: YPCidGxhNTZRUWtAh4by8WpwsqQ67yLvLhERvUVNBv9sM2j

This illustration is about reaching Astar. Especially for those who aren't in the Astar's system. The title is "La quête..."

This is the URL :
https://twitter.com/AkpedjeR/status/1433177707605417984?t=Tqdwk2js6k61nYSZwlGhJA&s=19

**Comment by fiexer** [comment]
![image](https://user-images.githubusercontent.com/36227274/132255969-a4daf90c-d47f-4824-802d-9694129927b6.png)

Great piece of art!
Like the design. 

Total points: 8

Feedback is always welcome, if not this issue will be closed at the end of the month.

**Comment by Oswald2395** [comment]
Thanks... I really appreciate.
