### ISSUE TITLE
A5 - Social engagement invitation for Astar/Shiden progress status

### ISSUE THREAD

**Issue by anaelleltd** [PlasmNetwork/growth-program#768]
Topic: Shiden's roadmap progress
Links: I have made the following posts on r/Kusama and r/ShidenNetwork (NB: Posts' statistics/insights only became available on Reddit after 28th September)
Shiden wallet: Z1fHUw3G38sDiuJ8mGBGoiCJwyV5Qg2zdrNxzV49Drhf2ft

1. [DApp staking is aggregating blockchain innovation onto Shiden network.](https://www.reddit.com/r/Kusama/comments/ptpygt/dapp_staking_is_aggregating_blockchain_innovation/)
![SDN_DappBuilders](https://user-images.githubusercontent.com/44770354/137607571-344c4c96-371c-45b7-a113-c8ae9e4ed156.JPG)

2. [Kwikswap is the first Dapp to go live on Shiden Network](https://www.reddit.com/r/ShidenNetwork/comments/q0bnda/kwikswap_is_the_first_dex_to_go_live_on_shiden/)
![SDN_Kwikswap](https://user-images.githubusercontent.com/44770354/137607587-518be2b8-b3c9-4adf-a68f-f6bd08eeb5f8.JPG)

3. [dApp staking stress test on Shibuya](https://www.reddit.com/r/ShidenNetwork/comments/q33vik/dapp_staking_stress_test_on_shibuya/) 
![SDN_Shibuya](https://user-images.githubusercontent.com/44770354/137607607-25f87c15-8bee-4527-9759-ffedd362d913.JPG)

4. [Dapp staking innovation is brought to you by Shiden Network!](https://www.reddit.com/r/Kusama/comments/q7v559/dapp_staking_innovation_is_brought_to_you_by/)
![SDN_Shiden](https://user-images.githubusercontent.com/44770354/137607628-e78aa51c-a322-4226-85bf-054b34bca457.JPG)

**Comment by fiexer** [comment]
Added
