### ISSUE TITLE
C1 / C2 - A1 A3  A5 A6 and other cool activity :) - PromoTeam Q1-Q2 March/May/June/July report

### ISSUE THREAD

**Issue by GlobalSG** [PlasmNetwork/growth-program#8]
PromoTeam March/May/June/July report and short self presentation .

Polkadot Ecosystem PromoTeam — global and regional adoption of Polkadot/Kusama. We are the international team of Web3 fans. Twitter - https://twitter.com/PromoTeamPD / medium - https://medium.com/polkadot-ecosystem-promoteam / YouTube -https://www.youtube.com/c/PromoTeamChannel 

1.PromoTeam and Astar Community. - Alex and Vlady - are ambassadors of Astar.  All PromoTeam members support Astar not being ambassadors. We have about  7 specialists actively involved in production, support and promotion. All of them are supporters and conributors of the project and community members. 
2.Alex contribute for Astar/Plasm from the early days of the project , from the first Lockdrop times. And Vlady contribute from second lockdrop times.
3.We did a lot of activities to promote and make Plasm/Astar/Shiden well known and understand. We support russian community of the project. Doing tons of mentions of Astar on different resources. Doing tons of content.
4.Its cool that ambassadors contributions are going to be valued and rewarded well. It will help our team to do more and grow faster
5.We want some our previous work will be valued and rewarded, so here is the report from March to July 2021
 
**Here is the link to full report**
https://docs.google.com/spreadsheets/d/15-JM6TsV4eoF37EmJVviHF13i841AIeN5-Hnbivz1fY/edit?usp=sharing

**Comment by fiexer** [comment]
Please create one issue for each contribution.

- Your report stated C1: can you share more about the projects you introduced to us?
- Ambassador status is not with PromoTeam but with individual users of the team? Or do we need to combine all work from Vlady and you to PromoTeam?
- You also mention other users in your full report, but they are not Ambassadors in our program?
- During this test phase, do not list previous work. Previous work will not be included in the quarterly pool but will be rewarded differently.
