### ISSUE TITLE
A1 - Translated 1 article into Thai and published in my medium

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#83]
https://medium.com/@panupong.astar/%E0%B8%A3%E0%B8%B9%E0%B9%89%E0%B8%88%E0%B8%B1%E0%B8%81%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B8%82%E0%B9%88%E0%B8%B2%E0%B8%A2-shiden-%E0%B9%81%E0%B8%A5%E0%B8%B0-astar-2da060dc48b0

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

currently, I am planning to increase more members on Thai Telegram Community, will publish more Thai article!

**Comment by pnpdude** [comment]
I also shared the translated article on Blockdit, Thai Community Reader.

https://www.blockdit.com/posts/61325d011bb13b30fa587003

**Comment by pnpdude** [comment]
I have to edit new address because the last one is my experiment.

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10
