### ISSUE TITLE
A1-FAQ about rebranding Plasm Network to Astar Network in Russian

### ISSUE THREAD

**Issue by kubvil** [PlasmNetwork/growth-program#85]
FAQ about rebranding Plasm Network to Astar Network in Russian

https://kak-uchastvovat-v-parachejn-aukc.gitbook.io/kubvil/chasto-zadavaemye-voprosy-o-rebrendinge-plasm-network-v-astar-network
telegram handle: @kubvil88
my Shiden wallet address: WBR6xowc6fNGhKkJgaF5ELx4UfLVjr14iFdpXqJ5w9jZMC5
Discord kubvil#4326

**Comment by fiexer** [comment]
Please share the stats for this translation please.
Thanks
