### ISSUE TITLE
A1 - Translated 2 articles into Thai and published in my medium and social media

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#86]
Here is an translated article about Collaboration between Microsoft and Plasm, I post on Medium and Blockdit

https://panupongpnp.medium.com/astar-plasm-%E0%B9%84%E0%B8%94%E0%B9%89%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B9%80%E0%B8%A5%E0%B8%B7%E0%B8%AD%E0%B8%81%E0%B8%88%E0%B8%B2%E0%B8%81-microsoft-%E0%B9%80%E0%B8%82%E0%B9%89%E0%B8%B2%E0%B8%A3%E0%B9%88%E0%B8%A7%E0%B8%A1-startup-program-e2c983f3b9b2

https://www.blockdit.com/posts/613372117cf06e0c5d3e1788

Here is an translated article about Meme campaign on Medium

https://panupongpnp.medium.com/%E0%B8%A3%E0%B9%88%E0%B8%A7%E0%B8%A1%E0%B8%81%E0%B8%B4%E0%B8%88%E0%B8%81%E0%B8%A3%E0%B8%A3%E0%B8%A1-%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87-meme-%E0%B8%8A%E0%B8%B4%E0%B8%87%E0%B8%A3%E0%B8%B2%E0%B8%87%E0%B8%A7%E0%B8%B1%E0%B8%A5%E0%B8%81%E0%B8%B1%E0%B8%9A-shiden-network-26f661202e9d

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by pnpdude** [comment]
I have to edit new address because the last one is my experiment.

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10
