### ISSUE TITLE
A2 -   Creating interesting memes and post it on my Twitter

### ISSUE THREAD

**Issue by pnpdude** [PlasmNetwork/growth-program#87]
https://twitter.com/pnpcanary/status/1434473606285692930?s=20
I will also add this to my rebrand article.

telegram handle: @pnp_404
my Shiden wallet address: Z7uxrY7GXF2dZFuxGV6EbjcpXWSAixSX1AeMjSuHDuzWUJF

**Comment by fiexer** [comment]
hehe funny!

Reward points: 1
