### ISSUE TITLE
A1 - Translated 1 article on community programs into Japanese

### ISSUE THREAD

**Issue by pitapa** [PlasmNetwork/growth-program#88]
Astarコミュニティプログラムの概要と参加方法 (Overview of the Astar Community Program and how to participate)
https://pencamblog.com/astar_community_program/
https://twitter.com/pencam_picon/status/1434485345366646787?s=20

Shiden wallet address: bBf4szdFiqgy6MPjXgn8WxXHTwhChnrEp9DdK1e2Rd3qdhd
Discord: pipipi#4745
Twitter: @pencam_picon

1-210905-picon

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10

**Comment by SotaWatanabe** [comment]
Thanks for working on this. Please teach me how well the article and movie were spread. We don't fund SDN for activities themselves but fund for the viewers etc.

**Comment by pitapa** [comment]
Thanks for your comment sota-san!
コメントありがとうございます！ここからは日本語で書きますね。
pv数8なので、全然読まれてないですね...
ご指摘の通りと思いますので、翻訳ではなく、別の形で貢献できるよう検討します！

**Comment by fiexer** [comment]
Please do share your stats for this article or it will not be counted for the September rewards.

**Comment by pitapa** [comment]
The number of page view is 10.
Thanks for your comments.

**Comment by fiexer** [comment]
Total points: 2
