### ISSUE TITLE
C2 - Community Management - Korean Community

### ISSUE THREAD

**Issue by RHEEUNION** [PlasmNetwork/growth-program#89]
Hello everyone,
I'm `RHEE` from South Korea and I'm an Official Ambassador of Astar Network.

**[Background]**
1. I discovered Astar(previously Plasm) during 2nd Lockdrop. I was very interested to become one of validators(current collator), so talked to Hoon and created Astar Korean Community Telegram group (https://t.me/astar_kr)
- Current Community Size: 206 members (Around 30% are active in interactions)
- Creation Date: September 4th, 2020 (🎉**It's the 1 Anniversary Day of Korean Community**🎉)
- 5 Time CS-Zoom call with individual holders to solve their problems.
- 24/7 Community Management ongoing.
2. I have translated @Poggi-Luca 's Lockdrop Participation guide(https://github.com/Poggi-Luca/Plasm-Network-Lockdrop-Guide/blob/master/Plasm%20Network%202nd%20Lockdrop%20Step%20by%20Step%20Guide%20-%20Rev.%201%20-%20EN.pdf) into Korean and helped around 200 people into get around our project.
3. I'm also supporting Shiden running `RHEEUNION` collator-node,
while also helping testing Dusty5/3 with Collator Warriors guided by Mario and Maarten.

**[Future Plans]**
1. Increase Korean community members to at least 500 before Polkadot Parachain Auction.
2. Coordinate the translations/paraphrasing work of medium involving active Korean Members (I started alone to paraphrased some content in Official Korean Twitter Account: https://twitter.com/AstarNetwork_KR)
3. Organize 1st Online Parachain Meetup Korea with Live Zoom.

**[Personal Info]**
Telegram Username: @R_BondLy
Discord Username: rheeunion#0605
Shiden Address: bUUve83HysJPyXGfbAPcGdV2YujGPVMqZgM61fio4WTrQSs

**Comment by fiexer** [comment]
Like your future plans! Looking forward.
Always great working with you.

For the month August, I added your points in the sheet.
I will update the sheet end of September for your community work for this month.

**Comment by RHEEUNION** [comment]
@fiexer Me too, Maarten. Thanks for your detailed guide all the time no matter how busy you are.
