### ISSUE TITLE
C1 - Introduced Shiden Network To Projects (Mar - Jul 2021)

### ISSUE THREAD

**Issue by togamamora** [PlasmNetwork/growth-program#9]
Hi, 

I am Toga Mamora.

I introduced Shiden/Astar to a few projects that are planning to be on Polkadot. These are the details.

1. Parakeet Network
- https://www.parakeetnetwork.com/
- Created a private Telegram group.
- Sota and Maarten have had a discussion with their team.
- They have decided to build on Shiden.

2. Composable Finance
- https://www.composable.finance/
- Created a private Telegram group.
- Had a discussion about forming a partnership to support the parachain auction but this topic was halted. 
- However, Maarten and Sota had another meeting session with them on another topic.
 
3. PolkaFantasy
- https://polkafantasy.com/
- A community member introduced this project to me and suggested that he would like to see this project build on Shiden. So I reached out to Alex Hui, the CEO of PolkaFantasy.
- Created a private Telegram group.
- Sota and Maarten have had a discussion with their team. 
- Their team has considered to move forward with the collaboration.

4. Tsunami Protocol
- https://twitter.com/TsunamiProtocol
- Created a private Telegram group.
- Sota and Maarten have had a discussion with their team. 
- They are considering to build on Shiden after they launch on Terra.

5. Open Emoji Battler
- https://game.open-emoji-battler.community/
- I reached out to Tash to build on Shiden, in their discord channel. I also introduced the Builders Program.
- With the support of another Astar community member (@CrypTod#5916), Tash decided to build on Shiden. 
- Though I did not create a private Telegram group for this, Tash told me that he already had a meeting with Sota and Maarten.

6. ETHKL - A group of ETH developers in Malaysia.
- https://www.meetup.com/ETHMALAYSIA/
- Telegram: https://t.me/joinchat/DkuTC01owUXy2hsdJ-k75A
- Introduced Astar and the Builders Program to them.
- Maarten has spoken to the group leaders.
- Planning to do a workshop.

I have also reached out to other projects like Polkacity, Revomon, Emiswap, Omni Ai, Polytrade Finance but yet to get a response from them. I will update all these in the next submission.

Telegram: @TogaMamora
Wallet: WKSs2K1c3nZs8rctvhLt8mA5vPJEMm11Ld8Ucxd9Mugbtg2

**Comment by fiexer** [comment]
Great work Tiger!
I will add this to your account but next one issue for each project.

Open Emoji Battler
I'm not aware of a meeting with him.

**Comment by cryptodmeme** [comment]
hi, I'm [CrypTod#5916] Open Emoji Battler is a great game. Thanks for the great communication. And I will support with memes.

**Comment by tash-2s** [comment]
Hi from Open Emoji Battler.

> Tash told me that he already had a meeting with Sota and Maarten.

This is incorrect. I talked with Shun from Astar. 😄 

<img width="707" alt="Screen Shot 2021-08-24 at 12 54 55" src="https://user-images.githubusercontent.com/81064017/130553345-59d2e73c-a129-47c5-afdc-5303496a12b9.png">

**Comment by togamamora** [comment]
> Hi from Open Emoji Battler.
> 
> > Tash told me that he already had a meeting with Sota and Maarten.
> 
> This is incorrect. I talked with Shun from Astar. 😄
> 
> <img alt="Screen Shot 2021-08-24 at 12 54 55" width="707" src="https://user-images.githubusercontent.com/81064017/130553345-59d2e73c-a129-47c5-afdc-5303496a12b9.png">

Thanks for the clarification.

**Comment by fiexer** [comment]
Points will be calculated at the end of September.
Comments are added to the spreadsheet. 

Current status:
Parakeet Network: renamed to Avem (ongoing)
Composable Finance: 
PolkaFantasy: ongoing
Tsunami Protocol: ongoing
ETHKL: not more talks
Open Emoji Battler: applied to the builders program
