### ISSUE TITLE
A3 - Video presentation of Astar network in YouTube.

### ISSUE THREAD

**Issue by boodovskiy** [PlasmNetwork/growth-program#91]
https://youtu.be/NpF7SFqCa_A
Twitter post: https://twitter.com/boodovskiy/status/1434577265451544577

Discord: budovskiy#4624
Telegram: budovskiy87
Twitter: @boodovskiy

Shiden address: YFTJBnTYxmVES377a1iwnY8SHmNZHYaBhhRPxwBSQ7tKJHq

**Comment by fiexer** [comment]
Thanks for creating this video.
Points will be calculated 2 weeks after publication.

**Comment by fiexer** [comment]
Total points: 7
