### ISSUE TITLE
A1 – Blog article about Astar in French

### ISSUE THREAD

**Issue by Gunit2481** [PlasmNetwork/growth-program#95]
August 2021 :

I created an article to present Astar and Shiden in French :

Astar Network, the gateway to a multi-chain network : https://link.medium.com/auDZvD314ib

I will provide stats when the article is two weeks old.

**Comment by Gunit2481** [comment]
![image](https://user-images.githubusercontent.com/85451570/132606276-c5cafc96-23a9-48e2-bc0f-f2f4b565a7c3.png)

**Comment by fiexer** [comment]
Total reward points: 13
