### ISSUE TITLE
A1 – Translated article into thai

### ISSUE THREAD

**Issue by Strongyloides** [PlasmNetwork/growth-program#99]
https://medium.com/@AndyDufresne_thai/shiden-a-sister-network-of-astar-becomes-a-parachain-%E0%B8%A0%E0%B8%B2%E0%B8%A9%E0%B8%B2%E0%B9%84%E0%B8%97%E0%B8%A2-af70e23a3f1f

discord: viverrinii#0535 
twitter: @caocaovalue
telegram: @caocaovalue
shiden adress: YwG4iSBymPKx7FjCqj7jEacfefinw1jYvKNck3zGm9eRKem

**Comment by fiexer** [comment]
Because of the very low quality of translations, we will only accept translations made by official Ambassadors!
We recommend writing a blog post about the Astar ecosystem instead of doing translations. Thanks!

More information:
https://forum.astar.network/t/start-of-our-community-program/1367/10
